/*****************************************************************************
* VERSION.H
*
*   $Revision:   1.35  $
*   $Author:   MSB  $
*   $Date:   18 Mar 1997 17:00:02  $
*
* Purpose
*   Defines the current software release version info.
*
* Discussion
*    If a local copy is required, just copy this file to the subdirectory and
*    make required changes -- the search order for C should find the local
*    copy before using this one.
*
* Author
*    PWT  24 Apr 90 - created for SETUPDEV (after much discussion)
*
*****************************************************************************/

#define VERSIONTXT "Version 8.0 - July 1997"
#define VERSIONNUM "8.0"
#define VERSIONDATE "July 1997"
