[MICROSIM]
LIBPATH=""C:\MSim_8\UserLib";"C:\MSim_8\lib";"C:\MSim_8\lib\XC5200";"C:\MSim_8\lib\XC4000E";"C:\MSim_8\lib\XC4000";"C:\MSim_8\lib\XC3000";"C:\MSim_8\lib\XC2000";"C:\MSim_8\lib\XBLOX""
BACKUP=C:\MSim_8\backup
VERSION=8.0
BOMATTRS=@PKGTYPE,@VALUE
TEXTEDITCMD=""TEXTEDIT.EXE""
PSPICEADCMD=""PSPICEAD.EXE""
PLSYNCMD=""PLSYN.EXE""
PROBECMD=""PROBE.EXE""
STMEDCMD=""STMED.EXE""
PARTSCMD=""PARTS.EXE""
SCHEMATICSCMD=""PSCHED.EXE""
CCTCMD=""specctra.exe""
OPTIMIZERCMD=""OPTIMIZE.EXE""
MSGVIEWCMD=""MSGVIEW.EXE""
POLARISCMD=""POLARIS.EXE""
POLTRANCMD=""POLTRAN.EXE""
PCBOARDSCMD=""PCBOARDS.EXE""
NETLISTERCMD=""netlist.exe""
XNF2PSCMD=""xnf2ps.exe""
MAINLIBPATH=""C:\MSim_8\lib";"C:\MSim_8\lib\XC5200";"C:\MSim_8\lib\XC4000E";"C:\MSim_8\lib\XC4000";"C:\MSim_8\lib\XC3000";"C:\MSim_8\lib\XC2000";"C:\MSim_8\lib\XBLOX""
[MICROSIM OPTIONS]
PACKAGETYPE=MicroSim
[SCHEMATICS]
LAYOUTCMD=""pcboards.exe""
SIMULATOR=PspiceAD
POLARIS=ON
ZOOMFACTOR=150
VIEWFITPERCENT=95
TEXTHEIGHT=10
DFLTTITLESYM=titleblk
LAYOUTFORMAT=PCBOARDS
[SCHEMATICS COLORS]
WIRE=DARKGREEN
SYMBOLS=DARKGREEN
PINNAME=DARKGREEN
SELECTION=RED
BACKGROUND=BRIGHTWHITE
FOREGROUND=BLUE
[SCHEMATICS DISPLAY MAP]
HIDDENPINS=OFF,OFF
[SCHEMATICS NETLIST]
LINE1=.lib nom.lib
[SCHEMATICS INTERFACES]
PCBOARDS=EXT:.nlf ECOEXT:.bco MAPFILE1:pcboards.xnt PAREX:MSIM REFPINSEP:2 RDBEXT:.si
CADSTAR=EXT:.cdi ECOEXT:.rin MAPFILE:cadstar.xmp MAPFILE1:cadstar.xnt MAPFILE2:cadstar.xpk PAREX:RACAL REFPINSEP:3 RDBEXT:.cdi
EDIF=EXT:.edf MAPFILE:edif.xmp MAPFILE1:edif.xnt MAPFILE2:edif.xpk
ORCAD=EXT:.orc MAPFILE:orcad.xmp MAPFILE1:orcad.xnt MAPFILE2:orcad.xpk
PADS=EXT:.pad ECOEXT:.eco MAPFILE:pads.xmp MAPFILE1:pads.xnt MAPFILE2:pads.xpk PAREX:PADS REFPINSEP:0 RDBEXT:.asc
PCAD=EXT:.alt MAPFILE:pcad.xmp MAPFILE1:pcad.xnt MAPFILE2:pcad.xpk PAREX:PDIF REFPINSEP:1 RDBEXT:.pdf
PROTEL=EXT:.pro ECOEXT:.eco MAPFILE:protel.xmp MAPFILE1:protel.xnt MAPFILE2:protel.xpk PAREX:PROTEL REFPINSEP:2
TANGO=EXT:.tan ECOEXT:.eco MAPFILE:tango.xmp MAPFILE1:tango.xnt MAPFILE2:tango.xpk PAREX:MSIM REFPINSEP:2 RDBEXT:.dbx
SCICARDS=EXT:.UPL ECOEXT:.SIF MAPFILE:scicards.xmp MAPFILE1:scicards.xnt MAPFILE2:scicards.xpk PAREX:PADS REFPINSEP:0
[ORCAD]
PackageTypes=C:\MSim_8\COMMON\package.lst
SymbolMapFile=C:\MSim_8\COMMON\orc_map.txt
ControlFile=C:\MSim_8\COMMON\orc2edi.cfg
PrefixMap=C:\MSim_8\COMMON\prefix.map
DeviceMapFile=C:\MSim_8\COMMON\devmap.ini
[Package Class Order]
DIP=
LCC=
SOIC=
SOJ=
TO=
TSOP=
PQFP=
DISCRETE=
[PACKAGE CLASSES]
DIP=
SOIC=
SOJ=
TO=
TSOP=
PQFP=
DISCRETE=
LCC=
[PACKAGE TYPES]
DIP6=DIP
DIP8=DIP
DIP14=DIP
DIP16=DIP
DIP16X=DIP
DIP18=DIP
DIP20=DIP
DIP22=DIP
DIP22L=DIP
DIP24=DIP
DIP24L=DIP
DIP24X=DIP
DIP28=DIP
DIP28L=DIP
DIP28X=DIP
DIP32=DIP
DIP32X=DIP
DIP36X=DIP
DIP36XX=DIP
DIP40X=DIP
DIP42X=DIP
DIP48X=DIP
DIP50XX=DIP
DIP52XX=DIP
DIP64XX=DIP
LCC18=LCC
LCC20=LCC
LCC28=LCC
SO8=SOIC
SO8W=SOIC
SO14=SOIC
SO14L/MO-046AA=SOIC
SO14W=SOIC
SO16=SOIC
SO16L/MO-046AB=SOIC
SO16W=SOIC
SO20L/MO-046AC=SOIC
SO20W=SOIC
SO24W=SOIC
SO24X=SOIC
SO28W=SOIC
SO28X=SOIC
SO32W=SOIC
SO32X=SOIC
SO36W=SOIC
SO36X=SOIC
SOJ14/300=SOJ
SOJ14/350=SOJ
SOJ16/300=SOJ
SOJ16/350=SOJ
SOJ18/300=SOJ
SOJ18/350=SOJ
SOJ20/300=SOJ
SOJ20/350=SOJ
SOJ22/300=SOJ
SOJ22/350=SOJ
SOJ24/300=SOJ
SOJ24/350=SOJ
TO-3=TO
TO-3-8=TO
TO-3P=TO
TO-5=TO
TO-8=TO
TO-18=TO
TO-39=TO
TO-46=TO
TO-52=TO
TO-64=TO
TO-61=TO
TO-66=TO
TO-78=TO
TO-92=TO
TO-99=TO
TO-100=TO
TO-204=TO
TO-205=TO
TO-206=TO
TO-218=TO
TO-220=TO
TO-226=TO
TO-238=TO
TO-252=TO
TO-254=TO
TSOP6X14-16=TSOP
TSOP6X14-24=TSOP
TSOP6X14-24R=TSOP
TSOP6X16-24=TSOP
TSOP6X18-24=TSOP
TSOP6X18-24R=TSOP
TSOP6X18-28=TSOP
PQFP84=PQFP
PQFP100=PQFP
PQFP132=PQFP
PQFP164=PQFP
PQFP196=PQFP
PQFP244=PQFP
DO-4=DISCRETE
DO-7=DISCRETE
DO-13=DISCRETE
DO-21=DISCRETE
DO-35=DISCRETE
DO-41=DISCRETE
DO-203=DISCRETE
DO-204=DISCRETE
DO-204AA=DISCRETE
DO-208=DISCRETE
[Polaris]
VIA_RADIS=30
PIN_RADIS=30
MIN_COUPLED_LEN=15
[Polaris Excludenets]
NET1=0
NET2=GND
NET3=DIG_GND
NET4=VCC
NET5=+5
[PROBE]
PRBFILE=C:\MSim_8\COMMON\msim.prb
MARKDATAPOINTS=OFF
TRACESYMBOLS=AUTO
TRACECOLORSCHEME=NORMAL
STATUSLINEON=ON
DISPLAYEVALON=OFF
HISTNDIVISIONS=10
HISTSHOWSTATSON=ON
CURSORRIGHT=0
CURSORBOTTOM=0
[PROBE DISPLAY COLORS]
NUMTRACECOLORS=6
BACKGROUND=BLACK
FOREGROUND=WHITE
TRACE_1=BRIGHTGREEN
TRACE_2=BRIGHTRED
TRACE_3=BRIGHTBLUE
TRACE_4=BRIGHTYELLOW
TRACE_5=BRIGHTMAGENTA
TRACE_6=BRIGHTCYAN
[PROBE PRINTER COLORS]
NUMTRACECOLORS=6
BACKGROUND=BRIGHTWHITE
FOREGROUND=BLACK
TRACE_1=GREEN
TRACE_2=RED
TRACE_3=BLUE
TRACE_4=YELLOW
TRACE_5=MAGENTA
TRACE_6=CYAN
[Stimulus Editor]
allowAD=Analog
[Stimulus Editor DISPLAY COLORS]
NUMTRACECOLORS=6
BACKGROUND=BLACK
FOREGROUND=WHITE
TRACE_1=BRIGHTGREEN
TRACE_2=BRIGHTRED
TRACE_3=BRIGHTBLUE
TRACE_4=BRIGHTYELLOW
TRACE_5=BRIGHTMAGENTA
TRACE_6=BRIGHTCYAN
[Stimulus Editor PRINTER COLORS]
NUMTRACECOLORS=6
BACKGROUND=BRIGHTWHITE
FOREGROUND=BLACK
TRACE_1=GREEN
TRACE_2=RED
TRACE_3=BLUE
TRACE_4=YELLOW
TRACE_5=MAGENTA
TRACE_6=CYAN
[PCBOARDS]
DEFAULTPADSTACK=rnd-040-020
XYdigits=3
XYfraction=4
[PCBOARDS FOOTPRINTS]
LIB1=ampdip.flb
LIB2=ampsimm.flb
LIB3=ampzip.flb
LIB4=cap.flb
LIB5=cbga.flb
LIB6=cdip.flb
LIB7=cdipsm.flb
LIB8=cfp.flb
LIB9=chipcap.flb
LIB10=chipres.flb
LIB11=connect.flb
LIB12=cpga.flb
LIB13=cqfp.flb
LIB14=csdip.flb
LIB15=csdipsm.flb
LIB16=dip.flb
LIB17=dipsm.flb
LIB18=discrete.flb
LIB19=dshell.flb
LIB20=edge.flb
LIB21=ims.flb
LIB22=ind.flb
LIB23=japan.flb
LIB24=lcc.flb
LIB25=melf.flb
LIB26=notstd4.flb
LIB27=plcc-rec.flb
LIB28=plcc.flb
LIB29=pqfp.flb
LIB30=resistor.flb
LIB31=sdip.flb
LIB32=sdipsm.flb
LIB33=sip.flb
LIB34=soic.flb
LIB35=soj.flb
LIB36=sop.flb
LIB37=sot_sod.flb
LIB38=sqfpqfpr.flb
LIB39=sqfpqfps.flb
LIB40=ssoic.flb
LIB41=ssop.flb
LIB42=tbga.flb
LIB43=tcap.flb
LIB44=to.flb
LIB45=tsop.flb
LIB46=zip.flb
LIB47=osc.flb
[PCBOARDS PADSTACKS]
LIB1=std.psl
[PCBOARDS DISPLAY COLORS]
backgrRGB=0 0 0
hiliteRGB=192 192 192
selectRGB=255 255 255
snapgrRGB=255 255 255
[PLSyn]
DisplayPrice=ON
OptimizeOpt=
PLSynTrnCmd=PLSYNTRN.EXE
NetlistConvertCmd=plsch.exe
NetlistConvertOpt=EDIF200 -dcomp -flat -EXTEND:ttl0#ttl1#ttl2#ttl3#ttl4#ttl5#ttl6
CompileCmd=plcomp.exe
OptimizeCmd=plopt.exe
ScanCmd=plscan.exe
FitCmd=plfit.exe
FuseMapCmd=plfuse.exe
DocumentCmd=pldoc.exe
CompilerNodeGeneration=FOR_CARRY_BITS
EDIFCfg1=Altera,.edo,ALTPRIMS
EDIFCfg2=Generic,.edf,PLDPRIMS,TTL0,TTL1,TTL2,TTL3,TTL4,TTL5,TTL6
EDIFCfg3=Synopsys,.edf,SYNPRIMS
MACHPROCMD=""C:\MSim_8\wmachpro\wmachpro.exe""
ProductTermLimit=1024
[PLSyn BORDER]
width=608
height=303
zoomed=0
left=74
top=343
[MsgView]
left=192
top=424
width=600
height=312
toolbar=1
statusbar=1
senderclr=1
col0width=60
col1width=130
col2width=90
col3width=1000
Fontsize=-13
fontwidth=6
Fontweight=400
Fontname=MS Sans Serif
fontitalic=0
autosave=1
autoclose=1
[PLOGIC]
Font=-11 700 0 MS Sans Serif
xdisplay=502
[PLOGIC BORDER]
zoomed=1
[XILINX]
XC2000=XC2000
XC3000=XC3000;XBLOX
XC4000=XC4000;XBLOX
XC4000E=XC4000E;XBLOX
XC5200=XC5200;XBLOX
cmdline=""DSGNMGR.EXE""
[HELP]
PDFS="C:\MSim_8\DOC"
[PART LIBS]
LIB1=1_SHOT [.slb , .plb]
LIB2=7400 [.slb , .plb]
LIB3=74AC [.slb , .plb]
LIB4=74ACT [.slb , .plb]
LIB5=74ALS [.slb , .plb]
LIB6=74AS [.slb , .plb]
LIB7=74F [.slb , .plb]
LIB8=74H [.slb , .plb]
LIB9=74HC [.slb , .plb]
LIB10=74HCT [.slb , .plb]
LIB11=74L [.slb , .plb]
LIB12=74LS [.slb , .plb]
LIB13=74S [.slb , .plb]
LIB14=ABM [.slb]
LIB15=ADV_LIN [.slb , .plb]
LIB16=ANA_SWIT [.slb , .plb]
LIB17=ANALOG [.slb , .plb]
LIB18=ANL_MISC [.slb , .plb]
LIB19=ANLG [.slb , .plb]
LIB20=ANLG1 [.slb , .plb]
LIB21=ANLG2 [.slb , .plb]
LIB22=ANLG_DEV [.slb , .plb]
LIB23=APEX [.slb , .plb]
LIB24=BIPOLAR [.slb , .plb]
LIB25=BREAKOUT [.slb]
LIB26=BROKTREE [.slb , .plb]
LIB27=BURR_BRN [.slb , .plb]
LIB28=CD4000 [.slb , .plb]
LIB29=CHIPS [.slb , .plb]
LIB30=CMOS [.slb , .plb]
LIB31=COMLINR [.slb , .plb]
LIB32=CONNECT [.slb , .plb]
LIB33=DALLAS [.slb , .plb]
LIB34=DATACONV [.slb , .plb]
LIB35=DIG_ECL [.slb , .plb]
LIB36=DIG_GAL [.slb , .plb]
LIB37=DIG_MISC [.slb]
LIB38=DIG_PAL [.slb , .plb]
LIB39=DIG_PRIM [.slb]
LIB40=DIODE [.slb , .plb]
LIB41=EBIPOLAR [.slb , .plb]
LIB42=ECL [.slb , .plb]
LIB43=EDIODE [.slb , .plb]
LIB44=ELANTEC [.slb , .plb]
LIB45=EPWRBJT [.slb , .plb]
LIB46=EXEL [.slb , .plb]
LIB47=FILTSUB [.slb]
LIB48=FUJITSU [.slb , .plb]
LIB49=FWBELL [.slb]
LIB50=GOLDSTAR [.slb , .plb]
LIB51=HAR_DIG [.slb , .plb]
LIB52=HARRIS [.slb , .plb]
LIB53=HUGHES [.slb , .plb]
LIB54=HYUNDAI [.slb , .plb]
LIB55=IGBT [.slb , .plb]
LIB56=INTEL [.slb , .plb]
LIB57=JBIPOLAR [.slb , .plb]
LIB58=JDIODE [.slb , .plb]
LIB59=JFET [.slb , .plb]
LIB60=JJFET [.slb , .plb]
LIB61=JOPAMP [.slb , .plb]
LIB62=JPWRBJT [.slb , .plb]
LIB63=JPWRMOS [.slb , .plb]
LIB64=LIN_TECH [.slb , .plb]
LIB65=MAGNETIC [.slb]
LIB66=MAXIM [.slb , .plb]
LIB67=MCPWRSYS [.slb , .plb]
LIB68=MCRNDRAM [.slb , .plb]
LIB69=MCRNRAM2 [.slb , .plb]
LIB70=MCRNSRAM [.slb , .plb]
LIB71=MISC_SYM [.slb , .plb]
LIB72=MITMEM [.slb , .plb]
LIB73=MITRAM [.slb , .plb]
LIB74=MITROM [.slb , .plb]
LIB75=MIX_MISC [.slb , .plb]
LIB76=MOSEL [.slb , .plb]
LIB77=MOTO [.slb , .plb]
LIB78=MOTO7 [.slb , .plb]
LIB79=MOTOR_RF [.slb , .plb]
LIB80=MOTORAMP [.slb , .plb]
LIB81=MOTORMOS [.slb , .plb]
LIB82=MOTORSEN [.slb , .plb]
LIB83=NAT_SEMI [.slb , .plb]
LIB84=NSCLNAPP [.slb , .plb]
LIB85=NSDRAM [.slb , .plb]
LIB86=NSNETWK [.slb , .plb]
LIB87=NSUCONT [.slb , .plb]
LIB88=OKI [.slb , .plb]
LIB89=OPAMP [.slb , .plb]
LIB90=OPTO [.slb , .plb]
LIB91=PANSONC [.slb , .plb]
LIB92=PHIL_BJT [.slb , .plb]
LIB93=PHIL_FET [.slb , .plb]
LIB94=PHIL_RF [.slb , .plb]
LIB95=PLD_ALT [.slb , .plb]
LIB96=PLD_AMD [.slb , .plb]
LIB97=PLD_AMI [.slb , .plb]
LIB98=PLD_ATM [.slb , .plb]
LIB99=PLD_CYP [.slb , .plb]
LIB100=PLD_ICT [.slb , .plb]
LIB101=PLD_INT [.slb , .plb]
LIB102=PLD_LAT [.slb , .plb]
LIB103=PLD_MOT [.slb , .plb]
LIB104=PLD_NAT [.slb , .plb]
LIB105=PLD_PLX [.slb , .plb]
LIB106=PLD_PS [.slb , .plb]
LIB107=PLD_ST [.slb , .plb]
LIB108=PLD_TI [.slb , .plb]
LIB109=PLD_TOS [.slb , .plb]
LIB110=PLD_TQS [.slb , .plb]
LIB111=POLYFET [.slb , .plb]
LIB112=PORT [.slb]
LIB113=PWRBJT [.slb , .plb]
LIB114=PWRMOS [.slb , .plb]
LIB115=SEEQ [.slb , .plb]
LIB116=SGSTHOM [.slb , .plb]
LIB117=SIEMENS [.slb , .plb]
LIB118=SIPEX [.slb , .plb]
LIB119=SMOS [.slb , .plb]
LIB120=SONY [.slb , .plb]
LIB121=SOURCE [.slb]
LIB122=SOURCSTM [.slb]
LIB123=SPECIAL [.slb]
LIB124=SWIT_RAV [.slb]
LIB125=SWIT_REG [.slb , .plb]
LIB126=TEX_INST [.slb , .plb]
LIB127=THYRISTR [.slb , .plb]
LIB128=TI1 [.slb , .plb]
LIB129=TI2 [.slb , .plb]
LIB130=TILSI [.slb , .plb]
LIB131=TLINE [.slb]
LIB132=TTL [.slb , .plb]
LIB133=VLSITEC [.slb , .plb]
LIB134=WEITEK [.slb , .plb]
LIB135=WSI [.slb , .plb]
LIB136=XC2000P [.slb , .plb]
LIB137=XC3000P [.slb , .plb]
LIB138=XC4000EP [.slb , .plb]
LIB139=XC4000P [.slb , .plb]
LIB140=XC5200P [.slb , .plb]
LIB141=XICOR [.slb , .plb]
LIB142=XTAL [.slb]
LIB143=ZETEX [.slb , .plb]
LIB144=ZILOG [.slb , .plb]
LIB145=ATMEL [.slb , .plb]
LIB146=MEMORY [.slb , .plb]
[PSPICE]
b1_r=255
b1_g=255
b1_b=255
t1_r=0
t1_g=0
t1_b=0
b2_r=255
b2_g=255
b2_b=255
t2_r=255
t2_g=0
t2_b=0
Font=-11 700 0 MS Sans Serif
display=502
[PSPICE BORDER]
width=490
height=208
left=0
top=24
zoomed=1
