*version 7.1 71529044
@index
symloc 7400 0 112
symloc 7403 112 112
symloc 7401 224 112
symloc 7402 336 112
symloc 7404 448 117
symloc 7405 565 113
symloc 7406 678 117
symloc 7407 795 117
symloc 7408 912 112
symloc 7409 1024 112
symloc 7410 1136 114
symloc 7411 1250 114
symloc 7412 1364 114
symloc 7413 1478 111
symloc 7414 1589 112
symloc 7416 1701 112
symloc 7417 1813 112
symloc 7420 1925 111
symloc 7422 2036 111
symloc 7423 2147 168
symloc 7425 2315 120
symloc 7426 2435 112
symloc 7427 2547 114
symloc 7428 2661 112
symloc 7430 2773 120
symloc 7432 2893 112
symloc 7433 3005 112
symloc 7439 3117 112
symloc 7437 3229 112
symloc 7438 3341 117
symloc 7440 3458 111
symloc 7442A 3569 165
symloc 7443A 3734 165
symloc 7444A 3899 165
symloc 7445 4064 164
symloc 7446A 4228 200
symloc 7447A 4428 200
symloc 7448 4628 171
symloc 7449 4799 150
symloc 7450 4949 154
symloc 7451 5103 110
symloc 7453 5213 136
symloc 7454 5349 120
symloc 7460 5469 122
symloc 7470 5591 154
symloc 7472 5745 152
symloc 7473 5897 128
symloc 7474 6025 137
symloc 7475 6162 140
symloc 7476 6302 142
symloc 7477 6444 115
symloc 7480 6559 156
symloc 7482 6715 128
symloc 7483A 6843 177
symloc 7485 7020 183
symloc 7486 7203 112
symloc 7490A 7315 144
symloc 7491A 7459 107
symloc 7492A 7566 128
symloc 7493A 7694 128
symloc 7494 7822 188
symloc 7495A 8010 156
symloc 7496 8166 172
symloc 7497 8338 181
symloc 74100 8519 161
symloc 74104 8680 205
symloc 74105 8885 205
symloc 74107 9090 129
symloc 74109 9219 145
symloc 74110 9364 195
symloc 74111 9559 143
symloc 74116 9702 191
symloc 74120 9893 141
symloc 74125 10034 115
symloc 74126 10149 113
symloc 74128 10262 113
symloc 74132 10375 113
symloc 74136 10488 113
symloc 74141 10601 165
symloc 74143 10766 251
symloc 74144 11017 251
symloc 74145 11268 165
symloc 74147 11433 166
symloc 74148 11599 177
symloc 74150 11776 235
symloc 74151A 12011 171
symloc 74153 12182 181
symloc 74154 12363 239
symloc 74155 12602 181
symloc 74156 12783 181
symloc 74157 12964 184
symloc 74159 13148 239
symloc 74160 13387 176
symloc 74161 13563 176
symloc 74162 13739 243
symloc 74163 13982 176
symloc 74164 14158 155
symloc 74165 14313 175
symloc 74166 14488 176
symloc 74167 14664 179
symloc 74170 14843 173
symloc 74172 15016 269
symloc 74173 15285 173
symloc 74174 15458 173
symloc 74175 15631 181
symloc 74176 15812 160
symloc 74177 15972 160
symloc 74178 16132 166
symloc 74179 16298 187
symloc 74180 16485 165
symloc 74181 16650 261
symloc 74182 16911 193
symloc 74184 17104 172
symloc 74185A 17276 173
symloc 74190 17449 185
symloc 74191 17634 185
symloc 74192 17819 176
symloc 74193 17995 176
symloc 74194 18171 169
symloc 74195 18340 176
symloc 74196 18516 160
symloc 74197 18676 160
symloc 74198 18836 229
symloc 74199 19065 239
symloc 74246 19304 207
symloc 74247 19511 207
symloc 74248 19718 207
symloc 74249 19925 207
symloc 74251 20132 300
symloc 74259 20432 172
symloc 74265 20604 169
symloc 74273 20773 205
symloc 74276 20978 223
symloc 74278 21201 147
symloc 74279 21348 150
symloc 74283 21498 177
symloc 74290 21675 147
symloc 74293 21822 131
symloc 74298 21953 170
symloc 74351 22123 214
symloc 74365A 22337 174
symloc 74366A 22511 174
symloc 74367A 22685 186
symloc 74368A 22871 186
symloc 74376 23057 181
symloc 74390 23238 141
symloc 74393 23379 127
symloc 74425 23506 115
symloc 74426 23621 113
symloc 74490 23734 142
*package 7400
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7403
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7401
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 7402
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 7404
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14,SO14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7405
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14,
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7406
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14,SO14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7407
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14,SO14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7408
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7409
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7410
@types 3
g 1 A,B,C
@pinout
t DIP14
g 1
p A 1,3,9
p B 2,4,10
p C 13,5,11
p Y 12,6,8
s PWR 14
s GND 7
*package 7411
@types 3
g 1 A,B,C
@pinout
t DIP14
g 1
p A 1,3,9
p B 2,4,10
p C 13,5,11
p Y 12,6,8
s PWR 14
s GND 7
*package 7412
@types 3
g 1 A,B,C
@pinout
t DIP14
g 1
p A 1,3,9
p B 2,4,10
p C 13,5,11
p Y 12,6,8
s PWR 14
s GND 7
*package 7413
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,9
p B 2,10
p C 4,12
p D 5,13
p Y 6,8
s PWR 14
s GND 7
*package 7414
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7416
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7417
@types 6
g 1 A,B,C,D,E,F
@pinout
t DIP14
g 1
p A 1,3,5,9,11,13
p Y 2,4,6,8,10,12
s PWR 14
s GND 7
*package 7420
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,9
p B 2,10
p C 4,12
p D 5,13
p Y 6,8
s PWR 14
s GND 7
*package 7422
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,9
p B 2,10
p C 4,12
p D 5,13
p Y 6,8
s PWR 14
s GND 7
*package 7423
@types 1
g 1
@pinout
t DIP16
g 1
p 1A 2
p 1B 3
p 1C 5
p 1D 6
p 1G 4
p X 1
p \X\ 15
p 1Y 7
p 2A 10
p 2B 11
p 2C 13
p 2D 14
p 2G 12
p 2Y 9
p PWR 16
p GND 8
*package 7425
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,9
p B 2,10
p C 4,12
p D 5,13
p G 3,11
p Y 6,8
s PWR 14
s GND 7
*package 7426
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7427
@types 3
g 1 A,B,C
@pinout
t DIP14
g 1
p A 1,3,9
p B 2,4,10
p C 13,5,11
p Y 12,6,8
s PWR 14
s GND 7
*package 7428
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 7430
@types 1
g 1
@pinout
t DIP14
g 1
p A 1
p B 2
p C 3
p D 4
p E 5
p F 6
p G 11
p H 12
p Y 8
p PWR 14
p GND 7
*package 7432
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7433
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 7439
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 7437
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7438
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7440
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,9
p B 2,10
p C 4,12
p D 5,13
p Y 6,8
s PWR 14
s GND 7
*package 7442A
@types 1
g 1
@pinout
t DIP16
g 1
p A 15
p B 14
p C 13
p D 12
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 9
p Y8 10
p Y9 11
p PWR 16
p GND 8
*package 7443A
@types 1
g 1
@pinout
t DIP16
g 1
p A 15
p B 14
p C 13
p D 12
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 9
p Y8 10
p Y9 11
p PWR 16
p GND 8
*package 7444A
@types 1
g 1
@pinout
t DIP16
g 1
p A 15
p B 14
p C 13
p D 12
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 9
p Y8 10
p Y9 11
p PWR 16
p GND 8
*package 7445
@types 1
g 1
@pinout
t DIP16
g 1
p A 15
p B 14
p C 13
p D 12
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 9
p Y8 10
p Y9 11
p PWR 16
p GND 8
*package 7446A
@types 1
g 1
@pinout
t DIP16
g 1
p INA 7
p INB 1
p INC 2
p IND 6
p \RBI\ 5
p \LT\ 3
p \BI\/\RBO\ 4
p OUTA 13
p OUTB 12
p OUTC 11
p OUTD 10
p OUTE 9
p OUTF 15
p OUTG 14
p PWR 16
p GND 8
*package 7447A
@types 1
g 1
@pinout
t DIP16
g 1
p INA 7
p INB 1
p INC 2
p IND 6
p \RBI\ 5
p \LT\ 3
p \BI\/\RBO\ 4
p OUTA 13
p OUTB 12
p OUTC 11
p OUTD 10
p OUTE 9
p OUTF 15
p OUTG 14
p PWR 16
p GND 8
*package 7448
@types 1
g 1
@pinout
t DIP16
g 1
p A 7
p B 1
p C 2
p D 6
p \RBI\ 5
p \LT\ 3
p \BI\ 4
p OA 13
p OB 12
p OC 11
p OD 10
p OE 9
p OF 15
p OG 14
p PWR 16
p GND 8
*package 7449
@types 1
g 1
@pinout
t DIP14
g 1
p A 5
p B 1
p C 2
p D 4
p \BI\ 3
p OA 11
p OB 10
p OC 9
p OD 8
p OE 6
p OF 13
p OG 12
p PWR 14
p GND 7
*package 7450
@types 1
g 1
@pinout
t DIP14
g 1
p 1A 1
p 1B 13
p 1C 9
p 1D 10
p 1X 11
p 1\X\ 12
p 1Y 8
p 2A 2
p 2B 3
p 2C 4
p 2D 5
p 2Y 6
p PWR 14
p GND 7
*package 7451
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,2
p B 13,3
p C 9,4
p D 10,5
p Y 8,6
s PWR 14
s GND 7
*package 7453
@types 1
g 1
@pinout
t DIP14
g 1
p A 1
p B 13
p C 2
p D 3
p E 4
p F 5
p G 9
p H 10
p X 11
p \X\ 12
p Y 8
p PWR 14
p GND 7
*package 7454
@types 1
g 1
@pinout
t DIP14
g 1
p A 1
p B 13
p C 2
p D 3
p E 4
p F 5
p G 9
p H 10
p Y 8
p PWR 14
p GND 7
*package 7460
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,4
p B 2,5
p C 3,6
p D 13,8
p X 11,10
p \X\ 12,9
s PWR 14
s GND 7
*package 7470
@types 1
g 1
@pinout
t DIP14
g 1
p CLK 12
p \PRE\ 13
p \CLR\ 2
p J1 3
p J2 4
p \J\ 5
p K1 10
p K2 11
p \K\ 9
p Q 8
p \Q\ 6
p PWR 14
p GND 7
*package 7472
@types 1
g 1
@pinout
t DIP14
g 1
p \PRE\ 13
p \CLR\ 2
p CLK 12
p J1 3
p J2 4
p J3 5
p K1 9
p K2 10
p K3 11
p Q 8
p \Q\ 6
p PWR 14
p GND 7
*package 7473
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p CLK 1,5
p \CLR\ 2,6
p J 14,7
p K 3,10
p Q 12,9
p \Q\ 13,8
s PWR 4
s GND 11
*package 7474
@types 2
g 1 A,B
@pinout
t DIP14,SO14
g 1
p \CLR\ 1,13
p D 2,12
p CLK 3,11
p \PRE\ 4,10
p Q 5,9
p \Q\ 6,8
s PWR 14
s GND 7
*package 7475
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p 1D 2,6
p 2D 3,7
p C 13,4
p 1Q 16,10
p 1\Q\ 1,11
p 2Q 15,9
p 2\Q\ 14,8
s PWR 5
s GND 12
*package 7476
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p CLK 1,6
p \PRE\ 2,7
p \CLR\ 3,8
p J 4,9
p K 16,12
p Q 15,11
p \Q\ 14,10
s PWR 5
s GND 13
*package 7477
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p 1D 1,5
p 2D 2,6
p C 12,3
p 1Q 14,9
p 2Q 13,8
s PWR 4
s GND 11
*package 7480
@types 1
g 1
@pinout
t DIP14
g 1
p B* 1
p BC 2
p Cn 3
p \C\n+1 4
p S 5
p \S\ 6
p GND 7
p A1 8
p A2 9
p A* 10
p AC 11
p B1 12
p B2 13
p PWR 14
*package 7482
@types 1
g 1
@pinout
t DIP14
g 1
p C0 5
p A1 2
p B1 3
p A2 14
p B2 13
p SUM1 1
p SUM2 12
p C2 10
p PWR 4
p GND 11
*package 7483A
@types 1
g 1
@pinout
t DIP16
g 1
p C0 13
p A1 10
p A2 8
p A3 3
p A4 1
p B1 11
p B2 7
p B3 4
p B4 16
p C4 14
p SUM1 9
p SUM2 6
p SUM3 2
p SUM4 15
p PWR 5
p GND 12
*package 7485
@types 1
g 1
@pinout
t DIP16
g 1
p A3 15
p A2 13
p A1 12
p A0 10
p B3 1
p B2 14
p B1 11
p B0 9
p A>B_IN 4
p A=B_IN 3
p A<B_IN 2
p A>B 5
p A=B 6
p A<B 7
p PWR 16
p GND 8
*package 7486
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 7490A
@types 1
g 1
@pinout
t DIP14
g 1
p R91 6
p R92 7
p CKA 14
p CKB 1
p R01 2
p R02 3
p QA 12
p QB 9
p QC 8
p QD 11
p PWR 5
p GND 10
*package 7491A
@types 1
g 1
@pinout
t DIP14
g 1
p CLOCK 9
p A 12
p B 11
p QH 13
p \QH\ 14
p PWR 5
p GND 10
*package 7492A
@types 1
g 1
@pinout
t DIP14
g 1
p CKA 14
p CKB 1
p R01 6
p R02 7
p QA 12
p QB 11
p QC 9
p QD 8
p PWR 5
p GND 10
*package 7493A
@types 1
g 1
@pinout
t DIP14
g 1
p CKA 14
p CKB 1
p R01 2
p R02 3
p QA 12
p QB 9
p QC 8
p QD 11
p PWR 5
p GND 10
*package 7494
@types 1
g 1
@pinout
t DIP16
g 1
p CLEAR 10
p CLOCK 8
p SER_IN 7
p PE1 6
p P1A 1
p P1B 2
p P1C 3
p P1D 4
p PE2 15
p P2A 16
p P2B 14
p P2C 13
p P2D 11
p QD 9
p PWR 5
p GND 12
*package 7495A
@types 1
g 1
@pinout
t DIP14
g 1
p MODE 6
p CLK1 9
p CLK2 8
p SER 1
p A 2
p B 3
p C 4
p D 5
p QA 13
p QB 12
p QC 11
p QD 10
p PWR 14
p GND 7
*package 7496
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 1
p \CLR\ 16
p SERIAL 9
p PRE 8
p A 2
p B 3
p C 4
p D 6
p E 7
p QA 15
p QB 14
p QC 13
p QD 11
p QE 10
p PWR 5
p GND 12
*package 7497
@types 1
g 1
@pinout
t DIP16
g 1
p CLR 13
p STROBE 10
p CLK 9
p ENin 11
p B0 4
p B1 1
p B2 14
p B3 15
p B4 2
p B5 3
p UNICAS 12
p Y 6
p Z 5
p ENout 7
p PWR 16
p GND 8
*package 74100
@types 2
g 1 A,B
@pinout
t DIP24
g 1
p C 23,12
p D1 2,11
p D2 3,10
p D3 22,15
p D4 21,16
p Q1 5,8
p Q2 4,9
p Q3 19,18
p Q4 20,17
s PWR 24
s GND 7
*package 74104
@types 1
g 1
@attributes
@pinout
t DIP14
g 1
p CLK   9
p \PRE\ 2
p \CLR\ 13
p JK    1
p J1    4
p J2    5
p J3    12
p K1    3
p K2    10
p K3    11
p Q     6
p \Q\   8
p PWR   14
p GND   7
*package 74105
@types 1
g 1
@attributes
@pinout
t DIP14
g 1
p CLK   9
p \PRE\ 2
p \CLR\ 13
p JK    1
p J1    4
p \J2\  5
p J3    12
p K1    3
p \K2\  10
p K3    11
p Q     6
p \Q\   8
p PWR   14
p GND   7
*package 74107
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p CLK 12,9
p \CLR\ 13,10
p J 1,8
p K 4,11
p Q 3,5
p \Q\ 2,6
s PWR 14
s GND 7
*package 74109
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p CLK 4,12
p \PRE\ 5,11
p \CLR\ 1,15
p J 2,14
p \K\ 3,13
p Q 6,10
p \Q\ 7,9
s PWR 16
s GND 8
*package 74110
@types 1
g 1
@attributes
@pinout
t DIP14
g 1
p CLK   12
p \PRE\ 13
p \CLR\ 2
p J1    3
p J2    4
p J3    5
p K1    9
p K2    10
p K3    11
p Q     8
p \Q\   6
p PWR   14
p GND   7
*package 74111
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p CLK 5,11
p \PRE\ 2,14
p \CLR\ 3,13
p J 4,12
p K 1,15
p Q 7,9
p \Q\ 6,10
s PWR 16
s GND 8
*package 74116 b
@types 2
g 1 A,B
@pinout
t DIP24
g 1
p \CLR\ 1,13
p \C\1 2,14
p \C\2 3,15
p D1 4,16
p Q1 5,17
p D2 6,18
p Q2 7,19
p D3 8,20
p Q3 9,21
p D4 10,22
p Q4 11,23
s PWR 24
s GND 12
*package 74120
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p M 1,15
p \S\1 2,13
p \S\2 3,14
p \R\ 4,12
p C 5,11
p Y 6,10
p \Y\ 7,9
s PWR 16
s GND 8
*package 74125
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,9,12
p \G\ 1,4,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74126
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,9,12
p G 1,4,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74128
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 2,5,8,11
p B 3,6,9,12
p Y 1,4,10,13
s PWR 14
s GND 7
*package 74132
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74136
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p A 1,4,9,12
p B 2,5,10,13
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74141
@types 1
g 1
@pinout
t DIP16
g 1
p A 3
p B 6
p C 7
p D 4
p o0 16
p o1 15
p o2 8
p o3 9
p o4 13
p o5 14
p o6 11
p o7 10
p o8 1
p o9 2
p PWR 5
p GND 12
*package 74143
@types 1
g 1
@pinout
t DIP24
g 1
p \SCEI\ 1
p CLK 2
p \CLR\ 3
p \RBI\ 4
p BI 5
p \RBO\ 6
p DPO 7
p dpi 8
p d 9
p f 10
p e 11
p GND 12
p g 13
p c 14
p a 15
p b 16
p QA 17
p QB 18
p QC 19
p QD 20
p \STRB\ 21
p MAX 22
p \PCEI\ 23
p PWR 24
*package 74144
@types 1
g 1
@pinout
t DIP24
g 1
p \SCEI\ 1
p CLK 2
p \CLR\ 3
p \RBI\ 4
p BI 5
p \RBO\ 6
p DPO 7
p dpi 8
p d 9
p f 10
p e 11
p GND 12
p g 13
p c 14
p a 15
p b 16
p QA 17
p QB 18
p QC 19
p QD 20
p \STRB\ 21
p MAX 22
p \PCEI\ 23
p PWR 24
*package 74145
@types 1
g 1
@pinout
t DIP16
g 1
p A 15
p B 14
p C 13
p D 12
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 9
p Y8 10
p Y9 11
p PWR 16
p GND 8
*package 74147
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 11
p IN2 12
p IN3 13
p IN4 1
p IN5 2
p IN6 3
p IN7 4
p IN8 5
p IN9 10
p A 9
p B 7
p C 6
p D 14
p PWR 16
p GND 8
*package 74148
@types 1
g 1
@pinout
t DIP16
g 1
p IN0 10
p IN1 11
p IN2 12
p IN3 13
p IN4 1
p IN5 2
p IN6 3
p IN7 4
p EI 5
p A0 9
p A1 7
p A2 6
p GS 14
p EO 15
p PWR 16
p GND 8
*package 74150
@types 1
g 1
@pinout
t DIP24
g 1
p \G\ 9
p A 15
p B 14
p C 13
p D 11
p E0 8
p E1 7
p E2 6
p E3 5
p E4 4
p E5 3
p E6 2
p E7 1
p E8 23
p E9 22
p E10 21
p E11 20
p E12 19
p E13 18
p E14 17
p E15 16
p W 10
p PWR 24
p GND 12
*package 74151A
@types 1
g 1
@pinout
t DIP16
g 1
p \E\ 7
p S0 11
p S1 10
p S2 9
p I0 4
p I1 3
p I2 2
p I3 1
p I4 15
p I5 14
p I6 13
p I7 12
p Z 5
p \Z\ 6
p PWR 16
p GND 8
*package 74153
@types 1
g 1
@pinout
t DIP16
g 1
p \EA\ 1
p \EB\ 15
p S0 14
p S1 2
p I0A 6
p I1A 5
p I2A 4
p I3A 3
p I0B 10
p I1B 11
p I2B 12
p I3B 13
p ZA 7
p ZB 9
p PWR 16
p GND 8
*package 74154
@types 1
g 1
@pinout
t DIP24
g 1
p \G\1 18
p \G\2 19
p A 23
p B 22
p C 21
p D 20
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 8
p Y8 9
p Y9 10
p Y10 11
p Y11 13
p Y12 14
p Y13 15
p Y14 16
p Y15 17
p PWR 24
p GND 12
*package 74155
@types 1
g 1
@pinout
t DIP16
g 1
p 1\G\ 2
p 2\G\ 14
p A 13
p B 3
p 1C 1
p 2\C\ 15
p 1Y0 7
p 1Y1 6
p 1Y2 5
p 1Y3 4
p 2Y0 9
p 2Y1 10
p 2Y2 11
p 2Y3 12
p PWR 16
p GND 8
*package 74156
@types 1
g 1
@pinout
t DIP16
g 1
p 1Y0 7
p 1Y1 6
p 1Y2 5
p 1Y3 4
p 2Y0 9
p 2Y1 10
p 2Y2 11
p 2Y3 12
p 1\G\ 2
p 1C 1
p A 13
p B 3
p 2\G\ 14
p 2\C\ 15
p PWR 16
p GND 8
*package 74157
@types 1
g 1
@pinout
t DIP16
g 1
p STROBE\G\ 15
p 1A 2
p 1B 3
p 2A 5
p 2B 6
p 3A 11
p 3B 10
p 4A 14
p 4B 13
p SELECT\A\B 1
p 1Y 4
p 2Y 7
p 3Y 9
p 4Y 12
p PWR 16
p GND 8
*package 74159
@types 1
g 1
@pinout
t DIP24
g 1
p \G\1 18
p \G\2 19
p A 23
p B 22
p C 21
p D 20
p Y0 1
p Y1 2
p Y2 3
p Y3 4
p Y4 5
p Y5 6
p Y6 7
p Y7 8
p Y8 9
p Y9 10
p Y10 11
p Y11 13
p Y12 14
p Y13 15
p Y14 16
p Y15 17
p PWR 24
p GND 12
*package 74160
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 2
p ENP 7
p ENT 10
p \CLR\ 1
p \LOAD\ 9
p A 3
p B 4
p C 5
p D 6
p QA 14
p QB 13
p QC 12
p QD 11
p RCO 15
p PWR 16
p GND 8
*package 74161
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 2
p ENP 7
p ENT 10
p \CLR\ 1
p \LOAD\ 9
p A 3
p B 4
p C 5
p D 6
p QA 14
p QB 13
p QC 12
p QD 11
p RCO 15
p PWR 16
p GND 8
*package 74162
@types 1
g 1
@attributes
@pinout
t DIP16
g 1
p CLK    2
p ENP    7
p ENT    10
p \CLR\  1
p \LOAD\ 9
p A      3
p B      4
p C      5
p D      6
p QA     14
p QB     13
p QC     12
p QD     11
p RCO    15
p PWR    16
p GND    8
*package 74163
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 2
p ENP 7
p ENT 10
p \CLR\ 1
p \LOAD\ 9
p A 3
p B 4
p C 5
p D 6
p QA 14
p QB 13
p QC 12
p QD 11
p RCO 15
p PWR 16
p GND 8
*package 74164
@types 1
g 1
@pinout
t DIP14
g 1
p \CLR\ 9
p CLK 8
p A 1
p B 2
p QA 3
p QB 4
p QC 5
p QD 6
p QE 10
p QF 11
p QG 12
p QH 13
p PWR 14
p GND 7
*package 74165
@types 1
g 1
@pinout
t DIP16
g 1
p SH/\LD\ 1
p CLK_INH 15
p CLK 2
p SER 10
p A 11
p B 12
p C 13
p D 14
p E 3
p F 4
p G 5
p H 6
p QH 9
p \Q\H 7
p PWR 16
p GND 8
*package 74166
@types 1
g 1
@pinout
t DIP16
g 1
p \CLR\ 9
p SH/\LD\ 15
p CLK_INH 6
p CLK 7
p SER 1
p A 2
p B 3
p C 4
p D 5
p E 10
p F 11
p G 12
p H 14
p QH 13
p PWR 16
p GND 8
*package 74167
@types 1
g 1
@pinout
t DIP16
g 1
p CLR 13
p STROBE 10
p CLK 9
p EN_IN 11
p SET9 4
p B0 14
p B1 15
p B2 2
p B3 3
p UNICAS 12
p Y 6
p Z 5
p EN_OUT 7
p PWR 16
p GND 8
*package 74170
@types 1
g 1
@pinout
t DIP16
g 1
p \G\W 12
p WA 14
p WB 13
p \G\R 11
p RA 5
p RB 4
p D1 15
p D2 1
p D3 2
p D4 3
p Q1 10
p Q2 9
p Q3 7
p Q4 6
p PWR 16
p GND 8
*package 74172
@types 1
g 1
@pinout
t DIP24
g 1
p CLK 6
p 1\GW\ 3
p 1W0 2
p 1W1 1
p 1W2 23
p 1\GR\ 15
p 1R0 9
p 1R1 8
p 1R2 7
p 1DA 22
p 1DB 4
p 2\GW\ 20
p 2W/R0 17
p 2W/R1 18
p 2W/R2 19
p 2\GR\ 16
p 2DA 21
p 2DB 5
p 1QA 14
p 1QB 10
p 2QA 13
p 2QB 11
p PWR 24
p GND 12
*package 74173
@types 1
g 1
@pinout
t DIP16
g 1
p CLR 15
p CLK 7
p \G\1 9
p \G\2 10
p M 1
p N 2
p 1D 14
p 2D 13
p 3D 12
p 4D 11
p 1Q 3
p 2Q 4
p 3Q 5
p 4Q 6
p PWR 16
p GND 8
*package 74174
@types 1
g 1
@pinout
t DIP16
g 1
p \CLR\ 1
p CLK 9
p 1D 3
p 2D 4
p 3D 6
p 4D 11
p 5D 13
p 6D 14
p 1Q 2
p 2Q 5
p 3Q 7
p 4Q 10
p 5Q 12
p 6Q 15
p PWR 16
p GND 8
*package 74175
@types 1
g 1
@pinout
t DIP16
g 1
p \CLR\ 1
p CLK 9
p 1D 4
p 2D 5
p 3D 12
p 4D 13
p 1Q 2
p 2Q 7
p 3Q 10
p 4Q 15
p 1\Q\ 3
p 2\Q\ 6
p 3\Q\ 11
p 4\Q\ 14
p PWR 16
p GND 8
*package 74176
@types 1
g 1
@pinout
t DIP14
g 1
p \LOAD\ 1
p \CLR\ 13
p CLK1 8
p CLK2 6
p A 4
p B 10
p C 3
p D 11
p QA 5
p QB 9
p QC 2
p QD 12
p PWR 14
p GND 7
*package 74177
@types 1
g 1
@pinout
t DIP14
g 1
p \LOAD\ 1
p \CLR\ 13
p CLK1 8
p CLK2 6
p A 4
p B 10
p C 3
p D 11
p QA 5
p QB 9
p QC 2
p QD 12
p PWR 14
p GND 7
*package 74178
@types 1
g 1
@pinout
t DIP14,CDIP14
g 1
p SERIAL 3
p CLK 5
p LOAD 9
p SHIFT 11
p A 2
p B 1
p C 13
p D 12
p QA 4
p QB 6
p QC 8
p QD 10
p PWR 14
p GND 7
*package 74179
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p \CLR\ 1
p CLK 6
p SERIAL 4
p LOAD 10
p SHIFT 13
p A 3
p B 2
p C 15
p D 14
p QA 5
p QB 7
p QC 9
p QD 11
p \Q\D 12
p PWR 16
p GND 8
*package 74180
@types 1
g 1
@pinout
t DIP14
g 1
p A 8
p B 9
p C 10
p D 11
p E 12
p F 13
p G 1
p H 2
p EVEN_IN 3
p ODD_IN 4
p EVEN_OUT 5
p ODD_OUT 6
p PWR 14
p GND 7
*package 74181
@types 1
g 1
@pinout
t DIP24
g 1
p \A\0 2
p \A\1 23
p \A\2 21
p \A\3 19
p \B\0 1
p \B\1 22
p \B\2 20
p \B\3 18
p S0 6
p S1 5
p S2 4
p S3 3
p M 8
p CN 7
p \F\0 9
p \F\1 10
p \F\2 11
p \F\3 13
p A=B 14
p \P\ 15
p \G\ 17
p CN+4 16
p PWR 24
p GND 12
*package 74182
@types 1
g 1
@pinout
t DIP16
g 1
p \G\3 5
p \G\2 14
p \G\1 1
p \G\0 3
p \P\3 6
p \P\2 15
p \P\1 2
p \P\0 4
p CN 13
p \G\ 10
p \P\ 7
p CN+X 12
p CN+Y 11
p CN+Z 9
p PWR 16
p GND 8
*package 74184
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p Y1 1
p Y2 2
p Y3 3
p Y4 4
p Y5 5
p Y6 6
p Y7 7
p Y8 9
p A 10
p B 11
p C 12
p D 13
p E 14
p \G\ 15
p PWR 16
p GND 8
*package 74185A
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p Y1 1
p Y2 2
p Y3 3
p Y4 4
p Y5 5
p Y6 6
p Y7 7
p Y8 9
p A 10
p B 11
p C 12
p D 13
p E 14
p \G\ 15
p PWR 16
p GND 8
*package 74190
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 14
p D/\U\ 5
p \CTEN\ 4
p \LOAD\ 11
p A 15
p B 1
p C 10
p D 9
p \RCO\ 13
p MAX/MIN 12
p QA 3
p QB 2
p QC 6
p QD 7
p PWR 16
p GND 8
*package 74191
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 14
p D/\U\ 5
p \CTEN\ 4
p \LOAD\ 11
p A 15
p B 1
p C 10
p D 9
p \RCO\ 13
p MAX/MIN 12
p QA 3
p QB 2
p QC 6
p QD 7
p PWR 16
p GND 8
*package 74192
@types 1
g 1
@pinout
t DIP16
g 1
p UP 5
p DOWN 4
p CLR 14
p \LOAD\ 11
p A 15
p B 1
p C 10
p D 9
p QA 3
p QB 2
p QC 6
p QD 7
p \BO\ 13
p \CO\ 12
p PWR 16
p GND 8
*package 74193
@types 1
g 1
@pinout
t DIP16
g 1
p UP 5
p DOWN 4
p CLR 14
p \LOAD\ 11
p A 15
p B 1
p C 10
p D 9
p QA 3
p QB 2
p QC 6
p QD 7
p \BO\ 13
p \CO\ 12
p PWR 16
p GND 8
*package 74194
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 11
p \CLR\ 1
p S1 10
p S0 9
p SL 7
p SR 2
p A 3
p B 4
p C 5
p D 6
p QA 15
p QB 14
p QC 13
p QD 12
p PWR 16
p GND 8
*package 74195
@types 1
g 1
@pinout
t DIP16
g 1
p CLK 10
p SH/\LD\ 9
p \CLR\ 1
p J 2
p \K\ 3
p A 4
p B 5
p C 6
p D 7
p QA 15
p QB 14
p QC 13
p QD 12
p \Q\D 11
p PWR 16
p GND 8
*package 74196
@types 1
g 1
@pinout
t DIP14
g 1
p \LOAD\ 1
p \CLR\ 13
p CLK1 8
p CLK2 6
p A 4
p B 10
p C 3
p D 11
p QA 5
p QB 9
p QC 2
p QD 12
p PWR 14
p GND 7
*package 74197
@types 1
g 1
@pinout
t DIP14
g 1
p \LOAD\ 1
p \CLR\ 13
p CLK1 8
p CLK2 6
p A 4
p B 10
p C 3
p D 11
p QA 5
p QB 9
p QC 2
p QD 12
p PWR 14
p GND 7
*package 74198
@types 1
g 1
@pinout
t DIP24
g 1
p CLK 11
p \CLR\ 13
p S0 1
p S1 23
p SR 2
p SL 22
p A 3
p B 5
p C 7
p D 9
p E 15
p F 17
p G 19
p H 21
p QA 4
p QB 6
p QC 8
p QD 10
p QE 14
p QF 16
p QG 18
p QH 20
p PWR 24
p GND 12
*package 74199
@types 1
g 1
@pinout
t DIP24
g 1
p CLK 13
p CLK_INH 11
p SH/\LD\ 23
p \CLR\ 14
p J 2
p \K\ 1
p A 3
p B 5
p C 7
p D 9
p E 16
p F 18
p G 20
p H 22
p QA 4
p QB 6
p QC 8
p QD 10
p QE 15
p QF 17
p QG 19
p QH 21
p PWR 24
p GND 12
*package 74246
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p INB 1
p INC 2
p \LT\ 3
p \BI\/\RBO\ 4
p \RBI\ 5
p IND 6
p INA 7
p OUTE 9
p OUTD 10
p OUTC 11
p OUTB 12
p OUTA 13
p OUTG 14
p OUTF 15
p PWR 16
p GND 8
*package 74247
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p INB 1
p INC 2
p \LT\ 3
p \BI\/\RBO\ 4
p \RBI\ 5
p IND 6
p INA 7
p OUTE 9
p OUTD 10
p OUTC 11
p OUTB 12
p OUTA 13
p OUTG 14
p OUTF 15
p PWR 16
p GND 8
*package 74248
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p INB 1
p INC 2
p \LT\ 3
p \BI\/\RBO\ 4
p \RBI\ 5
p IND 6
p INA 7
p OUTE 9
p OUTD 10
p OUTC 11
p OUTB 12
p OUTA 13
p OUTG 14
p OUTF 15
p PWR 16
p GND 8
*package 74249
@types 1
g 1
@pinout
t DIP16,CDIP16
g 1
p INB 1
p INC 2
p \LT\ 3
p \BI\/\RBO\ 4
p \RBI\ 5
p IND 6
p INA 7
p OUTE 9
p OUTD 10
p OUTC 11
p OUTB 12
p OUTA 13
p OUTG 14
p OUTF 15
p PWR 16
p GND 8
*package 74251
@types 1
g 1
@pinout
t DIP16
g 1
p \G\ 7
p A 11
p B 10
p C 9
p D0 4
p D1 3
p D2 2
p D3 1
p D4 15
p D5 14
p D6 13
p D7 12
p Y 5
p \W\ 6
p PWR 16
p GND 8
t LCC20
g 1
p \G\ 9
p A 14
p B 13
p C 12
p D0 5
p D1 4
p D2 3
p D3 2
p D4 19
p D5 18
p D6 17
p D7 15
p Y 7
p \W\ 8
p PWR 20
p GND 10
*package 74259
@types 1
g 1
@pinout
t DIP16
g 1
p \CLR\ 15
p \G\ 14
p D 13
p S0 1
p S1 2
p S2 3
p Q0 4
p Q1 5
p Q2 6
p Q3 7
p Q4 9
p Q5 10
p Q6 11
p Q7 12
p PWR 16
p GND 8
*package 74265
@types 1
g 1
@pinout
t DIP16
g 1
p 1A 1
p 1W 2
p 1Y 3
p 2A 4
p 2B 5
p 2W 6
p 2Y 7
p 3A 11
p 3B 12
p 3W 10
p 3Y 9
p 4A 15
p 4W 14
p 4Y 13
p PWR 16
p GND 8
*package 74273
@types 1
g 1
@pinout
t DIP20
g 1
p \CLR\ 1
p CLK 11
p D1 3
p D2 4
p D3 7
p D4 8
p D5 13
p D6 14
p D7 17
p D8 18
p Q1 2
p Q2 5
p Q3 6
p Q4 9
p Q5 12
p Q6 15
p Q7 16
p Q8 19
p PWR 20
p GND 10
*package 74276
@types 1
g 1
@pinout
t DIP20
g 1
p \PRE\ 11
p \CLR\ 1
p 1CLK 3
p 2CLK 8
p 3CLK 13
p 4CLK 18
p 1J 2
p 2J 9
p 3J 12
p 4J 19
p 1\K\ 4
p 2\K\ 7
p 3\K\ 14
p 4\K\ 17
p 1Q 5
p 2Q 6
p 3Q 15
p 4Q 16
p PWR 20
p GND 10
*package 74278
@types 1
g 1
@pinout
t DIP14
g 1
p P0 4
p STRB 1
p D1 12
p D2 13
p D3 2
p D4 3
p Y1 10
p Y2 9
p Y3 8
p Y4 6
p P1 5
p PWR 14
p GND 7
*package 74279
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p 1\R\ 1,10
p 1\S\1 2,11
p 1\S\2 3,12
p 2\R\ 5,14
p 2\S\ 6,15
p 1Q 4,9
p 2Q 7,13
s PWR 16
s GND 8
*package 74283
@types 1
g 1
@pinout
t DIP16
g 1
p C0 7
p A1 5
p A2 3
p A3 14
p A4 12
p B1 6
p B2 2
p B3 15
p B4 11
p C4 9
p SUM1 4
p SUM2 1
p SUM3 13
p SUM4 10
p PWR 16
p GND 8
*package 74290
@types 1
g 1
@pinout
t DIP14
g 1
p R91 1
p R92 3
p CLKA 10
p CLKB 11
p R01 12
p R02 13
p QA 9
p QB 5
p QC 4
p QD 8
p PWR 14
p GND 7
*package 74293
@types 1
g 1
@pinout
t DIP14
g 1
p CLKA 10
p CLKB 11
p R01 12
p R02 13
p QA 9
p QB 5
p QC 4
p QD 8
p PWR 14
p GND 7
*package 74298
@types 1
g 1
@pinout
t DIP16
g 1
p WS 10
p CLK 11
p A1 3
p A2 2
p B1 4
p B2 1
p C1 9
p C2 5
p D1 7
p D2 6
p QA 15
p QB 14
p QC 13
p QD 12
p PWR 16
p GND 8
*package 74351
@types 1
g 1
@pinout
t DIP20,CDIP20
g 1
p D7 11
p 1Y 1
p A 3
p 1D2 8
p D5 13
p 2D0 18
p \G\ 2
p 1D3 9
p D6 12
p 2Y 19
p B 4
p 1D1 7
p D4 14
p 2D1 17
p C 5
p 1D0 6
p 2D3 15
p 2D2 16
p PWR 20
p GND 10
*package 74365A
@types 1
g 1
@pinout
t DIP16
g 1
p A1 2
p A2 4
p A3 6
p A4 10
p A5 12
p A6 14
p \G\1 1
p \G\2 15
p Y1 3
p Y2 5
p Y3 7
p Y4 9
p Y5 11
p Y6 13
p PWR 16
p GND 8
*package 74366A
@types 1
g 1
@pinout
t DIP16
g 1
p A1 2
p A2 4
p A3 6
p A4 10
p A5 12
p A6 14
p \G\1 1
p \G\2 15
p Y1 3
p Y2 5
p Y3 7
p Y4 9
p Y5 11
p Y6 13
p PWR 16
p GND 8
*package 74367A
@types 1
g 1
@pinout
t DIP16
g 1
p 1A1 2
p 1A2 4
p 1A3 6
p 1A4 10
p 2A1 12
p 2A2 14
p 1\G\ 1
p 2\G\ 15
p 1Y1 3
p 1Y2 5
p 1Y3 7
p 1Y4 9
p 2Y1 11
p 2Y2 13
p PWR 16
p GND 8
*package 74368A
@types 1
g 1
@pinout
t DIP16
g 1
p 1A1 2
p 1A2 4
p 1A3 6
p 1A4 10
p 2A1 12
p 2A2 14
p 1\G\ 1
p 2\G\ 15
p 1Y1 3
p 1Y2 5
p 1Y3 7
p 1Y4 9
p 2Y1 11
p 2Y2 13
p PWR 16
p GND 8
*package 74376
@types 1
g 1
@pinout
t DIP16
g 1
p \CLR\ 1
p CLK 9
p 1J 2
p 2J 7
p 3J 10
p 4J 15
p 1\K\ 3
p 2\K\ 6
p 3\K\ 11
p 4\K\ 14
p 1Q 4
p 2Q 5
p 3Q 12
p 4Q 13
p PWR 16
p GND 8
*package 74390
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p CKA 1,15
p CKB 4,12
p CLR 2,14
p QA 3,13
p QB 5,11
p QC 6,10
p QD 7,9
s PWR 16
s GND 8
*package 74393
@types 2
g 1 A,B
@pinout
t DIP14
g 1
p A 1,13
p CLR 2,12
p QA 3,11
p QB 4,10
p QC 5,9
p QD 6,8
s PWR 14
s GND 7
*package 74425
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p \G\ 1,4,10,13
p A 2,5,9,12
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74426
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p G 1,4,10,13
p A 2,5,9,12
p Y 3,6,8,11
s PWR 14
s GND 7
*package 74490
@types 2
g 1 A,B
@pinout
t DIP16
g 1
p CLR 2,14
p SET9 4,12
p CLK 1,15
p QA 3,13
p QB 5,11
p QC 6,10
p QD 7,9
s PWR 16
s GND 8
