*version 7.2 629068554
@index
symloc AD581J/AD 0 75
symloc AD581K/AD 75 75
symloc AD581/AD 150 74
symloc AD581L/AD 224 75
symloc AD581S/AD 299 75
symloc AD581T/AD 374 75
symloc AD581U/AD 449 75
symloc AD584/AD 524 125
symloc AD584J/AD 649 126
symloc AD584K/AD 775 126
symloc AD584L/AD 901 126
symloc AD584S/AD 1027 126
symloc AD584T/AD 1153 126
symloc AD587/AD 1279 97
symloc AD587J/AD 1376 196
symloc AD587K/AD 1572 92
symloc AD587L/AD 1664 145
symloc AD587S/AD 1809 93
symloc AD587T/AD 1902 93
symloc AD587U/AD 1995 93
symloc AD588 2088 432
symloc AD600/AD 2520 252
symloc AD600J/AD 2772 253
symloc AD602/AD 3025 149
symloc AD602J/AD 3174 253
symloc AD603/AD 3427 187
symloc AD603A/AD 3614 188
symloc AD620/AD 3802 118
symloc AD620A/AD 3920 125
symloc AD620B/AD 4045 125
symloc AD620S/AD 4170 178
symloc AD624/AD 4348 186
symloc AD624A/AD 4534 187
symloc AD624B/AD 4721 187
symloc AD624C/AD 4908 187
symloc AD624S/AD 5095 187
symloc AD630/AD 5282 247
symloc AD630A/AD 5529 236
symloc AD630B/AD 5765 236
symloc AD630J/AD 6001 247
symloc AD630K/AD 6248 235
symloc AD630S/AD 6483 242
symloc AD633/AD 6725 108
symloc AD633J/AD 6833 109
symloc AD645/AD 6942 104
symloc AD645A/AD 7046 159
symloc AD645B/AD 7205 159
symloc AD645J/AD 7364 159
symloc AD645K/AD 7523 159
symloc AD645S/AD 7682 159
symloc AD680 7841 85
symloc AD680JT 7926 75
symloc AD704/AD 8001 265
symloc AD704A/AD 8266 194
symloc AD704B/AD 8460 118
symloc AD704J/AD 8578 187
symloc AD704K/AD 8765 129
symloc AD704T/AD 8894 118
symloc AD705/AD 9012 114
symloc AD705A/AD 9126 106
symloc AD705B/AD 9232 106
symloc AD705J/AD 9338 109
symloc AD705K/AD 9447 117
symloc AD705T/AD 9564 106
symloc AD706/AD 9670 104
symloc AD706A/AD 9774 100
symloc AD706B/AD 9874 96
symloc AD706J/AD 9970 99
symloc AD706K/AD 10069 95
symloc AD706T/AD 10164 96
symloc AD711/AD 10260 114
symloc AD711A/AD 10374 106
symloc AD711B/AD 10480 106
symloc AD711C/AD 10586 106
symloc AD711J/AD 10692 103
symloc AD711K/AD 10795 103
symloc AD711S/AD 10898 106
symloc AD711T/AD 11004 106
symloc AD712/AD 11110 110
symloc AD712A/AD 11220 102
symloc AD712B/AD 11322 102
symloc AD712C/AD 11424 102
symloc AD712J/AD 11526 99
symloc AD712K/AD 11625 99
symloc AD712S/AD 11724 102
symloc AD712T/AD 11826 102
symloc AD713/AD 11928 193
symloc AD713A/AD 12121 118
symloc AD713B/AD 12239 118
symloc AD713J/AD 12357 187
symloc AD713K/AD 12544 117
symloc AD713S/AD 12661 118
symloc AD713T/AD 12779 118
symloc AD734/AD 12897 160
symloc AD734A/AD 13057 161
symloc AD734B/AD 13218 161
symloc AD734S/AD 13379 155
symloc AD743/AD 13534 166
symloc AD743A/AD 13700 167
symloc AD743B/AD 13867 100
symloc AD743J/AD 13967 161
symloc AD743K/AD 14128 161
symloc AD743S/AD 14289 100
symloc AD744/AD 14389 120
symloc AD744A/AD 14509 112
symloc AD744B/AD 14621 112
symloc AD744C/AD 14733 112
symloc AD744J/AD 14845 109
symloc AD744K/AD 14954 109
symloc AD744S/AD 15063 112
symloc AD744T/AD 15175 112
symloc AD745/AD 15287 166
symloc AD745A/AD 15453 221
symloc AD745B/AD 15674 100
symloc AD745J/AD 15774 161
symloc AD745K/AD 15935 99
symloc AD745S/AD 16034 100
symloc AD746/AD 16134 104
symloc AD746A/AD 16238 96
symloc AD746B/AD 16334 96
symloc AD746J/AD 16430 99
symloc AD746S/AD 16529 96
symloc AD780/AD 16625 111
symloc AD780A/AD 16736 106
symloc AD780B/AD 16842 106
symloc AD780S/AD 16948 103
symloc AD795/AD 17051 130
symloc AD795J/AD 17181 131
symloc AD795K/AD 17312 131
symloc AD797/AD 17443 117
symloc AD797A/AD 17560 112
symloc AD797B/AD 17672 108
symloc AD797S/AD 17780 109
symloc AD811/AD 17889 238
symloc AD810/AD 18127 106
symloc AD810A/AD 18233 101
symloc AD810S/AD 18334 98
symloc AD812/AD 18432 98
symloc AD812A/AD 18530 99
symloc AD813/AD 18629 129
symloc AD813A/AD 18758 130
symloc AD817/AD 18888 88
symloc AD817A/AD 18976 89
symloc AD818/AD 19065 88
symloc AD818A/AD 19153 89
symloc AD820/AD 19242 94
symloc AD824/AD 19336 192
symloc AD824A/AD:AD824/AD 19528 32
symloc AD824B/AD:AD824/AD 19560 32
symloc AD826/AD 19592 98
symloc AD826A/AD 19690 99
symloc AD828/AD 19789 98
symloc AD828A/AD 19887 99
symloc AD829/AD 19986 114
symloc AD829A/AD 20100 106
symloc AD829J/AD 20206 109
symloc AD829S/AD 20315 106
symloc AD830/AD 20421 110
symloc AD830A/AD 20531 101
symloc AD830J/AD 20632 100
symloc AD830S/AD 20732 102
symloc AD840/AD 20834 173
symloc AD-840/AD 21007 174
symloc AD840J/AD 21181 110
symloc AD-840J/AD 21291 111
symloc AD840K/AD 21402 110
symloc AD-840K/AD 21512 111
symloc AD840S/AD 21623 168
symloc AD-840S/AD 21791 175
symloc AD843/AD 21966 292
symloc AD843A/AD 22258 100
symloc AD843B/AD 22358 162
symloc AD843J/AD 22520 161
symloc AD843K/AD 22681 99
symloc AD843S/AD 22780 226
symloc AD844/AD 23006 179
symloc AD844A/AD 23185 111
symloc AD844B/AD 23296 106
symloc AD844S/AD 23402 106
symloc AD845/AD 23508 166
symloc AD-845/AD 23674 167
symloc AD845A/AD 23841 100
symloc AD-845A/AD 23941 101
symloc AD845B/AD 24042 100
symloc AD-845B/AD 24142 101
symloc AD845J/AD 24243 161
symloc AD-845J/AD 24404 162
symloc AD845K/AD 24566 99
symloc AD-845K/AD 24665 100
symloc AD845S/AD 24765 100
symloc AD-845S/AD 24865 101
symloc AD846/AD 24966 96
symloc AD846A/AD 25062 97
symloc AD846B/AD 25159 97
symloc AD846S/AD 25256 92
symloc AD847/AD 25348 108
symloc AD847A/AD 25456 104
symloc AD847J/AD 25560 103
symloc AD847S/AD 25663 100
symloc AD848/AD 25763 108
symloc AD848A/AD 25871 100
symloc AD848J/AD 25971 103
symloc AD848S/AD 26074 100
symloc AD8001A/AD 26174 130
symloc AD8001AN/AD 26304 87
symloc AD8001AR/AD 26391 86
symloc AD9617/AD 26477 111
symloc AD9618/AD 26588 111
symloc AD9621/AD 26699 109
symloc AD9622/AD 26808 109
symloc AD9623/AD 26917 109
symloc AD9624/AD 27026 109
symloc AD9630/AD 27135 94
symloc ADG411/AD 27229 190
symloc ADG411B/AD 27419 184
symloc ADG411T/AD 27603 180
symloc ADG412/AD 27783 190
symloc ADG412B/AD 27973 184
symloc ADG412T/AD 28157 180
symloc ADG413/AD 28337 183
symloc ADG413B/AD 28520 184
symloc ADG413T/AD 28704 180
symloc AMP-01/AD 28884 522
symloc AMP-02/AD 29406 182
symloc AMP-04 29588 110
symloc BUF04/AD 29698 88
symloc MAT-02/AD 29786 168
symloc MAT-03/AD 29954 152
symloc MAT-04/AD 30106 171
symloc MLT04/AD 30277 138
symloc MLT04G/AD 30415 139
symloc OP-08 30554 107
symloc OP-20/AD 30661 114
symloc OP-20B/AD 30775 106
symloc OP-20C/AD 30881 100
symloc OP-20F/AD 30981 111
symloc OP-20G/AD 31092 111
symloc OP-20H/AD 31203 115
symloc OP-21/AD 31318 114
symloc OP-21A/AD 31432 106
symloc OP-21E/AD 31538 100
symloc OP-21F/AD 31638 111
symloc OP-21G/AD 31749 105
symloc OP-21H/AD 31854 103
symloc OP-27/AD 31957 178
symloc OP-27A/AD 32135 106
symloc OP-27B/AD 32241 170
symloc OP-27C/AD 32411 106
symloc OP-27E/AD 32517 111
symloc OP-27F/AD 32628 111
symloc OP-27G/AD 32739 115
symloc OP-37/AD 32854 178
symloc OP-37A/AD 33032 106
symloc OP-37B/AD 33138 170
symloc OP-37C/AD 33308 106
symloc OP-37E/AD 33414 111
symloc OP-37F/AD 33525 111
symloc OP-37G/AD 33636 115
symloc OP-41/AD 33751 108
symloc OP-41A/AD 33859 100
symloc OP-41B/AD 33959 100
symloc OP-41E/AD 34059 100
symloc OP-41F/AD 34159 100
symloc OP-41G/AD 34259 103
symloc OP-42/AD 34362 178
symloc OP-42A/AD 34540 170
symloc OP-42E/AD 34710 106
symloc OP-42F/AD 34816 106
symloc OP-42G/AD 34922 103
symloc OP-43/AD 35025 104
symloc OP-43A/AD 35129 100
symloc OP-43B/AD 35229 100
symloc OP-43E/AD 35329 100
symloc OP-43F/AD 35429 100
symloc OP-43G/AD 35529 99
symloc OP-44/AD 35628 178
symloc OP-61/AD 35806 172
symloc OP-64/AD 35978 199
symloc OP-77/AD 36177 178
symloc OP-77A/AD 36355 106
symloc OP-77B/AD 36461 170
symloc OP-77E/AD 36631 111
symloc OP-77F/AD 36742 111
symloc OP-77G/AD 36853 103
symloc OP-80/AD 36956 94
symloc OP-80B/AD 37050 86
symloc OP-80E/AD 37136 86
symloc OP-80F/AD 37222 86
symloc OP-80G/AD 37308 89
symloc OP-90/AD 37397 172
symloc OP-90A/AD 37569 164
symloc OP-90E/AD 37733 100
symloc OP-90F/AD 37833 100
symloc OP-90G/AD 37933 103
symloc OP-97/AD 38036 122
symloc OP-97A/AD 38158 114
symloc OP-97E/AD 38272 119
symloc OP-97F/AD 38391 123
symloc OP-113 38514 100
symloc OP-160/AD 38614 193
symloc OP-160A/AD 38807 185
symloc OP-160F/AD 38992 111
symloc OP-160G/AD 39103 114
symloc OP-176/AD 39217 89
symloc OP-176G/AD 39306 90
symloc OP-177/AD 39396 173
symloc OP-177A/AD 39569 101
symloc OP-177B/AD 39670 165
symloc OP-177E/AD 39835 101
symloc OP-177F/AD 39936 106
symloc OP-177G/AD 40042 110
symloc OP-183 40152 100
symloc OP-200/AD 40252 212
symloc OP-200A/AD 40464 154
symloc OP-200E/AD 40618 97
symloc OP-200F/AD 40715 97
symloc OP-200G/AD 40812 150
symloc OP-213 40962 102
symloc OP-295/AD 41064 99
symloc OP-215/AD 41163 213
symloc OP-215A/AD 41376 103
symloc OP-215B/AD 41479 159
symloc OP-215C/AD 41638 103
symloc OP-215E/AD 41741 108
symloc OP-215F/AD 41849 108
symloc OP-215G/AD 41957 152
symloc OP-220/AD 42109 157
symloc OP-220A/AD 42266 103
symloc OP-220C/AD 42369 103
symloc OP-220E/AD 42472 97
symloc OP-220F/AD 42569 97
symloc OP-220G/AD 42666 158
symloc OP-221/AD 42824 157
symloc OP-221A/AD 42981 103
symloc OP-221B/AD 43084 97
symloc OP-221C/AD 43181 97
symloc OP-221E/AD 43278 97
symloc OP-221G/AD 43375 158
symloc OP-249/AD 43533 214
symloc OP-249A/AD 43747 160
symloc OP-249E/AD 43907 97
symloc OP-249F/AD 44004 103
symloc OP-249G/AD 44107 146
symloc OP-260/AD 44253 218
symloc OP-275/AD 44471 99
symloc OP-275G/AD 44570 100
symloc OP-282/AD 44670 99
symloc OP-282G/AD 44769 100
symloc OP-283 44869 96
symloc OP-283/AD 44965 99
symloc OP-285/AD 45064 99
symloc OP-285G/AD 45163 112
symloc OP-290/AD 45275 212
symloc OP-290A/AD 45487 154
symloc OP-290E/AD 45641 97
symloc OP-290F/AD 45738 97
symloc OP-290G/AD 45835 150
symloc OP-291 45985 96
symloc OP-292/AD 46081 111
symloc OP-297/AD 46192 162
symloc OP-297A/AD 46354 154
symloc OP-297E/AD 46508 97
symloc OP-297F/AD 46605 102
symloc OP-297G/AD 46707 100
symloc OP-400/AD 46807 268
symloc OP-400A/AD 47075 193
symloc OP-400E/AD 47268 119
symloc OP-400F/AD 47387 119
symloc OP-400G/AD 47506 188
symloc OP-400H/AD 47694 188
symloc OP-413 47882 185
symloc OP-420/AD 48067 266
symloc OP-420B/AD 48333 119
symloc OP-420C/AD 48452 191
symloc OP-420F/AD 48643 119
symloc OP-420G/AD 48762 195
symloc OP-420H/AD 48957 195
symloc OP-421/AD 49152 194
symloc OP-421B/AD 49346 119
symloc OP-421C/AD 49465 119
symloc OP-421F/AD 49584 119
symloc OP-421G/AD 49703 195
symloc OP-421H/AD 49898 195
symloc OP-467/AD 50093 266
symloc OP-467G/AD 50359 188
symloc OP-470/AD 50547 340
symloc OP-482/AD 50887 194
symloc OP-482G/AD 51081 123
symloc OP-490/AD 51204 268
symloc OP-490A/AD 51472 193
symloc OP-490E/AD 51665 119
symloc OP-490F/AD 51784 119
symloc OP-490G/AD 51903 188
symloc OP-491 52091 119
symloc OP-492/AD 52210 122
symloc OP-497/AD 52332 266
symloc OP-497A/AD 52598 119
symloc OP-497B/AD 52717 191
symloc OP-497C/AD 52908 119
symloc OP-497F/AD 53027 195
symloc OP-497G/AD 53222 195
symloc OP191/AD 53417 88
symloc OP191G/AD 53505 89
symloc OP279/AD 53594 98
symloc OP279G/AD 53692 99
symloc OP284/AD 53791 90
symloc OP284E/AD 53881 91
symloc OP284F/AD 53972 91
symloc PM-1012/AD 54063 124
symloc REF-01/AD 54187 141
symloc REF01/AD 54328 149
symloc REF-01A/AD 54477 93
symloc REF01A/AD 54570 90
symloc REF-01C/AD 54660 102
symloc REF01C/AD 54762 96
symloc REF-01E/AD 54858 93
symloc REF01E/AD 54951 96
symloc REF-01H/AD 55047 98
symloc REF01H/AD 55145 96
symloc REF-02/AD 55241 164
symloc REF02/AD 55405 167
symloc REF-02A/AD 55572 102
symloc REF02A/AD 55674 100
symloc REF-02C/AD 55774 111
symloc REF02C/AD 55885 105
symloc REF-02D/AD 55990 107
symloc REF02D/AD 56097 105
symloc REF-02E/AD 56202 102
symloc REF02E/AD 56304 105
symloc REF-02H/AD 56409 107
symloc REF02H/AD 56516 105
symloc REF-05/AD 56621 95
symloc REF05/AD 56716 93
symloc REF-05A/AD 56809 96
symloc REF05A/AD 56905 94
symloc REF-05B/AD 56999 96
symloc REF-10/AD 57095 86
symloc REF10/AD 57181 84
symloc REF-10A/AD 57265 87
symloc REF10A/AD 57352 85
symloc REF-10B/AD 57437 87
symloc REF10B/AD 57524 85
symloc REF-195 57609 94
symloc SSM-2017/AD 57703 190
symloc SSM-2017P/AD 57893 112
symloc SSM-2131/AD 58005 105
symloc SSM-2135 58110 98
symloc SSM-2210/AD 58208 99
symloc SSM-2220/AD 58307 99
symloc AD626 58406 114
symloc AD22050N 58520 106
symloc AD22057N 58626 106
symloc AD626AN 58732 112
symloc AD626BN 58844 112
symloc AD8002A 58956 97
symloc AD8002AN 59053 94
symloc AD8002AR 59147 93
symloc ADG406 59240 258
symloc ADG406B:ADG406 59498 28
symloc ADG407 59526 267
symloc ADG407B:ADG407 59793 28
symloc ADG426 59821 286
symloc ADG426B 60107 287
symloc ADG408 60394 182
symloc ADG408B 60576 176
symloc ADG408T 60752 172
symloc ADG409 60924 191
symloc ADG409B 61115 185
symloc ADG409T 61300 181
symloc ADG441_DUAL 61481 184
symloc ADG444_DUAL 61665 185
symloc ADG444B_DUAL 61850 186
symloc ADG444B_SINGLE 62036 188
symloc ADG444_SINGLE 62224 187
symloc ADG441B_DUAL 62411 178
symloc ADG441B_SINGLE 62589 180
symloc ADG441_SINGLE:ADG441_DUAL 62769 39
symloc ADG441T_DUAL 62808 174
symloc ADG441T_SINGLE 62982 176
symloc ADG442_DUAL 63158 177
symloc ADG442B_DUAL:ADG442_DUAL 63335 38
symloc ADG442_SINGLE:ADG442_DUAL 63373 39
symloc ADG508F 63412 189
symloc ADG508FB 63601 183
symloc ADG508FT 63784 173
symloc ADG509F 63957 198
symloc ADG509FT 64155 182
symloc ADG509FB 64337 192
symloc ADG528FB 64529 347
symloc ADG528FT 64876 193
symloc OP196G 65069 106
symloc OP296G 65175 96
symloc OP496G 65271 119
symloc OP484E 65390 119
symloc OP484F:OP484E 65509 27
symloc REF191 65536 85
symloc REF191E 65621 81
symloc REF191F 65702 81
symloc REF191G 65783 86
symloc REF192 65869 85
symloc REF192E 65954 81
symloc REF192F 66035 81
symloc REF192G 66116 86
symloc REF193 66202 85
symloc REF193G 66287 86
symloc REF194 66373 85
symloc REF194E 66458 81
symloc REF194F 66539 81
symloc REF194G 66620 86
symloc REF196 66706 85
symloc REF196G 66791 86
symloc REF198 66877 85
symloc REF198E 66962 81
symloc REF198F 67043 81
symloc REF198G 67124 86
symloc ADG528F 67210 353
symloc OP196 67563 105
symloc OP484 67668 118
symloc ADG442B_SINGLE 67786 180
symloc AD626AR 67966 111
symloc ADG406BN 68077 253
symloc ADG406BP 68330 254
symloc ADG407BN 68584 262
symloc ADG407BP 68846 263
symloc ADG408BN 69109 172
symloc ADG408BR 69281 171
symloc ADG408TQ 69452 173
symloc ADG409BN 69625 181
symloc ADG409BR 69806 180
symloc ADG409TQ 69986 182
symloc ADG426BN 70168 272
symloc ADG426BRS 70440 283
symloc ADG441BN_DUAL 70723 174
symloc ADG441BR_DUAL 70897 173
symloc ADG441BN_SINGLE 71070 176
symloc ADG441BR_SINGLE 71246 175
symloc ADG441TQ_DUAL 71421 175
symloc ADG441TQ_SINGLE 71596 177
symloc ADG442BN_DUAL 71773 174
symloc ADG442BR_DUAL 71947 173
symloc ADG442BN_SINGLE 72120 176
symloc ADG442BR_SINGLE 72296 175
symloc ADG444BN_DUAL 72471 182
symloc ADG444BR_DUAL 72653 181
symloc ADG444BN_SINGLE 72834 184
symloc ADG444BR_SINGLE 73018 183
symloc ADG508FBN 73201 173
symloc ADG508FBRN 73374 173
symloc ADG508FBRW 73547 174
symloc ADG508FTQ 73721 174
symloc ADG509FBN 73895 182
symloc ADG509FBRN 74077 182
symloc ADG509FBRW 74259 183
symloc ADG509FTQ 74442 183
symloc ADG528FBN 74625 193
symloc ADG528FBP 74818 195
symloc ADG528FTQ 75013 194
symloc OP196GP 75207 103
symloc OP196GS 75310 102
symloc OP296GP 75412 93
symloc OP296GS 75505 92
symloc OP496GP 75597 115
symloc OP496GS 75712 114
symloc OP484EP 75826 115
symloc OP484ES 75941 114
symloc OP484FP 76055 115
symloc OP484FS 76170 114
symloc REF191ES 76284 82
symloc REF191FS 76366 82
symloc REF191GP 76448 83
symloc REF191GS 76531 82
symloc REF192ES 76613 82
symloc REF192FS 76695 82
symloc REF192GP 76777 83
symloc REF192GS 76860 82
symloc REF193GP 76942 83
symloc REF193GS 77025 82
symloc REF194ES 77107 82
symloc REF194GP 77189 83
symloc REF194GS 77272 82
symloc REF194FS 77354 82
symloc REF196GP 77436 83
symloc REF196GS 77519 82
symloc REF198ES 77601 82
symloc REF198FS 77683 82
symloc REF198GP 77765 83
symloc REF198GS 77848 82
*package AD581J/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581K/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581L/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581S/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581T/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD581U/AD
@types 1
g 1
@pinout
t TO-5
g 1
p VIN 1
p GND 3
p 10V 2
*package AD584/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD584J/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD584K/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD584L/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD584S/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD584T/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p CAP 7
p VBG 6
p STROBE 5
p GND 4
p VIN 8
p 10V 1
p 5.0V 2
p 2.5V 3
*package AD587/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
t CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
t SO8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587L/AD
@types 1
g 1
@pinout
t DIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
t CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587T/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD587U/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p TRIM 5
p NR 8
p VOUT 6
p VIN 2
p GND 4
*package AD588
@types 1
g 1
@pinout
t LCC20
g 1
p VHIGH 8
p A4+IN 17
p A3+IN 5
p GAIN_ADJ 7
p NOISE 9
p GNDSEN-IN 13
p GNDSEN+IN 12
p BAL_ADJ 15
p VLOW 10
p A3_FORCE 2
p A3_SENSE 4
p A4_FORCE 19
p A4_SENSE 18
p VCT 14
p VS+ 3
p VS- 20
t DIP16
g 1
p VHIGH 6
p A4+IN 13
p A3+IN 4
p GAIN_ADJ 5
p NOISE 7
p GNDSEN-IN 10
p GNDSEN+IN 9
p BAL_ADJ 12
p VLOW 8
p A3_FORCE 1
p A3_SENSE 3
p A4_FORCE 15
p A4_SENSE 14
p VCT 11
p VS+ 2
p VS- 16
*package AD600/AD
@types 2
g 1 A1,A2
@pinout
t DIP16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
t SO16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
*package AD600J/AD
@types 2
g 1 A1,A2
@pinout
t DIP16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
t SO16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
*package AD602/AD
@types 2
g 1 A1,A2
@pinout
t DIP16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
*package AD602J/AD
@types 2
g 1 A1,A2
@pinout
t DIP16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
t SO16
g 1
p + 2,7
p - 3,6
p A1OP 14,11
p A1Cm 15,10
p C1Lo 1,8
p C1Hi 16,9
p Gat1 4,5
s V+ 13
s V- 12
*package AD603/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p G+ 1
p G- 2
p VINP 3
p COMM 4
p FDBK 5
p V- 6
p OUT 7
p V+ 8
t SO8
g 1
p G+ 1
p G- 2
p VINP 3
p COMM 4
p FDBK 5
p V- 6
p OUT 7
p V+ 8
*package AD603A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p G+ 1
p G- 2
p VINP 3
p COMM 4
p FDBK 5
p V- 6
p OUT 7
p V+ 8
t SO8
g 1
p G+ 1
p G- 2
p VINP 3
p COMM 4
p FDBK 5
p V- 6
p OUT 7
p V+ 8
*package AD620/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package AD620A/AD
@types 1
g 1
@attributes
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package AD620B/AD
@types 1
g 1
@attributes
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package AD620S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
t SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package AD624/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p RG1 16
p - 1
p + 2
p V- 7
p REF 6
p OUT 9
p V+ 8
p RG2 3
p SENSE 10
p G100 13
p G200 12
p G500 11
p IN1 4
p IN2 5
p ON1 14
p ON2 15
*package AD624A/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p RG1 16
p - 1
p + 2
p V- 7
p REF 6
p OUT 9
p V+ 8
p RG2 3
p SENSE 10
p G100 13
p G200 12
p G500 11
p IN1 4
p IN2 5
p ON1 14
p ON2 15
*package AD624B/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p RG1 16
p - 1
p + 2
p V- 7
p REF 6
p OUT 9
p V+ 8
p RG2 3
p SENSE 10
p G100 13
p G200 12
p G500 11
p IN1 4
p IN2 5
p ON1 14
p ON2 15
*package AD624C/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p RG1 16
p - 1
p + 2
p V- 7
p REF 6
p OUT 9
p V+ 8
p RG2 3
p SENSE 10
p G100 13
p G200 12
p G500 11
p IN1 4
p IN2 5
p ON1 14
p ON2 15
*package AD624S/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p RG1 16
p - 1
p + 2
p V- 7
p REF 6
p OUT 9
p V+ 8
p RG2 3
p SENSE 10
p G100 13
p G200 12
p G500 11
p IN1 4
p IN2 5
p ON1 14
p ON2 15
*package AD630/AD
@types 1
g 1
@pinout
t DIP20,CDIP20,LCC20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD630A/AD
@types 1
g 1
@pinout
t CDIP20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD630B/AD
@types 1
g 1
@pinout
t CDIP20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD630J/AD
@types 1
g 1
@attributes
@pinout
t DIP20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD630K/AD
@types 1
g 1
@pinout
t DIP20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD630S/AD
@types 1
g 1
@pinout
t CDIP20,LCC20
g 1
p CHA+ 2
p CHA- 20
p RINA 1
p CHB+ 18
p CHB- 19
p RINB 17
p SELA 10
p SELB 9
p RB 14
p RF 15
p RA 16
p COMP 12
p STAT 7
p +VS 11
p -VS 8
p VOUT 13
p DOA1 3
p DOA2 4
p COA1 5
p COA2 6
*package AD633/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p X1 1
p X2 2
p Y1 3
p Y2 4
p Z 6
p W 7
p V+ 8
p V- 5
*package AD633J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p X1 1
p X2 2
p Y1 3
p Y2 4
p Z 6
p W 7
p V+ 8
p V- 5
*package AD645/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD645A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD645B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD645J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD645K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD645S/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD680
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p VIN 2
p VOUT 6
p TEMP 3
p GND 4
*package AD680JT
@types 1
g 1
@pinout
t TO-92
g 1
p VIN 3
p VOUT 2
p GND 1
*package AD704/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package AD704A/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package AD704B/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD704J/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package AD704K/AD
@types 4
g 1 A,B,C,D
@attributes
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD704T/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD705/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD705A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD705B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD705J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD705K/AD
@types 1
g 1
@attributes
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD705T/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD706/AD
@types 2
g 1 A,B
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD706A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD706B/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD706J/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD706K/AD
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD706T/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD711/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711C/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711K/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711S/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD711T/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD712/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712B/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712C/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712J/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712K/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712S/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD712T/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD713/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package AD713A/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD713B/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD713J/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package AD713K/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD713S/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD713T/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package AD734/AD
@types 1
g 1
@pinout
t CDIP14,DIP14
g 1
p X1 1
p X2 2
p U0 3
p U1 4
p U2 5
p Y1 6
p Y2 7
p VN 8
p ER 9
p Z2 10
p Z1 11
p W 12
p DD 13
p VP 14
*package AD734A/AD
@types 1
g 1
@pinout
t CDIP14,DIP14
g 1
p X1 1
p X2 2
p U0 3
p U1 4
p U2 5
p Y1 6
p Y2 7
p VN 8
p ER 9
p Z2 10
p Z1 11
p W 12
p DD 13
p VP 14
*package AD734B/AD
@types 1
g 1
@pinout
t CDIP14,DIP14
g 1
p X1 1
p X2 2
p U0 3
p U1 4
p U2 5
p Y1 6
p Y2 7
p VN 8
p ER 9
p Z2 10
p Z1 11
p W 12
p DD 13
p VP 14
*package AD734S/AD
@types 1
g 1
@pinout
t CDIP14
g 1
p X1 1
p X2 2
p U0 3
p U1 4
p U2 5
p Y1 6
p Y2 7
p VN 8
p ER 9
p Z2 10
p Z1 11
p W 12
p DD 13
p VP 14
*package AD743/AD
@types 1
g 1
@pinout
t CDIP8,DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
*package AD743A/AD
@types 1
g 1
@pinout
t CDIP8,DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
*package AD743B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD743J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
*package AD743K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
*package AD743S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD744/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744C/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744K/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744S/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD744T/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N2 8
p C 5
p N1 1
*package AD745/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
*package AD745A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD745B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD745J/AD
@types 1
g 1
@pinout
t SO16
g 1
p + 5
p - 3
p V+ 13
p V- 6
p OUT 12
p N1 2
p N2 11
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD745K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD745S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package AD746/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD746A/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD746B/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD746J/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD746S/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD780/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p VIN 2
p TEMP 3
p GND 4
p TRIM 5
p VOUT 6
p SEL 8
*package AD780A/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p VIN 2
p TEMP 3
p GND 4
p TRIM 5
p VOUT 6
p SEL 8
*package AD780B/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p VIN 2
p TEMP 3
p GND 4
p TRIM 5
p VOUT 6
p SEL 8
*package AD780S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p VIN 2
p TEMP 3
p GND 4
p TRIM 5
p VOUT 6
p SEL 8
*package AD795/AD
@types 1
g 1
@pinout
t TO-99
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
t DIP8
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
*package AD795J/AD
@types 1
g 1
@pinout
t TO-99
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
t DIP8
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
*package AD795K/AD
@types 1
g 1
@pinout
t TO-99
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
t DIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package AD797/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p DCMP 8
p N1 1
p N2 5
*package AD797A/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p DCMP 8
p N1 1
p N2 5
*package AD797B/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p DCMP 8
p N1 1
p N2 5
*package AD797S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p DCMP 8
p N1 1
p N2 5
*package AD811/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
t DIP16
g 1
p + 5
p - 3
p V+ 14
p V- 7
p OUT 12
t DIP20
g 1
p + 6
p - 4
p V+ 17
p V- 8
p OUT 15
t LCC20
g 1
p + 8
p - 6
p V+ 16
p V- 9
p OUT 14
*package AD810/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p OUT 6
p + 3
p - 2
p DISABLE 8
p V+ 7
p V- 4
*package AD810A/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p OUT 6
p + 3
p - 2
p DISABLE 8
p V+ 7
p V- 4
*package AD810S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p OUT 6
p + 3
p - 2
p DISABLE 8
p V+ 7
p V- 4
*package AD812/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V- 4
s V+ 8
*package AD812A/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V- 4
s V+ 8
*package AD813/AD
@types 3
g 1 A,B,C
@pinout
t DIP14,SO14
g 1
p OUT 7,14,8
p + 5,12,10
p - 6,13,9
p DISABLE 1,2,3
s V- 11
s V+ 4
*package AD813A/AD
@types 3
g 1 A,B,C
@pinout
t DIP14,SO14
g 1
p OUT 7,14,8
p + 5,12,10
p - 6,13,9
p DISABLE 1,2,3
s V- 11
s V+ 4
*package AD817/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package AD817A/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package AD818/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package AD818A/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package AD820/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package AD824/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16W
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package AD824A/AD ako AD824/AD
*package AD824B/AD ako AD824/AD
*package AD826/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD826A/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD828/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD828A/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package AD829/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD829A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD829J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD829S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD830/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p +X 1
p -X 2
p +Y 3
p -Y 4
p V- 5
p OUT 7
p V+ 8
*package AD830A/AD
@types 1
g 1
@pinout
t DIP8
g 1
p +X 1
p -X 2
p +Y 3
p -Y 4
p V- 5
p OUT 7
p V+ 8
*package AD830J/AD
@types 1
g 1
@pinout
t SO8
g 1
p +X 1
p -X 2
p +Y 3
p -Y 4
p V- 5
p OUT 7
p V+ 8
*package AD830S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p +X 1
p -X 2
p +Y 3
p -Y 4
p V- 5
p OUT 7
p V+ 8
*package AD840/AD
@types 1
g 1
@pinout
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD-840/AD
@types 1
g 1
@pinout
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD840J/AD
@types 1
g 1
@pinout
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD-840J/AD
@types 1
g 1
@pinout
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD840K/AD
@types 1
g 1
@pinout
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD-840K/AD
@types 1
g 1
@pinout
t DIP14,CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD840S/AD
@types 1
g 1
@pinout
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
t CDIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD-840S/AD
@types 1
g 1
@pinout
t LCC20
g 1
p + 7
p - 4
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
t CDIP14,DIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p B1 3
p B2 12
*package AD843/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p B1 3
p B2 14
t TO-8
g 1
p + 6
p - 5
p V+ 12
p V- 10
p OUT 11
p B1 3
p B2 4
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
*package AD843A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
*package AD843B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
t TO-8
g 1
p + 6
p - 5
p V+ 12
p V- 10
p OUT 11
p B1 3
p B2 4
*package AD843J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p B1 3
p B2 14
*package AD843K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
*package AD843S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 8
t TO-8
g 1
p + 6
p - 5
p V+ 12
p V- 10
p OUT 11
p B1 3
p B2 4
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p B1 2
p B2 20
*package AD844/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
t SO16
g 1
p + 5
p - 3
p V+ 14
p V- 7
p OUT 12
p C 11
p N1 2
p N2 15
*package AD844A/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD844B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD844S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
p N1 1
p N2 8
*package AD845/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p N1 3
p N2 14
*package AD-845/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p N1 3
p N2 14
*package AD845A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD-845A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD845B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD-845B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD845J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p N1 3
p N2 14
*package AD-845J/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 6
p OUT 12
p N1 3
p N2 14
*package AD845K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD-845K/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD845S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD-845S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD846/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
*package AD846A/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
*package AD846B/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
*package AD846S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C 5
*package AD847/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD847A/AD
@types 1
g 1
@pinout
t CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD847J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD847S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD848/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD848A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD848J/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD848S/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package AD8001A/AD
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package AD8001AN/AD
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p V- 4
p OUT 6
p V+ 7
*package AD8001AR/AD
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package AD9617/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p VO+ 8
p VO- 5
*package AD9618/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p VO+ 8
p VO- 5
*package AD9621/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
*package AD9622/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
*package AD9623/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
*package AD9624/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
*package AD9630/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,SO8
g 1
p VIN 4
p VOUT 8
p VDD 1
p VSS 5
*package ADG411/AD
@types 1
g 1
@pinout
t DIP16,SO16,CDIP16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG411B/AD
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG411T/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG412/AD
@types 1
g 1
@pinout
t DIP16,SO16,CDIP16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG412B/AD
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG412T/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG413/AD
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG413B/AD
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package ADG413T/AD
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p D1 2
p S1 3
p VSS 4
p GND 5
p S4 6
p D4 7
p IN4 8
p IN3 9
p D3 10
p S3 11
p VL 12
p VDD 13
p S2 14
p D2 15
p IN2 16
*package AMP-01/AD
@types 1
g 1
@pinout
t CDIP18
g 1
p RG1 1
p RG2 2
p - 3
p SENSE 7
p REF 8
p OUT 9
p VOP- 10
p V- 11
p V+ 12
p VOP+ 13
p RS1 14
p RS2 15
p + 18
p VON1 4
p VON2 5
p VIN1 16
p VIN2 17
t SOP20
g 1
p RG1 1
p RG2 20
p - 3
p SENSE 7
p REF 8
p OUT 9
p VOP- 10
p V- 11
p V+ 12
p VOP+ 13
p RS1 14
p RS2 15
p + 18
p VON1 4
p VON2 5
p VIN1 16
p VIN2 17
t LCC28
g 1
p RG1 2
p RG2 3
p - 4
p SENSE 12
p REF 13
p OUT 14
p VOP- 16
p V- 18
p V+ 19
p VOP+ 21
p RS1 22
p RS2 23
p + 28
p VON1 6
p VON2 8
p VIN1 25
p VIN2 26
*package AMP-02/AD
@types 1
g 1
@pinout
t DIP8
g 1
p RG1 1
p - 2
p + 3
p V- 4
p REF 5
p OUT 6
p V+ 7
p RG2 8
t SO16
g 1
p RG1 2
p - 4
p + 5
p V- 7
p REF 10
p OUT 11
p V+ 13
p RG2 15
*package AMP-04
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 2
p + 3
p RG1 1
p RG2 8
p REF 5
p OUT 6
p V+ 7
p V- 4
*package BUF04/AD
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p + 3
p V+ 7
p V- 4
p OUT 6
*package MAT-02/AD
@types 1
g 1
@pinout
t TO-78
g 1
p C1 1
p B1 2
p E1 3
p E2 5
p B2 6
p C2 7
p SUB 8
t LCC20
g 1
p C1 2
p B1 7
p E1 10
p E2 12
p B2 15
p C2 20
p SUB 5
*package MAT-03/AD
@types 1
g 1
@pinout
t TO-78
g 1
p C1 1
p B1 2
p E1 3
p E2 5
p B2 6
p C2 7
t LCC20
g 1
p C1 2
p B1 7
p E1 10
p E2 12
p B2 15
p C2 20
*package MAT-04/AD
@types 1
g 1
@pinout
t DIP14,CDIP14,SO14
g 1
p C1 1
p B1 2
p E1 3
p SUB1 4
p E2 5
p B2 6
p C2 7
p C3 8
p B3 9
p E3 10
p SUB2 11
p E4 12
p B4 13
p C4 14
*package MLT04/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP18,SOP18
g 1
p X 3,7,12,16
p Y 4,6,13,15
p GND 2,8,11,17
p W 1,9,10,18
s V- 14
s V+ 5
*package MLT04G/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP18,SOP18
g 1
p X 3,7,12,16
p Y 4,6,13,15
p GND 2,8,11,17
p W 1,9,10,18
s V- 14
s V+ 5
*package OP-08
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p - 2
p + 3
p COMP1 1
p COMP2 8
p OUT 6
p V+ 7
p V- 4
*package OP-20/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-20B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-20C/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-20F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-20G/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-20H/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21E/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21G/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-21H/AD
@types 1
g 1
@pinout
t SO8,DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package OP-27/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-27A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-27B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-27C/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-27E/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-27F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-27G/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-37/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-37A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-37B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-37C/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-37E/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-37F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-37G/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p N1 1
p N2 8
p OUT 6
*package OP-41/AD
@types 1
g 1
@pinout
t DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-41A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-41B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-41E/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-41F/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-41G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-42/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 12
*package OP-42A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 12
*package OP-42E/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-42F/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-42G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43E/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43F/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-43G/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-44/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 12
*package OP-61/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 12
*package OP-64/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
p \DIS\ 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 12
p \DIS\ 20
*package OP-77/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-77A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-77B/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-77E/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-77F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-77G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-80/AD
@types 1
g 1
@pinout
t DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package OP-80B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package OP-80E/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package OP-80F/AD
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package OP-80G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
*package OP-90/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-90A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-90E/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-90F/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-90G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package OP-97/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
p OVC 5
*package OP-97A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
p OVC 5
*package OP-97E/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
p OVC 5
*package OP-97F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
p OVC 5
*package OP-113
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p N1 1
p N2 5
p - 2
p + 3
p V+ 7
p V- 4
p OUT 6
*package OP-160/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
p \DIS\ 8
t LCC20
g 1
p + 8
p - 6
p V+ 16
p V- 9
p OUT 14
p N1 2
p N2 12
p \DIS\ 20
*package OP-160A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
p \DIS\ 8
t LCC20
g 1
p + 8
p - 6
p V+ 16
p V- 9
p OUT 14
p N1 2
p N2 12
p \DIS\ 20
*package OP-160F/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
p \DIS\ 8
*package OP-160G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
p \DIS\ 8
*package OP-176/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p V- 4
p V+ 7
p + 3
p - 2
p OUT 6
*package OP-176G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p V- 4
p V+ 7
p + 3
p - 2
p OUT 6
*package OP-177/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-177A/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-177B/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p N1 2
p N2 20
*package OP-177E/AD
@types 1
g 1
@pinout
t CDIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-177F/AD
@types 1
g 1
@pinout
t CDIP8,DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-177G/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
*package OP-183
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p N1 1
p N2 5
p - 2
p + 3
p V+ 7
p V- 4
p OUT 6
*package OP-200/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO16
g 1
p + 2,6
p - 1,7
p OUT 16,10
s V+ 13
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-200A/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-200E/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-200F/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-200G/AD
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO16
g 1
p + 2,6
p - 1,7
p OUT 16,10
s V+ 13
s V- 4
*package OP-213
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-295/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-215/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t DIP8,CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 3,9
p - 2,10
p OUT 18,14
s V+ 19
s V- 6
*package OP-215A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-215B/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 3,9
p - 2,10
p OUT 18,14
s V+ 19
s V- 6
*package OP-215C/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-215E/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-215F/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-215G/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t DIP8,CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220C/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220E/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220F/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-220G/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-221/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
*package OP-221A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-221B/AD
@types 2
g 1 A,B
@pinout
t TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-221C/AD
@types 2
g 1 A,B
@pinout
t TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-221E/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-221G/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-249/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-249A/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-249E/AD
@types 2
g 1 A,B
@pinout
t TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-249F/AD
@types 2
g 1 A,B
@pinout
t CDIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-249G/AD
@types 2
g 1 A,B
@pinout
t SO8
g 1
p + 1,3
p - 8,4
p OUT 7,5
s V+ 6
s V- 2
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-260/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO16
g 1
p + 2,6
p - 1,7
p OUT 16,10
s V+ 13
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-275/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-275G/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-282/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-282G/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-283
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP-283/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V- 4
s V+ 8
*package OP-285/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-285G/AD
@types 2
g 1 A,B
@attributes
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-290/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO16
g 1
p + 2,6
p - 1,7
p OUT 16,10
s V+ 13
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-290A/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-290E/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-290F/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-290G/AD
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t SO16
g 1
p + 2,6
p - 1,7
p OUT 16,10
s V+ 13
s V- 4
*package OP-291
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP-292/AD
@types 2
g 1 A,B
@attributes
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-297/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-297A/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t LCC20
g 1
p + 7,12
p - 5,15
p OUT 2,17
s V+ 20
s V- 10
*package OP-297E/AD
@types 2
g 1 A,B
@pinout
t CDIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-297F/AD
@types 2
g 1 A,B
@pinout
t CDIP8,DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-297G/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package OP-400/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-400A/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-400E/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-400F/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-400G/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-400H/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-413
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16W
g 1
p - 2,6,11,15
p + 3,5,12,14
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-420/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-420B/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-420C/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-420F/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-420G/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-420H/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-421/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-421B/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-421C/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-421F/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-421G/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-421H/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-467/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-467G/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-470/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-482/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-482G/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-490/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-490A/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-490E/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-490F/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-490G/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-491
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-492/AD
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-497/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-497A/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-497B/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package OP-497C/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-497F/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP-497G/AD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14,DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t SO16
g 1
p + 3,5,12,14
p - 2,6,11,15
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OP191/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package OP191G/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package OP279/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP279G/AD
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP284/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package OP284E/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package OP284F/AD
@types 1
g 1
@pinout
t DIP8,CDIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p V- 4
*package PM-1012/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 8
p OVC 5
*package REF-01/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
t LCC20
g 1
p VIN 5
p GND 10
p TRIM 12
p VOUT 15
*package REF01/AD
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
t LCC20
g 1
p VIN 5
p GND 10
p TRIM 12
p OUT 15
*package REF-01A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF01A/AD
@types 1
g 1
@pinout
t DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-01C/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF01C/AD
@types 1
g 1
@pinout
t DIP8,TO-99,CDIP8
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-01E/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF01E/AD
@types 1
g 1
@pinout
t DIP8,TO-99,CDIP8
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-01H/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF01H/AD
@types 1
g 1
@pinout
t DIP8,TO-99,CDIP8
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-02/AD
@types 1
g 1
@pinout
t CDIP8,TO-99,DIP8
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
t LCC20
g 1
p VIN 5
p GND 10
p TRIM 12
p VOUT 15
p TEMP 7
*package REF02/AD
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
t LCC20
g 1
p VIN 5
p GND 10
p TRIM 12
p OUT 15
p TEMP 7
*package REF-02A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF02A/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-02C/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,SO8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF02C/AD
@types 1
g 1
@pinout
t DIP8,TO-99,CDIP8
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-02D/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF02D/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-02E/AD
@types 1
g 1
@pinout
t CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF02E/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-02H/AD
@types 1
g 1
@pinout
t CDIP8,DIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF02H/AD
@types 1
g 1
@pinout
t DIP8,CDIP8,TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-05/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF05/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-05A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
p TEMP 3
*package REF05A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
p TEMP 3
*package REF-05B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p GND 4
p VIN 2
p TRIM 5
p VOUT 6
p TEMP 3
*package REF-10/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF10/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-10A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF10A/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-10B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p VOUT 6
*package REF10B/AD
@types 1
g 1
@pinout
t TO-99
g 1
p VIN 2
p GND 4
p TRIM 5
p OUT 6
*package REF-195
@types 1
g 1
@pinout
t DIP8,SO8,CDIP8
g 1
p V+ 2
p SHTDWN 3
p VOUT 6
p GND 4
*package SSM-2017/AD
@types 1
g 1
@pinout
t SO16
g 1
p + 5
p - 4
p V+ 13
p V- 7
p OUT 11
p REF 10
p RG1 2
p RG2 15
t CDIP8,DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package SSM-2017P/AD
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p REF 5
p RG1 1
p RG2 8
*package SSM-2131/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p N1 1
p N2 5
*package SSM-2135
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package SSM-2210/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p C1 1
p B1 2
p E1 3
p E2 6
p B2 7
p C2 8
*package SSM-2220/AD
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p C1 1
p B1 2
p E1 3
p E2 6
p B2 7
p C2 8
*package AD626
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 1
p + 8
p GND 2
p V- 3
p FILTER 4
p OUT 5
p V+ 6
p G=100 7
*package AD22050N
@types 1
g 1
@pinout
t DIP8
g 1
p + 8
p - 1
p V- 2
p OUT 5
p A1 3
p A2 4
p V+ 6
p OFS 7
*package AD22057N
@types 1
g 1
@pinout
t DIP8
g 1
p + 8
p - 1
p v- 2
p OUT 5
p A1 3
p A2 4
p V+ 6
p OFS 7
*package AD626AN
@types 1
g 1
@pinout
t DIP8
g 1
p - 1
p + 8
p GND 2
p V- 3
p FILTER 4
p OUT 5
p V+ 6
p G=100 7
*package AD626BN
@types 1
g 1
@pinout
t DIP8
g 1
p - 1
p + 8
p GND 2
p V- 3
p FILTER 4
p OUT 5
p V+ 6
p G=100 7
*package AD8002A
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V- 4
s V+ 8
*package AD8002AN
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V- 4
s V+ 8
*package AD8002AR
@types 2
g 1 A,B
@pinout
t SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V- 4
s V+ 8
*package ADG406
@types 1
g 1
@pinout
t DIP28,PLCC28
g 1
p S16 4
p S15 5
p S14 6
p S13 7
p S12 8
p S11 9
p S10 10
p S9 11
p S8 26
p S7 25
p S6 24
p S5 23
p S4 22
p S3 21
p S2 20
p S1 19
p GND 12
p EN 18
p A0 17
p A1 16
p A3 14
p A2 15
p VSS 27
p D 28
p VDD 1
*package ADG406B ako ADG406
*package ADG407
@types 1
g 1
@pinout
t DIP28,PLCC28
g 1
p S8B 4
p S7B 5
p S6B 6
p S5B 7
p S4B 8
p S3B 9
p S2B 10
p S1B 11
p S2A 20
p S3A 21
p S4A 22
p S5A 23
p S6A 24
p S7A 25
p S8A 26
p GND 12
p A2 15
p A1 16
p A0 17
p EN 18
p S1A 19
p VSS 27
p DB 2
p DA 28
p VDD 1
*package ADG407B ako ADG407
*package ADG426
@types 1
g 1
@pinout
t DIP28,SSOP28/MO-137AF
g 1
p EN 18
p \WR\ 13
p \RS\ 3
p A0 17
p A1 16
p A2 15
p A3 14
p S1 19
p S2 20
p S3 21
p S4 22
p S5 23
p S6 24
p S7 25
p S8 26
p S9 11
p S10 10
p S11 9
p S12 8
p S13 7
p S14 6
p S15 5
p S16 4
p GND 12
p VSS 27
p D 28
p VDD 1
*package ADG426B
@types 1
g 1
@pinout
t DIP28,SSOP28/MO-137AF
g 1
p EN 18
p \WR\ 13
p \RS\ 3
p A0 17
p A1 16
p A2 15
p A3 14
p S1 19
p S2 20
p S3 21
p S4 22
p S5 23
p S6 24
p S7 25
p S8 26
p S9 11
p S10 10
p S11 9
p S12 8
p S13 7
p S14 6
p S15 5
p S16 4
p GND 12
p VSS 27
p D 28
p VDD 1
*package ADG408
@types 1
g 1
@pinout
t DIP16,CDIP16,SO16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p A1 16
p A2 15
p EN 2
p GND 14
p VSS 3
p D 8
p VDD 13
*package ADG408B
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG408T
@types 1
g 1
@pinout
t CDIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG409
@types 1
g 1
@pinout
t DIP16,SO16,CDIP16
g 1
p EN 2
p A0 1
p A1 16
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p VSS 3
p GND 15
p DA 8
p DB 9
p VDD 14
*package ADG409B
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p EN 2
p A0 1
p A1 16
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p VSS 3
p GND 15
p DA 8
p DB 9
p VDD 14
*package ADG409T
@types 1
g 1
@pinout
t CDIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG441_DUAL
@types 1
g 1
@pinout
t CDIP16,DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG444_DUAL
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444B_DUAL
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444B_SINGLE
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444_SINGLE
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG441B_DUAL
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441B_SINGLE
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441_SINGLE ako ADG441_DUAL
*package ADG441T_DUAL
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441T_SINGLE
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442_DUAL
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442B_DUAL ako ADG442_DUAL
*package ADG442_SINGLE ako ADG442_DUAL
*package ADG508F
@types 1
g 1
@pinout
t DIP16,SO16,SO16W,CDIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG508FB
@types 1
g 1
@pinout
t DIP16,SO16,SO16W
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG508FT
@types 1
g 1
@pinout
t CDIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG509F
@types 1
g 1
@pinout
t DIP16,SO16,SO16W,CDIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG509FT
@types 1
g 1
@pinout
t CDIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG509FB
@types 1
g 1
@pinout
t DIP16,SO16,SO16W
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG528FB
@types 1
g 1
@pinout
t DIP18
g 1
p \WR\ 1
p S1 5
p S2 6
p S3 7
p S4 8
p S8 10
p S7 11
p S6 12
p S5 13
p \RS\ 18
p A0 2
p EN 3
p VSS 4
p GND 15
p A2 16
p A1 17
p D 9
p VDD 14
t PLCC20
g 1
p \WR\ 2
p S1 6
p S2 7
p S3 8
p S4 9
p S8 12
p S7 13
p S6 14
p S5 15
p \RS\ 20
p A0 3
p EN 4
p VSS 5
p GND 17
p A2 18
p A1 19
p D 10
p VDD 16
*package ADG528FT
@types 1
g 1
@pinout
t CDIP18
g 1
p \WR\ 1
p S1 5
p S2 6
p S3 7
p S4 8
p S8 10
p S7 11
p S6 12
p S5 13
p \RS\ 18
p A0 2
p EN 3
p VSS 4
p GND 15
p A2 16
p A1 17
p D 9
p VDD 14
*package OP196G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 2
p + 3
p NULL1 1
p NULL2 5
p V- 4
p OUT 6
p V+ 7
*package OP296G
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP496G
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484E
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484F ako OP484E
*package REF191
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p VS 2
*package REF191E
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p VS 2
*package REF191F
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p VS 2
*package REF191G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192E
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192F
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF193
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF193G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194E
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194F
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF196
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF196G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198E
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198F
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198G
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package ADG528F
@types 1
g 1
@pinout
t DIP18,CDIP18
g 1
p \WR\ 1
p S1 5
p S2 6
p S3 7
p S4 8
p S8 10
p S7 11
p S6 12
p S5 13
p \RS\ 18
p A0 2
p EN 3
p VSS 4
p GND 15
p A2 16
p A1 17
p D 9
p VDD 14
t PLCC20
g 1
p \WR\ 2
p S1 6
p S2 7
p S3 8
p S4 9
p S8 12
p S7 13
p S6 14
p S5 15
p \RS\ 20
p A0 3
p EN 4
p VSS 5
p GND 17
p A2 18
p A1 19
p D 10
p VDD 16
*package OP196
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p - 2
p + 3
p NULL1 1
p NULL2 5
p V- 4
p OUT 6
p V+ 7
*package OP484
@types 4
g 1 A,B,C,D
@pinout
t DIP14,SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package ADG442B_SINGLE
@types 1
g 1
@pinout
t DIP16,SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package AD626AR
@types 1
g 1
@pinout
t SO8
g 1
p - 1
p + 8
p GND 2
p V- 3
p FILTER 4
p OUT 5
p V+ 6
p G=100 7
*package ADG406BN
@types 1
g 1
@pinout
t DIP28
g 1
p S16 4
p S15 5
p S14 6
p S13 7
p S12 8
p S11 9
p S10 10
p S9 11
p S8 26
p S7 25
p S6 24
p S5 23
p S4 22
p S3 21
p S2 20
p S1 19
p GND 12
p EN 18
p A0 17
p A1 16
p A3 14
p A2 15
p VSS 27
p D 28
p VDD 1
*package ADG406BP
@types 1
g 1
@pinout
t PLCC28
g 1
p S16 4
p S15 5
p S14 6
p S13 7
p S12 8
p S11 9
p S10 10
p S9 11
p S8 26
p S7 25
p S6 24
p S5 23
p S4 22
p S3 21
p S2 20
p S1 19
p GND 12
p EN 18
p A0 17
p A1 16
p A3 14
p A2 15
p VSS 27
p D 28
p VDD 1
*package ADG407BN
@types 1
g 1
@pinout
t DIP28
g 1
p S8B 4
p S7B 5
p S6B 6
p S5B 7
p S4B 8
p S3B 9
p S2B 10
p S1B 11
p S2A 20
p S3A 21
p S4A 22
p S5A 23
p S6A 24
p S7A 25
p S8A 26
p GND 12
p A2 15
p A1 16
p A0 17
p EN 18
p S1A 19
p VSS 27
p DB 2
p DA 28
p VDD 1
*package ADG407BP
@types 1
g 1
@pinout
t PLCC28
g 1
p S8B 4
p S7B 5
p S6B 6
p S5B 7
p S4B 8
p S3B 9
p S2B 10
p S1B 11
p S2A 20
p S3A 21
p S4A 22
p S5A 23
p S6A 24
p S7A 25
p S8A 26
p GND 12
p A2 15
p A1 16
p A0 17
p EN 18
p S1A 19
p VSS 27
p DB 2
p DA 28
p VDD 1
*package ADG408BN
@types 1
g 1
@pinout
t DIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG408BR
@types 1
g 1
@pinout
t SO16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG408TQ
@types 1
g 1
@pinout
t CDIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S5 12
p S6 11
p S7 10
p S8 9
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG409BN
@types 1
g 1
@pinout
t DIP16
g 1
p EN 2
p A0 1
p A1 16
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p VSS 3
p GND 15
p DA 8
p DB 9
p VDD 14
*package ADG409BR
@types 1
g 1
@pinout
t SO16
g 1
p EN 2
p A0 1
p A1 16
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p VSS 3
p GND 15
p DA 8
p DB 9
p VDD 14
*package ADG409TQ
@types 1
g 1
@pinout
t CDIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S1B 13
p S2B 12
p S3B 11
p S4B 10
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG426BN
@types 1
g 1
@pinout
t DIP28
g 1
p EN 18
p \WR\ 13
p \RS\ 3
p A0 17
p A1 16
p A2 15
p A3 14
p S1 19
p S2 20
p S3 21
p S4 22
p S5 23
p S6 24
p S7 25
p S8 26
p S9 11
p S10 10
p S11 9
p S12 8
p S13 7
p S14 6
p S15 5
p S16 4
p GND 12
p VSS 27
p D 28
p VDD 1
*package ADG426BRS
@types 1
g 1
@pinout
t SSOP28/MO-137AF
g 1
p EN 18
p \WR\ 13
p \RS\ 3
p A0 17
p A1 16
p A2 15
p A3 14
p S1 19
p S2 20
p S3 21
p S4 22
p S5 23
p S6 24
p S7 25
p S8 26
p S9 11
p S10 10
p S11 9
p S12 8
p S13 7
p S14 6
p S15 5
p S16 4
p GND 12
p VSS 27
p D 28
p VDD 1
*package ADG441BN_DUAL
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441BR_DUAL
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441BN_SINGLE
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441BR_SINGLE
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441TQ_DUAL
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG441TQ_SINGLE
@types 1
g 1
@pinout
t CDIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442BN_DUAL
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442BR_DUAL
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442BN_SINGLE
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG442BR_SINGLE
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
*package ADG444BN_DUAL
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444BR_DUAL
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444BN_SINGLE
@types 1
g 1
@pinout
t DIP16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG444BR_SINGLE
@types 1
g 1
@pinout
t SO16
g 1
p IN1 1
p IN4 8
p IN3 9
p IN2 16
p VSS 4
p GND 5
p D1 2
p S1 3
p S4 6
p D4 7
p D3 10
p S3 11
p S2 14
p D2 15
p VDD 13
p VL 12
*package ADG508FBN
@types 1
g 1
@pinout
t DIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG508FBRN
@types 1
g 1
@pinout
t SO16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG508FBRW
@types 1
g 1
@pinout
t SO16W
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG508FTQ
@types 1
g 1
@pinout
t CDIP16
g 1
p S1 4
p S2 5
p S3 6
p S4 7
p S8 9
p S7 10
p S6 11
p S5 12
p A0 1
p EN 2
p VSS 3
p GND 14
p A2 15
p A1 16
p D 8
p VDD 13
*package ADG509FBN
@types 1
g 1
@pinout
t DIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG509FBRN
@types 1
g 1
@pinout
t SO16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG509FBRW
@types 1
g 1
@pinout
t SO16W
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG509FTQ
@types 1
g 1
@pinout
t CDIP16
g 1
p S1A 4
p S2A 5
p S3A 6
p S4A 7
p S4B 10
p S3B 11
p S2B 12
p S1B 13
p A0 1
p EN 2
p VSS 3
p GND 15
p A1 16
p DA 8
p DB 9
p VDD 14
*package ADG528FBN
@types 1
g 1
@pinout
t DIP18
g 1
p \WR\ 1
p S1 5
p S2 6
p S3 7
p S4 8
p S8 10
p S7 11
p S6 12
p S5 13
p \RS\ 18
p A0 2
p EN 3
p VSS 4
p GND 15
p A2 16
p A1 17
p D 9
p VDD 14
*package ADG528FBP
@types 1
g 1
@pinout
t PLCC20
g 1
p \WR\ 2
p S1 6
p S2 7
p S3 8
p S4 9
p S8 12
p S7 13
p S6 14
p S5 15
p \RS\ 20
p A0 3
p EN 4
p VSS 5
p GND 17
p A2 18
p A1 19
p D 10
p VDD 16
*package ADG528FTQ
@types 1
g 1
@pinout
t CDIP18
g 1
p \WR\ 1
p S1 5
p S2 6
p S3 7
p S4 8
p S8 10
p S7 11
p S6 12
p S5 13
p \RS\ 18
p A0 2
p EN 3
p VSS 4
p GND 15
p A2 16
p A1 17
p D 9
p VDD 14
*package OP196GP
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p NULL1 1
p NULL2 5
p V- 4
p OUT 6
p V+ 7
*package OP196GS
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p NULL1 1
p NULL2 5
p V- 4
p OUT 6
p V+ 7
*package OP296GP
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP296GS
@types 2
g 1 A,B
@pinout
t SO8
g 1
p - 2,6
p + 3,5
p OUT 1,7
s V+ 8
s V- 4
*package OP496GP
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP496GS
@types 4
g 1 A,B,C,D
@pinout
t SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484EP
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484ES
@types 4
g 1 A,B,C,D
@pinout
t SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484FP
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP484FS
@types 4
g 1 A,B,C,D
@pinout
t SO14
g 1
p - 2,6,9,13
p + 3,5,10,12
p OUT 1,7,8,14
s V+ 4
s V- 11
*package REF191ES
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p VS 2
*package REF191FS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p VS 2
*package REF191GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF191GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192ES
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192FS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF192GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF193GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF193GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194ES
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF194FS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF196GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF196GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198ES
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198FS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198GP
@types 1
g 1
@pinout
t DIP8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
*package REF198GS
@types 1
g 1
@pinout
t SO8
g 1
p SLEEP 3
p GND 4
p OUT 6
p Vs 2
