*version 8.0 126543735
@index
symloc 2N696 0 65
symloc 2N697 65 98
symloc 2N706 163 69
symloc 2N708 232 96
symloc 2N718 328 78
symloc 2N718A 406 79
symloc 2N722 485 78
symloc 2N743 563 66
symloc 2N744 629 66
symloc 2N753 695 66
symloc 2N760 761 78
symloc 2N760A 839 79
symloc 2N834 918 66
symloc 2N869 984 66
symloc 2N869A 1050 67
symloc 2N914 1117 78
symloc 2N915 1195 78
symloc 2N916 1273 78
symloc 2N929 1351 78
symloc 2N929A 1429 79
symloc 2N930 1508 78
symloc 2N956 1586 78
symloc 2N995 1664 66
symloc 2N995A 1730 67
symloc 2N1132 1797 78
symloc 2N1132A 1875 71
symloc 2N1420 1946 78
symloc 2N1566 2024 78
symloc 2N1613 2102 99
symloc 2N1711 2201 99
symloc 2N2193A 2300 71
symloc 2N2217 2371 78
symloc 2N2218 2449 99
symloc 2N2218A 2548 100
symloc 2N2219 2648 99
symloc 2N2219A 2747 100
symloc 2N2220 2847 79
symloc 2N2221 2926 70
symloc 2N2221A 2996 71
symloc 2N2222 3067 76
symloc 2N2222A 3143 77
symloc 2N2270 3220 70
symloc 2N2282 3290 79
symloc 2N2369 3369 70
symloc 2N2369A 3439 80
symloc 2N2484 3519 79
symloc 2N2509 3598 79
symloc 2N2510 3677 79
symloc 2N2511 3756 79
symloc 2N2586 3835 79
symloc 2N2604 3914 79
symloc 2N2605 3993 70
symloc 2N2696 4063 79
symloc 2N2712 4142 67
symloc 2N2714 4209 67
symloc 2N2857 4276 103
symloc 2N2894 4379 70
symloc 2N2894A 4449 71
symloc 2N2897 4520 79
symloc 2N2904 4599 99
symloc 2N2904A 4698 100
symloc 2N2905 4798 99
symloc 2N2905A 4897 100
symloc 2N2906 4997 103
symloc 2N2906A 5100 71
symloc 2N2907 5171 70
symloc 2N2907A 5241 71
symloc 2N2923 5312 67
symloc 2N2924 5379 67
symloc 2N2925 5446 67
symloc 2N2926 5513 67
symloc 2N3009 5580 79
symloc 2N3011 5659 70
symloc 2N3012 5729 97
symloc 2N3013 5826 79
symloc 2N3015 5905 96
symloc 2N3019 6001 70
symloc 2N3020 6071 70
symloc 2N3053 6141 79
symloc 2N3072 6220 78
symloc 2N3073 6298 79
symloc 2N3115 6377 79
symloc 2N3116 6456 79
symloc 2N3117 6535 79
symloc 2N3120 6614 78
symloc 2N3121 6692 79
symloc 2N3133 6771 96
symloc 2N3134 6867 78
symloc 2N3135 6945 79
symloc 2N3136 7024 79
symloc 2N3209 7103 97
symloc 2N3227 7200 79
symloc 2N3244 7279 70
symloc 2N3245 7349 70
symloc 2N3246 7419 79
symloc 2N3248 7498 97
symloc 2N3249 7595 97
symloc 2N3250 7692 79
symloc 2N3250A 7771 80
symloc 2N3251 7851 79
symloc 2N3251A 7930 80
symloc 2N3252 8010 70
symloc 2N3253 8080 70
symloc 2N3299 8150 66
symloc 2N3300 8216 99
symloc 2N3301 8315 79
symloc 2N3302 8394 79
symloc 2N3304 8473 67
symloc 2N3390 8540 67
symloc 2N3391 8607 67
symloc 2N3391A 8674 68
symloc 2N3392 8742 67
symloc 2N3393 8809 67
symloc 2N3394 8876 67
symloc 2N3395 8943 67
symloc 2N3396 9010 67
symloc 2N3397 9077 67
symloc 2N3398 9144 67
symloc 2N3414 9211 67
symloc 2N3415 9278 67
symloc 2N3416 9345 67
symloc 2N3417 9412 67
symloc 2N3439 9479 70
symloc 2N3440 9549 70
symloc 2N3444 9619 96
symloc 2N3451 9715 97
symloc 2N3467 9812 70
symloc 2N3468 9882 70
symloc 2N3478 9952 103
symloc 2N3485 10055 79
symloc 2N3485A 10134 80
symloc 2N3486 10214 79
symloc 2N3486A 10293 80
symloc 2N3502 10373 78
symloc 2N3503 10451 78
symloc 2N3504 10529 79
symloc 2N3505 10608 79
symloc 2N3508 10687 79
symloc 2N3509 10766 79
symloc 2N3545 10845 97
symloc 2N3546 10942 70
symloc 2N3547 11012 79
symloc 2N3548 11091 79
symloc 2N3549 11170 79
symloc 2N3550 11249 79
symloc 2N3565 11328 79
symloc 2N3576 11407 67
symloc 2N3600 11474 103
symloc 2N3605 11577 67
symloc 2N3606 11644 67
symloc 2N3607 11711 67
symloc 2N3634 11778 67
symloc 2N3635 11845 67
symloc 2N3636 11912 67
symloc 2N3637 11979 67
symloc 2N3638 12046 79
symloc 2N3638A 12125 80
symloc 2N3639 12205 67
symloc 2N3640 12272 67
symloc 2N3641 12339 79
symloc 2N3642 12418 79
symloc 2N3643 12497 79
symloc 2N3644 12576 79
symloc 2N3645 12655 79
symloc 2N3646 12734 79
symloc 2N3678 12813 78
symloc 2N3691 12891 79
symloc 2N3692 12970 79
symloc 2N3693 13049 79
symloc 2N3694 13128 79
symloc 2N3700 13207 79
symloc 2N3702 13286 67
symloc 2N3703 13353 67
symloc 2N3707 13420 67
symloc 2N3708 13487 67
symloc 2N3709 13554 67
symloc 2N3710 13621 67
symloc 2N3711 13688 67
symloc 2N3721 13755 67
symloc 2N3724 13822 67
symloc 2N3724A 13889 68
symloc 2N3725 13957 67
symloc 2N3725A 14024 68
symloc 2N3734 14092 70
symloc 2N3735 14162 70
symloc 2N3736 14232 79
symloc 2N3737 14311 79
symloc 2N3742 14390 70
symloc 2N3762 14460 70
symloc 2N3763 14530 70
symloc 2N3799 14600 79
symloc 2N3827 14679 79
symloc 2N3858 14758 67
symloc 2N3858A 14825 68
symloc 2N3859 14893 67
symloc 2N3859A 14960 68
symloc 2N3860 15028 67
symloc 2N3866 15095 79
symloc 2N3877 15174 67
symloc 2N3877A 15241 68
symloc 2N3900 15309 67
symloc 2N3900A 15376 68
symloc 2N3901 15444 67
symloc 2N3903 15511 67
symloc 2N3904 15578 67
symloc 2N3905 15645 79
symloc 2N3906 15724 67
symloc 2N3932 15791 103
symloc 2N3933 15894 103
symloc 2N3946 15997 70
symloc 2N3947 16067 79
symloc 2N3959 16146 79
symloc 2N3960 16225 79
symloc 2N4013 16304 79
symloc 2N4014 16383 79
symloc 2N4047 16462 70
symloc 2N4058 16532 67
symloc 2N4059 16599 67
symloc 2N4061 16666 67
symloc 2N4062 16733 67
symloc 2N4121 16800 79
symloc 2N4122 16879 79
symloc 2N4123 16958 79
symloc 2N4124 17037 79
symloc 2N4125 17116 79
symloc 2N4126 17195 79
symloc 2N4140 17274 68
symloc 2N4141 17342 68
symloc 2N4142 17410 79
symloc 2N4143 17489 79
symloc 2N4208 17568 100
symloc 2N4209 17668 100
symloc 2N4234 17768 70
symloc 2N4235 17838 70
symloc 2N4236 17908 70
symloc 2N4248 17978 98
symloc 2N4249 18076 98
symloc 2N4250 18174 98
symloc 2N4250A 18272 80
symloc 2N4258 18352 68
symloc 2N4258A 18420 69
symloc 2N4259 18489 103
symloc 2N4260 18592 82
symloc 2N4261 18674 82
symloc 2N4274 18756 68
symloc 2N4275 18824 68
symloc 2N4286 18892 67
symloc 2N4287 18959 67
symloc 2N4288 19026 67
symloc 2N4289 19093 67
symloc 2N4290 19160 67
symloc 2N4291 19227 67
symloc 2N4294 19294 67
symloc 2N4295 19361 67
symloc 2N4354 19428 68
symloc 2N4355 19496 68
symloc 2N4356 19564 68
symloc 2N4384 19632 79
symloc 2N4386 19711 79
symloc 2N4400 19790 79
symloc 2N4401 19869 67
symloc 2N4402 19936 67
symloc 2N4403 20003 67
symloc 2N4404 20070 79
symloc 2N4405 20149 79
symloc 2N4406 20228 79
symloc 2N4407 20307 79
symloc 2N4409 20386 79
symloc 2N4410 20465 79
symloc 2N4424 20544 67
symloc 2N4916 20611 79
symloc 2N4917 20690 79
symloc 2N4964 20769 98
symloc 2N4965 20867 98
symloc 2N4966 20965 67
symloc 2N4967 21032 67
symloc 2N4968 21099 79
symloc 2N4969 21178 79
symloc 2N4970 21257 79
symloc 2N4971 21336 79
symloc 2N4972 21415 79
symloc 2N5022 21494 70
symloc 2N5023 21564 70
symloc 2N5030 21634 67
symloc 2N5056 21701 67
symloc 2N5057 21768 67
symloc 2N5058 21835 67
symloc 2N5059 21902 67
symloc 2N5086 21969 67
symloc 2N5087 22036 67
symloc 2N5088 22103 67
symloc 2N5089 22170 67
symloc 2N5109 22237 70
symloc 2N5127 22307 79
symloc 2N5128 22386 79
symloc 2N5129 22465 79
symloc 2N5131 22544 98
symloc 2N5132 22642 98
symloc 2N5133 22740 98
symloc 2N5134 22838 98
symloc 2N5135 22936 98
symloc 2N5136 23034 98
symloc 2N5137 23132 98
symloc 2N5138 23230 98
symloc 2N5139 23328 98
symloc 2N5140 23426 98
symloc 2N5142 23524 98
symloc 2N5143 23622 98
symloc 2N5172 23720 67
symloc 2N5179 23787 103
symloc 2N5180 23890 103
symloc 2N5189 23993 79
symloc 2N5209 24072 79
symloc 2N5210 24151 79
symloc 2N5219 24230 67
symloc 2N5221 24297 79
symloc 2N5223 24376 79
symloc 2N5224 24455 79
symloc 2N5226 24534 79
symloc 2N5227 24613 79
symloc 2N5232 24692 67
symloc 2N5232A 24759 68
symloc 2N5354 24827 67
symloc 2N5355 24894 67
symloc 2N5365 24961 67
symloc 2N5366 25028 67
symloc 2N5400 25095 67
symloc 2N5401 25162 67
symloc 2N5415 25229 70
symloc 2N5416 25299 70
symloc 2N5447 25369 67
symloc 2N5448 25436 79
symloc 2N5550 25515 67
symloc 2N5551 25582 67
symloc 2N5581 25649 79
symloc 2N5679 25728 70
symloc 2N5680 25798 70
symloc 2N5681 25868 70
symloc 2N5682 25938 70
symloc 2N5769 26008 79
symloc 2N5771 26087 79
symloc 2N5772 26166 79
symloc 2N5817 26245 67
symloc 2N5830 26312 67
symloc 2N5861 26379 70
symloc 2N5910 26449 67
symloc 2N6515 26516 79
symloc 2N6516 26595 79
symloc 2N6517 26674 79
symloc 2N6518 26753 79
symloc 2N6519 26832 79
symloc 2N6520 26911 79
symloc 2N6737 26990 80
symloc 40235 27070 81
symloc 40236 27151 81
symloc 40237 27232 81
symloc 40238 27313 81
symloc 40239 27394 81
symloc 40240 27475 81
symloc 40242 27556 81
symloc MM420 27637 78
symloc MM421 27715 78
symloc MM3905 27793 67
symloc MM3906 27860 67
symloc MM4001 27927 79
symloc MM4258 28006 67
symloc MM5262 28073 67
symloc MPS706 28140 67
symloc MPS834 28207 79
symloc MPS2222 28286 80
symloc MPS2369 28366 80
symloc MPS2711 28446 80
symloc MPS2712 28526 80
symloc MPS2713 28606 80
symloc MPS2714 28686 80
symloc MPS2716 28766 80
symloc MPS2907 28846 80
symloc MPS2923 28926 80
symloc MPS2924 29006 80
symloc MPS2925 29086 80
symloc MPS2926 29166 80
symloc MPS3392 29246 80
symloc MPS3393 29326 80
symloc MPS3394 29406 80
symloc MPS3395 29486 80
symloc MPS3396 29566 80
symloc MPS3397 29646 80
symloc MPS3398 29726 80
symloc MPS3638 29806 80
symloc MPS3638A 29886 81
symloc MPS3639 29967 80
symloc MPS3640 30047 80
symloc MPS3642 30127 80
symloc MPS3644 30207 80
symloc MPS3645 30287 80
symloc MPS3646 30367 80
symloc MPS3693 30447 80
symloc MPS3694 30527 80
symloc MPS3702 30607 80
symloc MPS3703 30687 80
symloc MPS3704 30767 80
symloc MPS3707 30847 80
symloc MPS3708 30927 80
symloc MPS3709 31007 80
symloc MPS3710 31087 80
symloc MPS3711 31167 80
symloc MPS3721 31247 80
symloc MPS3826 31327 80
symloc MPS3827 31407 80
symloc MPS3903 31487 80
symloc MPS3904 31567 80
symloc MPS3905 31647 80
symloc MPS3906 31727 80
symloc MPS4258 31807 80
symloc MPS4354 31887 80
symloc MPS4355 31967 80
symloc MPS4356 32047 80
symloc MPS5172 32127 80
symloc MPS6512 32207 80
symloc MPS6513 32287 80
symloc MPS6514 32367 80
symloc MPS6515 32447 80
symloc MPS6516 32527 80
symloc MPS6517 32607 80
symloc MPS6518 32687 80
symloc MPS6519 32767 80
symloc MPS6520 32847 80
symloc MPS6521 32927 80
symloc MPS6522 33007 80
symloc MPS6523 33087 80
symloc MPS6531 33167 80
symloc MPS6533 33247 80
symloc MPS6534 33327 80
symloc MPS6535 33407 80
symloc MPS6539 33487 68
symloc MPS6548 33555 68
symloc MPS6562 33623 80
symloc MPS6563 33703 80
symloc MPS6564 33783 80
symloc MPS6565 33863 80
symloc MPS6566 33943 80
symloc MPS6571 34023 80
symloc MPS6573 34103 80
symloc MPS6574 34183 80
symloc MPS6575 34263 80
symloc MPS6576 34343 80
symloc MPS6601 34423 80
symloc MPS6651 34503 80
symloc MPS6714 34583 80
symloc MPS6715 34663 80
symloc MPS6726 34743 80
symloc MPS6727 34823 80
symloc MPS6728 34903 80
symloc MPS6729 34983 80
symloc MPS6733 35063 69
symloc MPS6734 35132 69
symloc MPS6735 35201 69
symloc MPS8097 35270 80
symloc MPS8098 35350 80
symloc MPS8099 35430 80
symloc MPS8598 35510 80
symloc MPS8599 35590 80
symloc MPSA05 35670 67
symloc MPSA06 35737 67
symloc MPSA09 35804 79
symloc MPSA10 35883 79
symloc MPSA18 35962 79
symloc MPSA20 36041 79
symloc MPSA42 36120 67
symloc MPSA43 36187 67
symloc MPSA44 36254 79
symloc MPSA45 36333 79
symloc MPSA55 36412 67
symloc MPSA56 36479 67
symloc MPSA70 36546 67
symloc MPSA92 36613 79
symloc MPSA93 36692 79
symloc MPSH10 36771 67
symloc MPSL01 36838 79
symloc MPSL51 36917 79
symloc MPSW01 36996 79
symloc MPSW01A 37075 80
symloc MPSW10 37155 79
symloc MPSW42 37234 79
symloc MPSW43 37313 68
symloc MPSW51 37381 79
symloc MPSW51A 37460 80
symloc MPSW55 37540 79
symloc MPSW56 37619 79
symloc MPSW60 37698 79
symloc MPSW92 37777 79
symloc MPSW93 37856 79
symloc MRF501 37935 103
symloc MRF502 38038 103
symloc MRH30N 38141 82
symloc MRH30P 38223 82
symloc MRH80N 38305 82
symloc MRH80P 38387 82
symloc NS3762 38469 79
symloc NS3763 38548 79
symloc NS3903 38627 79
symloc NS3904 38706 79
symloc NS3905 38785 79
symloc NS3906 38864 79
symloc NS4234 38943 79
symloc PE4010 39022 79
symloc PE5025 39101 79
symloc PN930 39180 78
symloc PN2221 39258 79
symloc PN2221A 39337 80
symloc PN2222 39417 79
symloc PN2222A 39496 80
symloc PN2369 39576 79
symloc PN2369A 39655 80
symloc PN2484 39735 79
symloc PN2906 39814 79
symloc PN2906A 39893 80
symloc PN2907 39973 79
symloc PN2907A 40052 80
symloc PN3565 40132 79
symloc PN3638 40211 79
symloc PN3638A 40290 80
symloc PN3639 40370 79
symloc PN3640 40449 79
symloc PN3641 40528 79
symloc PN3642 40607 79
symloc PN3643 40686 79
symloc PN3644 40765 79
symloc PN3645 40844 79
symloc PN3646 40923 79
symloc PN3691 41002 79
symloc PN3692 41081 79
symloc PN3694 41160 79
symloc PN4121 41239 79
symloc PN4122 41318 79
symloc PN4140 41397 79
symloc PN4141 41476 79
symloc PN4142 41555 79
symloc PN4143 41634 79
symloc PN4248 41713 79
symloc PN4249 41792 79
symloc PN4250 41871 79
symloc PN4250A 41950 80
symloc PN4258 42030 79
symloc PN4258A 42109 80
symloc PN4274 42189 79
symloc PN4275 42268 79
symloc PN4354 42347 79
symloc PN4355 42426 79
symloc PN4356 42505 79
symloc PN4916 42584 79
symloc PN4917 42663 79
symloc PN5127 42742 79
symloc PN5128 42821 79
symloc PN5129 42900 79
symloc PN5131 42979 79
symloc PN5132 43058 79
symloc PN5133 43137 79
symloc PN5134 43216 79
symloc PN5135 43295 79
symloc PN5136 43374 79
symloc PN5137 43453 79
symloc PN5138 43532 79
symloc PN5139 43611 79
symloc PN5140 43690 79
symloc PN5142 43769 79
symloc PN5143 43848 79
symloc PN5179 43927 79
symloc PN5447 44006 79
symloc PN5910 44085 79
symloc ST3904 44164 79
symloc ST3906 44243 79
symloc ST5771-1 44322 81
symloc ST5771-2 44403 81
symloc TIS90 44484 66
symloc TIS91 44550 66
symloc TIS92 44616 66
symloc TIS93 44682 66
symloc TIS97 44748 66
symloc TIS98 44814 66
symloc TIS99 44880 66
symloc TN2218A 44946 81
symloc TN2219 45027 80
symloc TN2219A 45107 81
symloc TN2904A 45188 81
symloc TN2905 45269 80
symloc TN2905A 45349 81
symloc TN4036 45430 80
symloc TN4037 45510 80
symloc DH3467CD 45590 100
symloc DH3467CN 45690 99
symloc DH3725CD 45789 100
symloc DH3725CN 45889 99
symloc 2N3240 45988 66
*package 2N696
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N697
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N706
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N708
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
t TO-52
g 1
p E 1
p B 2
p C 3
*package 2N718
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N718A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N722
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N743
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N744
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N753
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N760
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N760A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N834
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N869
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N869A
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N914
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N915
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N916
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N929
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N929A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N930
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N956
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N995
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N995A
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N1132
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N1132A
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N1420
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N1566
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N1613
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N1711
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2193A
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2217
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N2218
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2218A
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2219
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2219A
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2220
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2221
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2221A
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2222
@types 1
g 1
@pinout
t TO-18,TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2222A
@types 1
g 1
@pinout
t TO-18,TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2270
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2282
@types 1
g 1
@attributes
@pinout
t TO-37
g 1
p E 1
p B 2
p C 3
*package 2N2369
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2369A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2484
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2509
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2510
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2511
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2586
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2604
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N2605
@types 1
g 1
@pinout
t TO-206AB
g 1
p E 1
p B 2
p C 3
*package 2N2696
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2712
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N2714
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N2857
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N2894
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2894A
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2897
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N2904
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2904A
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2905
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2905A
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N2906
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2906A
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2907
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2907A
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N2923
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N2924
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N2925
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N2926
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3009
@types 1
g 1
@attributes
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
*package 2N3011
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N3012
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3013
@types 1
g 1
@attributes
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
*package 2N3015
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3019
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3020
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3053
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3072
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3073
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3115
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3116
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3117
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3120
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3121
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3133
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3134
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3135
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3136
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3209
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3227
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3244
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3245
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3246
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3248
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3249
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3250
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3250A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3251
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3251A
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3252
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3253
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3299
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3300
@types 1
g 1
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3301
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3302
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3304
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
*package 2N3390
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3391
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3391A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3392
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3393
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3394
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3395
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3396
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3397
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3398
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3414
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3415
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3416
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3417
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3439
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3440
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3444
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3451
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3467
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3468
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3478
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N3485
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3485A
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3486
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3486A
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3502
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3503
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3504
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3505
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3508
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3509
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3545
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3546
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N3547
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3548
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3549
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3550
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3565
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3576
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3600
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N3605
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3606
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3607
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3634
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3635
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3636
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3637
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3638
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3638A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3639
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3640
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3641
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3642
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3643
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3644
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3645
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3646
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3678
@types 1
g 1
@attributes
@pinout
t TO-5
g 1
p E 1
p B 2
p C 3
*package 2N3691
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3692
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3693
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3694
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3700
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3702
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3703
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3707
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3708
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3709
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3710
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3711
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3721
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3724
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3724A
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3725
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3725A
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3734
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3735
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3736
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3737
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N3742
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3762
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3763
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N3799
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3827
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3858
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3858A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3859
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3859A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3860
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3866
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N3877
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3877A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3900
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3900A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3901
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N3903
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3904
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3905
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3906
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N3932
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N3933
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N3946
@types 1
g 1
@pinout
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N3947
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3959
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N3960
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N4013
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N4014
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N4047
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N4058
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4059
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4061
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4062
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4121
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4122
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4123
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4124
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4125
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4126
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4140
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4141
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4142
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4143
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4208
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N4209
@types 1
g 1
@pinout
t TO-52
g 1
p E 1
p B 2
p C 3
t TO-206AA
g 1
p E 1
p B 2
p C 3
*package 2N4234
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N4235
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N4236
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N4248
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4249
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4250
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4250A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4258
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4258A
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4259
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N4260
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 2N4261
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 2N4274
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4275
@types 1
g 1
@pinout
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4286
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4287
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4288
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4289
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4290
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4291
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4294
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4295
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4354
@types 1
g 1
@pinout
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N4355
@types 1
g 1
@pinout
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N4356
@types 1
g 1
@pinout
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N4384
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N4386
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N4400
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4401
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4402
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4403
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4404
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N4405
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N4406
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N4407
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N4409
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4410
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4424
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N4916
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4917
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4964
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4965
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N4966
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4967
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4968
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4969
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4970
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4971
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N4972
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5022
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5023
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5030
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5056
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N5057
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package 2N5058
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N5059
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N5086
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5087
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5088
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5089
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5109
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5127
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5128
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5129
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5131
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5132
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5133
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5134
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5135
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N5136
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N5137
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5138
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5139
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5140
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5142
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-105
g 1
p E 1
p B 2
p C 3
*package 2N5143
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
t TO-106
g 1
p E 1
p B 2
p C 3
*package 2N5172
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5179
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N5180
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package 2N5189
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package 2N5209
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5210
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5219
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5221
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5223
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5224
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5226
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5227
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5232
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5232A
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5354
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5355
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5365
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5366
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package 2N5400
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5401
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5415
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5416
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5447
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package 2N5448
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5550
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5551
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5581
@types 1
g 1
@attributes
@pinout
t TO-46
g 1
p E 1
p B 2
p C 3
*package 2N5679
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5680
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5681
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5682
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5769
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5771
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5772
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5817
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package 2N5830
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N5861
@types 1
g 1
@pinout
t TO-205AD
g 1
p E 1
p B 2
p C 3
*package 2N5910
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6515
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6516
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6517
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6518
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6519
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6520
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package 2N6737
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package 40235
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40236
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40237
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40238
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40239
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40240
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package 40242
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p E  1
p B  2
p C  3
*package MM420
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package MM421
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package MM3905
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package MM3906
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package MM4001
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package MM4258
@types 1
g 1
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package MM5262
@types 1
g 1
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package MPS706
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS834
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2222
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2369
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2711
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2712
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2713
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2714
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2716
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2907
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2923
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2924
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2925
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS2926
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3392
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3393
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3394
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3395
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3396
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3397
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3398
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3638
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3638A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3639
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3640
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3642
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3644
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3645
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3646
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3693
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3694
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3702
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3703
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3704
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3707
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3708
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3709
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3710
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3711
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3721
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3826
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3827
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3903
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3904
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3905
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS3906
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS4258
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS4354
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS4355
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS4356
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS5172
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6512
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6513
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6514
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6515
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6516
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6517
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6518
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6519
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6520
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6521
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6522
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6523
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6531
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6533
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6534
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6535
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6539
@types 1
g 1
@pinout
t TO-92
g 1
p E 2
p B 1
p C 3
*package MPS6548
@types 1
g 1
@pinout
t TO-92
g 1
p E 2
p B 1
p C 3
*package MPS6562
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6563
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6564
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6565
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6566
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6571
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6573
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6574
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6575
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6576
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6601
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6651
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6714
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6715
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6726
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6727
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6728
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6729
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS6733
@types 1
g 1
@pinout
t TO-226
g 1
p E 1
p B 2
p C 3
*package MPS6734
@types 1
g 1
@pinout
t TO-226
g 1
p E 1
p B 2
p C 3
*package MPS6735
@types 1
g 1
@pinout
t TO-226
g 1
p E 1
p B 2
p C 3
*package MPS8097
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS8098
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS8099
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS8598
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPS8599
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA05
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA06
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA09
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA10
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA18
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA20
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA42
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA43
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA44
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA45
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA55
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA56
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA70
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA92
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSA93
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSH10
@types 1
g 1
@pinout
t TO-92
g 1
p E 2
p B 1
p C 3
*package MPSL01
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSL51
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW01
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW01A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW10
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW42
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW43
@types 1
g 1
@pinout
t TO-226
g 1
p E 1
p B 2
p C 3
*package MPSW51
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW51A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW55
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW56
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW60
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW92
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MPSW93
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package MRF501
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package MRF502
@types 1
g 1
@pinout
t TO-72-28
g 1
p E 2
p B 1
p C 3
t TO-72-25
g 1
p E 1
p B 2
p C 3
*package MRH30N
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E  1
p B  2
p C  3
*package MRH30P
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E  1
p B  2
p C  3
*package MRH80N
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E  1
p B  2
p C  3
*package MRH80P
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E  1
p B  2
p C  3
*package NS3762
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package NS3763
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package NS3903
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package NS3904
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package NS3905
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package NS3906
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p E 1
p B 2
p C 3
*package NS4234
@types 1
g 1
@attributes
@pinout
t TO-39
g 1
p E 1
p B 2
p C 3
*package PE4010
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PE5025
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN930
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2221
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2221A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2222
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2222A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2369
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2369A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2484
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2906
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2906A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2907
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN2907A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3565
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3638
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3638A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3639
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3640
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3641
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3642
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3643
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3644
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3645
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3646
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3691
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3692
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN3694
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4121
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4122
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4140
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4141
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4142
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4143
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4248
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4249
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4250
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4250A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4258
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4258A
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4274
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4275
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4354
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4355
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4356
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4916
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN4917
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5127
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5128
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5129
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5131
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5132
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5133
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5134
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5135
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5136
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5137
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5138
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5139
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5140
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5142
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5143
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5179
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5447
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package PN5910
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package ST3904
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package ST3906
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package ST5771-1
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package ST5771-2
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p E 1
p B 2
p C 3
*package TIS90
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package TIS91
@types 1
g 1
@pinout
t TO-92
g 1
p E 1
p B 3
p C 2
*package TIS92
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package TIS93
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package TIS97
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package TIS98
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package TIS99
@types 1
g 1
@pinout
t TO-92
g 1
p E 3
p B 2
p C 1
*package TN2218A
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN2219
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN2219A
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN2904A
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN2905
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN2905A
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN4036
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package TN4037
@types 1
g 1
@attributes
@pinout
t TO-237
g 1
p E 1
p B 2
p C 3
*package DH3467CD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p b 2,6,9,13
p c 1,7,8,14
p e 3,5,10,12
*package DH3467CN
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p b 2,6,9,13
p c 1,7,8,14
p e 3,5,10,12
*package DH3725CD
@types 4
g 1 A,B,C,D
@pinout
t CDIP14
g 1
p b 2,6,9,13
p c 1,7,8,14
p e 3,5,10,12
*package DH3725CN
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p b 2,6,9,13
p c 1,7,8,14
p e 3,5,10,12
*package 2N3240
@types 1
g 1
@pinout
t TO-3
g 1
p b 1
p c 3
p e 2
