*version 6.2 524512895
@index
symloc MBM101474A-3 0 666
symloc MBM100422A-5 666 720
symloc MBM100470A-7 1386 228
symloc MBM100480A-8 1614 247
symloc MBM100484A-8 1861 294
symloc MBM100490-15 2155 445
symloc MBM100A484-5 2600 283
symloc MBM100C490-15 2883 265
symloc MBM100C494-15 3148 302
symloc MBM100C500-15/-17 3450 493
symloc MBM100C504-15-CFP28 3943 304
symloc MBM100C504-15-DIP32 4247 314
symloc MBM101C500-15 4561 489
symloc MBM10470A-7 5050 227
symloc MBM10480A-8 5277 243
symloc MBM10490-15/-25 5520 448
symloc MBM10494-7/-8 5968 537
symloc MBM10A474-3 6505 665
symloc MBM10A484-5 7170 282
symloc MBM10C490-15 7452 264
symloc MBM10C494-15 7716 301
symloc MBM10C500-15 8017 488
symloc MC10100 8505 254
symloc MC10101 8759 250
symloc MC10102 9009 357
symloc MC10103 9366 357
symloc MC10104 9723 357
symloc MC10105 10080 371
symloc MC10106 10451 341
symloc MC10107 10792 250
symloc MC10109 11042 355
symloc MC10110 11397 292
symloc MC10111 11689 292
symloc MC10113 11981 248
symloc MC10114 12229 262
symloc MC10115 12491 252
symloc MC10116 12743 262
symloc MC10117 13005 431
symloc MC10118 13436 427
symloc MC10119 13863 429
symloc MC10121 14292 431
symloc MC10123 14723 413
symloc MC10124 15136 407
symloc MC10125 15543 248
symloc MC10128 15791 213
symloc MC10129 16004 197
symloc MC10130 16201 345
symloc MC10131 16546 343
symloc MC10132 16889 196
symloc MC10133 17085 343
symloc MC10134 17428 351
symloc MC10135 17779 345
symloc MC10136 18124 359
symloc MC10137 18483 202
symloc MC10138 18685 335
symloc MC10141 19020 325
symloc MC10153 19345 343
symloc MC10154 19688 193
symloc MC10158 19881 321
symloc MC10159 20202 339
symloc MC10160 20541 355
symloc MC10161 20896 325
symloc MC10162 21221 325
symloc MC10164 21546 319
symloc MC10165 21865 321
symloc MC10166 22186 329
symloc MC10168 22515 339
symloc MC10170 22854 325
symloc MC10171 23179 345
symloc MC10172 23524 345
symloc MC10173 23869 345
symloc MC10174 24214 339
symloc MC10175 24553 337
symloc MC10176 24890 325
symloc MC10178 25215 341
symloc MC10181 25556 251
symloc MC10186 25807 325
symloc MC10188 26132 385
symloc MC10189 26517 385
symloc MC10190 26902 256
symloc MC10195 27158 321
symloc MC10197 27479 385
symloc MC10210 27864 292
symloc MC10211 28156 292
symloc MC10212 28448 292
symloc MC10216 28740 262
symloc MC10231 29002 343
symloc MC10566 29345 322
symloc MC10616 29667 255
symloc MC10H016 29922 336
symloc MC10H100 30258 237
symloc MC10H101 30495 237
symloc MC10H102 30732 368
symloc MC10H103 31100 356
symloc MC10H104 31456 356
symloc MC10H105 31812 372
symloc MC10H106 32184 354
symloc MC10H107 32538 251
symloc MC10H109 32789 356
symloc MC10H113 33145 249
symloc MC10H115 33394 249
symloc MC10H116 33643 279
symloc MC10H117 33922 432
symloc MC10H118 34354 428
symloc MC10H119 34782 430
symloc MC10H121 35212 432
symloc MC10H123 35644 414
symloc MC10H124 36058 408
symloc MC10H125 36466 245
symloc MC10H130 36711 346
symloc MC10H131 37057 344
symloc MC10H135 37401 346
symloc MC10H136 37747 360
symloc MC10H141 38107 326
symloc MC10H145 38433 326
symloc MC10H158 38759 338
symloc MC10H159 39097 372
symloc MC10H166 39469 330
symloc MC10H171 39799 362
symloc MC10H172 40161 362
symloc MC10H173 40523 354
symloc MC10H174 40877 320
symloc MC10H175 41197 338
symloc MC10H176 41535 326
symloc MC10H179 41861 332
symloc MC10H180 42193 370
symloc MC10H181 42563 469
symloc MC10H186 43032 326
symloc MC10H188 43358 386
symloc MC10H189 43744 386
symloc MC10H209 44130 410
symloc MC10H210 44540 321
symloc MC10H211 44861 321
symloc MC10H301 45182 402
symloc MC10H302 45584 402
symloc MC10H303 45986 380
symloc MC10H304 46366 361
symloc MC10H330 46727 516
symloc MC10H332 47243 241
symloc MC10H334 47484 247
symloc MC10H350 47731 412
symloc MC10H351 48143 259
symloc MC10H352 48402 260
symloc MC10H423 48662 408
symloc MC10H424 49070 408
symloc MC12002 49478 247
symloc MC12009 49725 220
symloc MC12011 49945 220
symloc MC12013 50165 220
symloc MC12014 50385 196
symloc MC12015 50581 146
symloc MC12015D 50727 136
symloc MC12015L 50863 138
symloc MC12015P 51001 137
symloc MC12016 51138 146
symloc MC12016D 51284 136
symloc MC12016L 51420 138
symloc MC12016P 51558 137
symloc MC12017 51695 146
symloc MC12017D 51841 136
symloc MC12017L 51977 138
symloc MC12017P 52115 137
symloc MC12018 52252 149
symloc MC12019 52401 124
symloc MC12022A 52525 111
symloc MC12022AD 52636 107
symloc MC12022AP 52743 105
symloc MC12022B 52848 111
symloc MC12022BD 52959 107
symloc MC12022BP 53066 108
symloc MC12023 53174 118
symloc MC12025 53292 110
symloc MC12040 53402 213
symloc MC12061 53615 230
symloc MC12073 53845 103
symloc MC12074 53948 103
symloc MC12090 54051 131
symloc MC1648 54182 309
symloc MC1650 54491 186
symloc MC1651 54677 186
symloc MC1658 54863 254
symloc MC1662 55117 137
symloc MC1692 55254 143
symloc MC4016 55397 187
symloc MC4018 55584 187
symloc MC4044 55771 166
symloc MC4316 55937 187
symloc MC4344 56124 166
symloc MCM10139 56290 191
symloc MCM10143 56481 266
symloc MCM10144 56747 192
symloc MCM10145 56939 180
symloc MCM10146 57119 185
symloc MCM10147 57304 185
symloc MCM10148 57489 176
*package MBM101474A-3 b
@types 1
g 1 
@pinout
t FPT-24C-C02
g 1
p A0 13
p A1 14
p A2 15
p A3 16
p A4 17
p A5 18
p A6 19
p A7 22
p A8 23
p DO1 7
p \CS\ 1
p \WE\ 2
p DI1 3
p VCC2 10
p VEE 21
p DO2 8
p DO3 11
p DO4 12
p DI2 4
p DI3 5
p DI4 6
p VCC1 9
p A9 24
t LCC24
g 1
p A0 4
p A1 5
p A2 6
p A3 7
p A4 8
p A5 9
p A6 11
p A7 13
p A8 14
p DO1 22
p \CS\ 17
p \WE\ 16
p DI1 18
p VCC2 1
p VEE 12
p DO2 23
p DO3 2
p DO4 3
p DI2 19
p DI3 20
p DI4 21
p VCC1 24
p A9 15
t CDIP24L
g 1
p A0 10
p A1 11
p A2 12
p A3 13
p A4 14
p A5 15
p A6 16
p A7 19
p A8 20
p DO1 4
p \CS\ 23
p \WE\ 22
p DI1 24
p VCC2 7
p VEE 18
p DO2 5
p DO3 8
p DO4 9
p DI2 1
p DI3 2
p DI4 3
p VCC1 6
p A9 21
*package MBM100422A-5 b
@types 1
g 1 
@pinout
t LCC24
g 1
p \WE\ 8
p A0 13
p A1 14
p A2 15
p A3 16
p A4 17
p A5 9
p A6 10
p A7 11
p DO1 2
p DO2 4
p DO3 21
p DO4 23
p DI1 6
p DI2 7
p DI3 18
p DI4 19
p \BS1\ 3
p \BS2\ 5
p \BS3\ 20
p \BS4\ 22
p VCC1 24
p VCC2 1
p VEE 12
t CDIP24L
g 1
p \WE\ 14
p A0 19
p A1 20
p A2 21
p A3 22
p A4 23
p A5 15
p A6 16
p A7 17
p DO1 8
p DO2 10
p DO3 3
p DO4 5
p DI1 12
p DI2 13
p DI3 24
p DI4 1
p \BS1\ 9
p \BS2\ 11
p \BS3\ 2
p \BS4\ 4
p VCC1 6
p VCC2 7
p VEE 18
t FPT-24C-C02
g 1
p \WE\ 17
p A0 22
p A1 23
p A2 24
p A3 1
p A4 2
p A5 18
p A6 19
p A7 20
p DO1 11
p DO2 13
p DO3 6
p DO4 8
p DI1 15
p DI2 16
p DI3 3
p DI4 4
p \BS1\ 12
p \BS2\ 14
p \BS3\ 5
p \BS4\ 7
p VCC1 9
p VCC2 10
p VEE 21
*package MBM100470A-7 b
@types 1
g 1 
@pinout
t CDIP18,FPT-18C-C01,LCC/R-18
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 10
p A8 11
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 16
p \WE\ 15
p D_IN 17
p VCC 18
p VEE 9
*package MBM100480A-8 b
@types 1
g 1 
@pinout
t CDIP20,LCC/R-20,CFP20-MO-018
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 11
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 18
p \WE\ 17
p D_IN 19
p VCC 20
p VEE 10
p A12 15
p A13 16
*package MBM100484A-8 b
@types 1
g 1 
@pinout
t CDIP28L,CFP28-MO-019
g 1
p A0 4
p A1 5
p A2 6
p A3 7
p A4 8
p A5 9
p A6 10
p A7 11
p A8 12
p A9 15
p A10 16
p A11 17
p DO1 26
p \CS\ 21
p \WE1\ 20
p DI1 22
p VCCA 1
p VEE 14
p DO2 27
p DO3 2
p DO4 3
p DI2 23
p DI3 24
p DI4 25
p VCC 28
p \WE2\ 19
*package MBM100490-15 b
@types 1
g 1 
@pinout
t FPT-22C-C01
g 1
p A0 19
p A1 20
p A2 21
p A3 22
p A4 1
p A5 2
p A6 3
p A7 4
p A8 5
p A9 7
p A10 8
p A11 9
p D_OUT 18
p \CS\ 15
p \WE\ 14
p D_IN 16
p VCC 17
p VEE 6
p A12 10
p A13 11
p A14 12
p A15 13
t CDIP22
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 20
p \WE\ 19
p D_IN 21
p VCC 22
p VEE 11
p A12 15
p A13 16
p A14 17
p A15 18
*package MBM100A484-5 b
@types 1
g 1 
@pinout
t CDIP28L,CFP28-MO-019
g 1
p A0 11
p A1 12
p A2 13
p A3 14
p A4 15
p A5 16
p A6 17
p A7 18
p A8 19
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VEE 21
p DO2 6
p DO3 9
p DO4 10
p DI2 2
p DI3 3
p DI4 4
p VCC1 7
p A9 22
p A10 23
p A11 24
p VCC2 8
*package MBM100C490-15 b
@types 1
g 1 
@pinout
t CDIP22,LCC/R-22,FPT-22C-C01
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 20
p \WE\ 19
p D_IN 21
p VCC 22
p VEE 11
p A12 15
p A13 16
p A14 17
p A15 18
*package MBM100C494-15 b
@types 1
g 1 
@pinout
t CDIP28L,CFP28-MO-019
g 1
p A0 11
p A1 12
p A2 13
p A3 14
p A4 15
p A5 16
p A6 17
p A7 18
p A8 19
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VCC2 8
p VEE 21
p DO2 6
p DO3 9
p DO4 10
p DI2 2
p DI3 3
p DI4 4
p VCC1 7
p A9 20
p A10 22
p A11 23
p A12 24
p A13 25
*package MBM100C500-15/-17 b
@types 1
g 1 
@pinout
t CFP24-MO-021
g 1
p A0 8
p A1 9
p A2 10
p A3 11
p A4 12
p A5 13
p A6 14
p A7 15
p A8 16
p A9 17
p A10 19
p A11 20
p D_OUT 7
p \CS\ 4
p \WE\ 3
p D_IN 5
p VCC 6
p VEE 18
p A12 21
p A13 22
p A14 23
p A15 24
p A16 1
p A17 2
t CDIP24,LCC24
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p A9 11
p A10 13
p A11 14
p D_OUT 1
p \CS\ 22
p \WE\ 21
p D_IN 23
p VCC 24
p VEE 12
p A12 15
p A13 16
p A14 17
p A15 18
p A16 19
p A17 20
*package MBM100C504-15-CFP28
@types 1
g 1
@pinout
t CFP28-MO-019
g 1
p A0 10
p A1 11
p A2 12
p A3 13
p A4 14
p A5 15
p A6 16
p A7 17
p A8 18
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VEE 21
p DO2 6
p DO3 8
p DO4 9
p DI2 2
p DI3 3
p DI4 4
p VCC 7
p A9 19
p A10 20
p A11 22
p A12 23
p A13 24
p A14 25
p A15 26
*package MBM100C504-15-DIP32 b
@types 1
g 1 
@pinout
t CDIP32X
g 1
p A0 12
p A1 13
p A2 14
p A3 15
p A4 16
p A5 17
p A6 18
p A7 19
p A8 20
p DO1 6
p \CS\ 32
p \WE\ 31
p DI1 2
p VCC2 9
p VEE 24
p DO2 7
p DO3 10
p DO4 11
p DI2 3
p DI3 4
p DI4 5
p VCC1 8
p A9 21
p A10 22
p A11 23
p A12 25
p A13 26
p A14 27
p A15 28
*package MBM101C500-15 b
@types 1
g 1 
@pinout
t CFP24-MO-019
g 1
p A0 8
p A1 9
p A2 10
p A3 11
p A4 12
p A5 13
p A6 14
p A7 15
p A8 16
p A9 17
p A10 19
p A11 20
p D_OUT 7
p \CS\ 4
p \WE\ 3
p D_IN 5
p VCC 6
p VEE 18
p A12 21
p A13 22
p A14 23
p A15 24
p A16 1
p A17 2
t CDIP24,LCC24
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p A9 11
p A10 13
p A11 14
p D_OUT 1
p \CS\ 22
p \WE\ 21
p D_IN 23
p VCC 24
p VEE 12
p A12 15
p A13 16
p A14 17
p A15 18
p A16 19
p A17 20
*package MBM10470A-7 b
@types 1
g 1 
@pinout
t CDIP18,LCC/R-18,FPT-18C-C01
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 10
p A8 11
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 16
p \WE\ 15
p D_IN 17
p VCC 18
p VEE 9
*package MBM10480A-8 b
@types 1
g 1 
@pinout
t CDIP20,LCC20,CFP20-MO-018
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 11
p A9 12
p A10 13
p A11 14
p D_OUT 1
p \CS\ 18
p \WE\ 17
p D_IN 19
p VCC 20
p VEE 10
p A12 15
p A13 16
*package MBM10490-15/-25 b
@types 1
g 1 
@pinout
t FPT-22C-C01
g 1
p A0 19
p A1 20
p A2 21
p A3 22
p A4 1
p A5 2
p A6 3
p A7 4
p A8 5
p D_OUT 18
p \CS\ 15
p \WE\ 14
p VEE 6
p VCC 17
p A9 7
p A10 8
p A11 9
p A12 10
p A13 11
p A14 12
p A15 13
p D_IN 16
t CDIP22
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p D_OUT 1
p \CS\ 20
p \WE\ 19
p VEE 11
p VCC 22
p A9 12
p A10 13
p A11 14
p A12 15
p A13 16
p A14 17
p A15 18
p D_IN 21
*package MBM10494-7/-8 b
@types 1
g 1 
@pinout
t CFP28-MO-019
g 1
p A0 18
p A1 17
p A2 16
p A3 15
p A4 14
p A5 13
p A6 12
p A7 11
p A8 10
p DO1 24
p \CS\ 1
p \WE\ 2
p DI1 28
p VEE 8
p DO2 23
p DO3 20
p DO4 19
p DI2 27
p DI3 26
p DI4 25
p VCC1 22
p A9 9
p VCC2 21
p A10 7
p A11 6
p A12 5
p A13 4
t CDIP28L
g 1
p A0 11
p A1 12
p A2 13
p A3 14
p A4 15
p A5 16
p A6 17
p A7 18
p A8 19
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VEE 21
p DO2 6
p DO3 9
p DO4 10
p DI2 2
p DI3 3
p DI4 4
p VCC1 7
p A9 20
p VCC2 8
p A10 22
p A11 23
p A12 24
p A13 25
*package MBM10A474-3 b
@types 1
g 1 
@pinout
t LCC24
g 1
p A0 4
p A1 5
p A2 6
p A3 7
p A4 8
p A5 9
p A6 11
p A7 13
p A8 14
p DO1 22
p \CS\ 17
p \WE\ 16
p DI1 18
p VEE 12
p DO2 23
p DO3 2
p DO4 3
p DI2 19
p DI3 20
p DI4 21
p VCC1 1
p A9 15
p VCC2 24
t FPT-24C-C02
g 1
p A0 13
p A1 14
p A2 15
p A3 16
p A4 17
p A5 18
p A6 19
p A7 22
p A8 23
p DO1 7
p \CS\ 1
p \WE\ 2
p DI1 3
p VEE 21
p DO2 8
p DO3 11
p DO4 12
p DI2 4
p DI3 5
p DI4 6
p VCC1 9
p A9 24
p VCC2 10
t CDIP24L
g 1
p A0 10
p A1 11
p A2 12
p A3 13
p A4 14
p A5 15
p A6 16
p A7 19
p A8 20
p DO1 4
p \CS\ 23
p \WE\ 22
p DI1 24
p VEE 18
p DO2 5
p DO3 8
p DO4 9
p DI2 1
p DI3 2
p DI4 3
p VCC1 6
p A9 21
p VCC2 7
*package MBM10A484-5 b
@types 1
g 1 
@pinout
t CDIP28L,CFP28-MO-019
g 1
p A0 11
p A1 12
p A2 13
p A3 14
p A4 15
p A5 16
p A6 17
p A7 18
p A8 19
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VEE 21
p DO2 6
p DO3 9
p DO4 10
p DI2 2
p DI3 3
p DI4 4
p VCC1 7
p A9 22
p VCC2 8
p A10 23
p A11 24
*package MBM10C490-15 b
@types 1
g 1 
@pinout
t CDIP22,LCC/R-22,FPT-22C-C01
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p D_OUT 1
p \CS\ 20
p \WE\ 19
p VEE 11
p VCC 22
p A9 12
p A10 13
p A11 14
p A12 15
p A13 16
p A14 17
p A15 18
p D_IN 21
*package MBM10C494-15 b
@types 1
g 1 
@pinout
t CDIP28L,CFP28-MO-019
g 1
p A0 11
p A1 12
p A2 13
p A3 14
p A4 15
p A5 16
p A6 17
p A7 18
p A8 19
p DO1 5
p \CS\ 28
p \WE\ 27
p DI1 1
p VEE 21
p DO2 6
p DO3 9
p DO4 10
p DI2 2
p DI3 3
p DI4 4
p VCC1 7
p A9 20
p VCC2 8
p A10 22
p A11 23
p A12 24
p A13 25
*package MBM10C500-15 b
@types 1
g 1 
@pinout
t CFP24-MO-021
g 1
p A0 8
p A1 9
p A2 10
p A3 11
p A4 12
p A5 13
p A6 14
p A7 15
p A8 16
p D_OUT 7
p \CS\ 4
p \WE\ 3
p VEE 18
p VCC 6
p A9 17
p A10 19
p A11 20
p A12 21
p A13 22
p A14 23
p A15 24
p D_IN 5
p A16 1
p A17 2
t CDIP24,LCC24
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 8
p A7 9
p A8 10
p D_OUT 1
p \CS\ 22
p \WE\ 21
p VEE 12
p VCC 24
p A9 11
p A10 13
p A11 14
p A12 15
p A13 16
p A14 17
p A15 18
p D_IN 23
p A16 19
p A17 20
*package MC10100 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p IN0 4,6,10,12
p IN1 5,7,11,13
p OUT 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s STROBE 9
t PLCC20
g 1
p IN0 5,8,13,15
p IN1 7,9,14,17
p OUT 3,4,18,19
s VCC1 2
s VCC2 20
s VEE 10
s STROBE 12
*package MC10101 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p IN 4,7,10,13
p \OUT\ 2,3,14,15
p OUT 5,6,11,9
s VCC1 1
s VCC2 16
s VEE 8
s COM 12
t PLCC20
g 1
p IN 5,9,13,17
p \OUT\ 3,4,18,19
p OUT 7,8,14,12
s VCC1 2
s VCC2 20
s VEE 10
s COM 15
*package MC10102 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A_OUT 2
p VCC1 1
p VEE 8
p B1 6
p B2 7
p B_OUT 3
p C1 10
p C2 11
p C_OUT 14
p D1 12
p D2 13
p \D_OUT\ 15
p D_OUT 9
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p A_OUT 3
p VCC1 2
p VEE 10
p B1 8
p B2 9
p B_OUT 4
p C1 13
p C2 14
p C_OUT 18
p D1 15
p D2 17
p \D_OUT\ 19
p D_OUT 12
p VCC2 20
*package MC10103 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A_OUT 2
p VCC1 1
p VEE 8
p B1 6
p B2 7
p B_OUT 3
p C1 10
p C2 11
p C_OUT 14
p D1 12
p D2 13
p \D_OUT\ 9
p D_OUT 15
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p A_OUT 3
p VCC1 2
p VEE 10
p B1 8
p B2 9
p B_OUT 4
p C1 13
p C2 14
p C_OUT 18
p D1 15
p D2 17
p \D_OUT\ 12
p D_OUT 19
p VCC2 20
*package MC10104 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A_OUT 2
p VCC1 1
p VEE 8
p B1 6
p B2 7
p B_OUT 3
p C1 10
p C2 11
p C_OUT 14
p D1 12
p D2 13
p \D_OUT\ 9
p D_OUT 15
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p A_OUT 3
p VCC1 2
p VEE 10
p B1 8
p B2 9
p B_OUT 4
p C1 13
p C2 14
p C_OUT 18
p D1 15
p D2 17
p \D_OUT\ 12
p D_OUT 19
p VCC2 20
*package MC10105 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p VCC1 1
p VEE 8
p C1 13
p C2 12
p \C_OUT\ 14
p C_OUT 15
p VCC2 16
p \B_OUT\ 6
p B_OUT 7
p \A_OUT\ 3
p A_OUT 2
p B1 9
p B3 11
p A1 4
p A2 5
p B2 10
t PLCC20
g 1
p VCC1 2
p VEE 10
p C1 17
p C2 15
p \C_OUT\ 18
p C_OUT 19
p VCC2 20
p \B_OUT\ 8
p B_OUT 9
p \A_OUT\ 4
p A_OUT 3
p B1 12
p B3 14
p A1 5
p A2 7
p B2 13
*package MC10106 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A2 5
p A1 4
p A3 6
p A_OUT 3
p B1 9
p B2 10
p B3 11
p B_OUT 2
p C1 12
p C2 13
p C3 14
p C_OUT 15
p A4 7
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A2 7
p A1 5
p A3 8
p A_OUT 4
p B1 12
p B2 13
p B3 14
p B_OUT 3
p C1 15
p C2 17
p C3 18
p C_OUT 19
p A4 9
p VCC1 2
p VCC2 20
p VEE 10
*package MC10107 b
@types 3
g 1 A,B,C
@pinout
t DIP16,CDIP16
g 1
p A1 4,9,14
p A2 5,7,15
p \A_OUT\ 2,11,12
p A_OUT 3,10,13
s VCC1 1
s VCC2 16
s VEE 8
t PLCC20
g 1
p A1 5,12,18
p A2 7,9,19
p \A_OUT\ 3,14,15
p A_OUT 4,13,17
s VCC1 2
s VCC2 20
s VEE 10
*package MC10109 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A3 6
p A4 7
p B1 9
p B2 10
p B3 11
p B4 12
p B5 13
p \A_OUT\ 3
p A_OUT 2
p \B_OUT\ 14
p B_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A1 5
p A2 7
p A3 8
p A4 9
p B1 12
p B2 13
p B3 14
p B4 15
p B5 17
p \A_OUT\ 4
p A_OUT 3
p \B_OUT\ 18
p B_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10110 b
@types 2
g 1 A,B
@pinout
t DIP16,CDIP16
g 1
p OUT0 2,12
p OUT1 3,13
p OUT2 4,14
p IN0 5,9
p IN1 6,10
p IN2 7,11
s VCC10 1
s VCC11 15
s VCC2 16
s VEE 8
t PLCC20
g 1
p OUT0 3,15
p OUT1 4,17
p OUT2 5,18
p IN0 7,12
p IN1 8,13
p IN2 9,14
s VCC10 2
s VCC11 19
s VCC2 20
s VEE 10
*package MC10111 b
@types 2
g 1 A,B
@pinout
t DIP16,CDIP16
g 1
p OUT0 2,12
p OUT1 3,13
p OUT2 4,14
p IN0 5,9
p IN1 6,10
p IN2 7,11
s VCC10 1
s VCC11 15
s VCC2 16
s VEE 8
t PLCC20
g 1
p OUT0 3,15
p OUT1 4,17
p OUT2 5,18
p IN0 7,12
p IN1 8,13
p IN2 9,14
s VCC10 2
s VCC11 19
s VCC2 20
s VEE 10
*package MC10113 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p A1 4,6,10,12
p A2 5,7,11,13
p A_OUT 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s \E\ 9
t PLCC20
g 1
p A1 5,8,13,15
p A2 7,9,14,17
p A_OUT 3,4,18,19
s VCC1 2
s VCC2 20
s VEE 10
s \E\ 12
*package MC10114 b
@types 3
g 1 A,B,C
@pinout
t DIP16,CDIP16
g 1
p \IN\ 4,9,12
p \OUT\ 2,6,14
p OUT 3,7,15
p IN 5,10,13
s VCC1 1
s VCC2 16
s VEE 8
s VBB 11
t PLCC20
g 1
p \IN\ 5,12,15
p \OUT\ 3,8,18
p OUT 4,9,19
p IN 7,13,17
s VCC1 2
s VCC2 20
s VEE 10
s VBB 14
*package MC10115 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p \A1\ 4,7,10,13
p A2 5,6,11,12
p A_OUT 2,3,14,15
s VCC1 1
s VCC2 16
s VBB 9
s VEE 8
t PLCC20
g 1
p \A1\ 5,9,13,17
p A2 7,8,14,15
p A_OUT 3,4,18,19
s VCC1 2
s VCC2 20
s VBB 12
s VEE 10
*package MC10116 b
@types 3
g 1 A,B,C
@pinout
t DIP16,CDIP16
g 1
p \IN\ 4,9,12
p \OUT\ 2,6,14
p OUT 3,7,15
p IN 5,10,13
s VCC1 1
s VCC2 16
s VBB 11
s VEE 8
t PLCC20
g 1
p \IN\ 5,12,15
p \OUT\ 3,8,18
p OUT 4,9,19
p IN 7,13,17
s VCC1 2
s VCC2 20
s VBB 14
s VEE 10
*package MC10117 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 6
p A2_IN1 7
p A2,B2_IN 9
p B1_IN0 10
p B1_IN1 11
p B2_IN0 12
p B2_IN1 13
p \A_OUT\ 3
p A_OUT 2
p \B_OUT\ 14
p B_OUT 15
p VCC2 16
p VCC1 1
p VEE 8
t PLCC20
g 1
p A1_IN0 5
p A1_IN1 7
p A2_IN0 8
p A2_IN1 9
p A2,B2_IN 12
p B1_IN0 13
p B1_IN1 14
p B2_IN0 15
p B2_IN1 17
p \A_OUT\ 4
p A_OUT 3
p \B_OUT\ 18
p B_OUT 19
p VCC2 20
p VCC1 2
p VEE 10
*package MC10118 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 3
p A1_IN1 4
p A2_IN0 6
p A2_IN1 7
p A2,B2_IN 9
p B1_IN0 10
p B1_IN1 11
p B2_IN0 12
p B2_IN1 13
p A_OUT 2
p B_OUT 15
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 5
p B2_IN2 14
t PLCC20
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 8
p A2_IN1 9
p A2,B2_IN 12
p B1_IN0 13
p B1_IN1 14
p B2_IN0 15
p B2_IN1 17
p A_OUT 3
p B_OUT 19
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 7
p B2_IN2 18
*package MC10119 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 3
p A1_IN1 4
p A2_IN0 7
p A2_IN1 9
p A2,B3_IN 10
p A3_IN0 11
p A3_IN1 12
p A4_IN0 13
p A4_IN1 14
p A_OUT 2
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 5
p A4_IN2 15
p A1_IN3 6
t PLCC20
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 9
p A2_IN1 12
p A2,B3_IN 13
p A3_IN0 14
p A3_IN1 15
p A4_IN0 17
p A4_IN1 18
p A_OUT 3
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 7
p A4_IN2 19
p A1_IN3 8
*package MC10121 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 7
p A2_IN1 9
p A2,A3_IN 10
p A3_IN0 11
p A3_IN1 12
p A4_IN0 13
p A4_IN1 14
p A_OUT 2
p \A_OUT\ 3
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 6
p A4_IN2 15
t PLCC20
g 1
p A1_IN0 5
p A1_IN1 7
p A2_IN0 9
p A2_IN1 12
p A2,A3_IN 13
p A3_IN0 14
p A3_IN1 15
p A4_IN0 17
p A4_IN1 18
p A_OUT 3
p \A_OUT\ 4
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 8
p A4_IN2 19
*package MC10123 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 6
p A_IN3 7
p B_IN0 9
p B_IN1 10
p B_IN2 11
p C_IN0 12
p C_IN1 13
p C_IN2 14
p \A_OUT\ 3
p \B_OUT\ 2
p \C_OUT\ 15
p VCC2 16
p VCC1 1
p VEE 8
t PLCC20
g 1
p A_IN0 5
p A_IN1 7
p A_IN2 8
p A_IN3 9
p B_IN0 12
p B_IN1 13
p B_IN2 14
p C_IN0 15
p C_IN1 17
p C_IN2 18
p \A_OUT\ 4
p \B_OUT\ 3
p \C_OUT\ 19
p VCC2 20
p VCC1 2
p VEE 10
*package MC10124 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN 5
p STROBE 6
p B_IN 7
p C_IN 10
p D_IN 11
p \A_OUT\ 4
p A_OUT 2
p \B_OUT\ 3
p B_OUT 1
p \C_OUT\ 12
p C_OUT 15
p \D_OUT\ 13
p D_OUT 14
p VCC 9
p GND 16
p VEE 8
t PLCC20
g 1
p A_IN 7
p STROBE 8
p B_IN 9
p C_IN 13
p D_IN 14
p \A_OUT\ 5
p A_OUT 3
p \B_OUT\ 4
p B_OUT 2
p \C_OUT\ 15
p C_OUT 19
p \D_OUT\ 17
p D_OUT 18
p VCC 12
p GND 20
p VEE 10
*package MC10125 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p \A0\ 2,6,10,14
p A1 3,7,11,15
p A_OUT 4,5,12,13
s VCC 9
s VEE 8
s GND 16
s VBB 1
t PLCC20
g 1
p \A0\ 3,8,13,18
p A1 4,9,14,19
p A_OUT 5,7,15,17
s VCC 12
s VEE 10
s GND 20
s VBB 2
*package MC10128 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D1 11
p D2 6
p CLK 10
p RES 7
p DISABLE1 12
p DISABLE2 5
p \STROBE\ 3
p CTRL1 13
p CTRL2 4
p Q1 15
p Q2 2
p GND1 16
p GND2 1
p GND3 9
p VEE 8
p VCC 14
*package MC10129 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D0 7
p D1 13
p D2 6
p D3 4
p HYS_CTRL 5
p CLK 11
p RES 10
p STROBE 12
p Q0 14
p Q1 15
p Q2 3
p Q3 2
p VCC 9
p GND0 1
p GND1 16
p VEE 8
*package MC10130 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p D1 7
p \CE1\ 6
p R1 4
p \C\ 9
p R2 13
p \CE2\ 11
p D2 10
p S2 12
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p D1 9
p \CE1\ 8
p R1 5
p \C\ 12
p R2 17
p \CE2\ 14
p D2 13
p S2 15
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10131 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p D1 7
p \CE1\ 6
p R1 4
p CC 9
p R2 13
p \CE2\ 11
p D2 10
p S2 12
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p D1 9
p \CE1\ 8
p R1 5
p CC 12
p R2 17
p \CE2\ 14
p D2 13
p S2 15
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10132 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A 11
p D11 4
p D12 5
p \CE0\ 10
p \CE2\ 9
p CC 7
p R 6
p D21 13
p D22 12
p Q1 2
p \Q1\ 3
p Q2 15
p \Q2\ 14
p VCC1 1
p VCC2 16
p VEE 8
*package MC10133 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D0 3
p \G0\ 5
p D1 7
p \CE0\ 4
p CC 13
p \CE1\ 12
p D2 9
p \G1\ 10
p D3 14
p Q0 2
p Q1 6
p Q2 11
p Q3 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p D0 4
p \G0\ 7
p D1 9
p \CE0\ 5
p CC 17
p \CE1\ 15
p D2 12
p \G1\ 13
p D3 18
p Q0 3
p Q1 8
p Q2 14
p Q3 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10134 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A0 6
p A1 11
p D11 4
p D12 5
p \CE0\ 10
p CC 7
p \CE1\ 9
p D21 13
p D22 12
p Q1 2
p \Q1\ 3
p Q2 15
p \Q2\ 14
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A0 8
p A1 14
p D11 5
p D12 7
p \CE0\ 13
p CC 9
p \CE1\ 12
p D21 17
p D22 15
p Q1 3
p \Q1\ 4
p Q2 19
p \Q2\ 18
p VCC1 2
p VCC2 20
p VEE 10
*package MC10135 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p \J1\ 7
p \K1\ 6
p R1 4
p C 9
p S2 12
p \J2\ 10
p \K2\ 11
p R2 13
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p \J1\ 9
p \K1\ 8
p R1 5
p C 12
p S2 15
p \J2\ 13
p \K2\ 14
p R2 17
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10136 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 9
p S2 7
p \CARRY_IN\ 10
p CLK 13
p DO 12
p D1 11
p D2 6
p D3 5
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p \CARRY-OUT\ 4
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 12
p S2 9
p \CARRY_IN\ 13
p CLK 17
p DO 15
p D1 14
p D2 8
p D3 7
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p \CARRY-OUT\ 5
p VCC1 2
p VCC2 20
p VEE 10
*package MC10137 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 9
p S2 7
p \CARRY_IN\ 10
p CLK 13
p DO 12
p D1 11
p D2 6
p D3 5
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p \CARRY-OUT\ 4
p VCC1 1
p VCC2 16
p VEE 8
*package MC10138 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p CLK 12
p RES 9
p C2 7
p S0 11
p S1 10
p S2 6
p S3 5
p Q0 15
p \Q0\ 14
p Q1 13
p Q2 4
p Q3 2
p \Q3\ 3
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p CLK 15
p RES 12
p C2 9
p S0 14
p S1 13
p S2 8
p S3 7
p Q0 19
p \Q0\ 18
p Q1 17
p Q2 5
p Q3 3
p \Q3\ 4
p VCC1 2
p VCC2 20
p VEE 10
*package MC10141 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 10
p S2 7
p DR 5
p CLK 4
p DO 12
p D1 11
p D2 9
p D3 6
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p VCC1 1
p VCC2 16
p VEE 8
p DL 13
t PLCC20
g 1
p S1 13
p S2 9
p DR 7
p CLK 5
p DO 15
p D1 14
p D2 12
p D3 8
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p VCC1 2
p VCC2 20
p VEE 10
p DL 17
*package MC10153 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D0 3
p \G0\ 5
p D1 7
p \CE0\ 4
p CC 13
p \CE1\ 12
p D2 9
p \G1\ 10
p D3 14
p Q0 2
p Q1 6
p Q2 11
p Q3 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p D0 4
p \G0\ 7
p D1 9
p \CE0\ 5
p CC 17
p \CE1\ 15
p D2 12
p \G1\ 13
p D3 18
p Q0 3
p Q1 8
p Q2 14
p Q3 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10154 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p CLK1 12
p RES 9
p CLK2 10
p S0 11
p S1 7
p S2 6
p S3 5
p Q0 15
p \Q0\ 14
p Q1 13
p Q2 4
p Q3 2
p \Q3\ 3
p VCC1 1
p VCC2 16
p VEE 8
*package MC10158 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D01 5
p D00 6
p D11 3
p D10 4
p D21 12
p D20 13
p D31 10
p D30 11
p Q0 1
p Q1 2
p Q2 15
p Q3 14
p VCC 16
p VEE 8
p SEL 9
t PLCC20
g 1
p D01 7
p D00 8
p D11 4
p D10 5
p D21 15
p D20 17
p D31 13
p D30 14
p Q0 2
p Q1 3
p Q2 19
p Q3 18
p VCC 20
p VEE 10
p SEL 12
*package MC10159 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D01 5
p D00 6
p D11 3
p D10 4
p D21 12
p D20 13
p D31 10
p D30 11
p Q0 1
p Q1 2
p Q2 15
p Q3 14
p VCC 16
p VEE 8
p SEL 9
p \EN\ 7
t PLCC20
g 1
p D01 7
p D00 8
p D11 4
p D10 5
p D21 15
p D20 17
p D31 13
p D30 14
p Q0 2
p Q1 3
p Q2 19
p Q3 18
p VCC 20
p VEE 10
p SEL 12
p \EN\ 9
*package MC10160 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p IN1 3
p IN2 4
p OUT 2
p IN3 5
p IN4 6
p IN5 7
p IN6 9
p IN7 10
p IN8 11
p IN9 12
p IN10 13
p IN11 14
p IN12 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p IN1 4
p IN2 5
p OUT 3
p IN3 7
p IN4 8
p IN5 9
p IN6 12
p IN7 13
p IN8 14
p IN9 15
p IN10 17
p IN11 18
p IN12 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10161 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \E0\ 2
p \E1\ 15
p A 7
p B 9
p C 14
p Q0 6
p Q1 5
p Q2 4
p Q3 3
p Q4 13
p Q5 12
p Q6 11
p Q7 10
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p \E0\ 3
p \E1\ 19
p A 9
p B 12
p C 18
p Q0 8
p Q1 7
p Q2 5
p Q3 4
p Q4 17
p Q5 15
p Q6 14
p Q7 13
p VCC1 2
p VCC2 20
p VEE 10
*package MC10162 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \E0\ 2
p \E1\ 15
p A 7
p B 9
p C 14
p Q0 6
p Q1 5
p Q2 4
p Q3 3
p Q4 13
p Q5 12
p Q6 11
p Q7 10
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p \E0\ 3
p \E1\ 19
p A 9
p B 12
p C 18
p Q0 8
p Q1 7
p Q2 5
p Q3 4
p Q4 17
p Q5 15
p Q6 14
p Q7 13
p VCC1 2
p VCC2 20
p VEE 10
*package MC10164 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A 7
p B 9
p C 10
p \EN\ 2
p X0 6
p X1 5
p X2 4
p X3 3
p X4 11
p X5 12
p X6 13
p X7 14
p Z 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A 9
p B 12
p C 13
p \EN\ 3
p X0 8
p X1 7
p X2 5
p X3 4
p X4 14
p X5 15
p X6 17
p X7 18
p Z 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10165 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p C 4
p D0 5
p D1 7
p D2 13
p D3 10
p D4 11
p D5 12
p D6 9
p D7 6
p Q0 3
p Q1 2
p Q2 15
p Q3 14
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p C 5
p D0 7
p D1 9
p D2 17
p D3 13
p D4 14
p D5 15
p D6 12
p D7 8
p Q0 4
p Q1 3
p Q2 19
p Q3 18
p VCC1 2
p VCC2 20
p VEE 10
*package MC10166 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A4 9
p B4 10
p A3 12
p B3 11
p A2 13
p B2 14
p A1 6
p B1 7
p A0 5
p B0 4
p \E\ 15
p A>B 2
p A<B 3
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A4 12
p B4 13
p A3 15
p B3 14
p A2 17
p B2 18
p A1 8
p B1 9
p A0 7
p B0 5
p \E\ 19
p A>B 3
p A<B 4
p VCC1 2
p VCC2 20
p VEE 10
*package MC10168 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D0 3
p \G0\ 5
p D1 7
p \G2\ 12
p CC 13
p \G3\ 10
p D2 9
p \G1\ 4
p D3 14
p Q0 2
p Q1 6
p Q2 11
p Q3 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p D0 4
p \G0\ 7
p D1 9
p \G2\ 15
p CC 17
p \G3\ 13
p D2 12
p \G1\ 5
p D3 18
p Q0 3
p Q1 8
p Q2 14
p Q3 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10170 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p HIGH 13
p LOW 14
p D0 3
p D1 4
p D2 5
p D3 6
p D4 7
p D5 9
p D6 10
p A 2
p B 15
p VCC1 1
p VCC2 16
p VEE 8
p D7 11
p D8 12
t PLCC20
g 1
p HIGH 17
p LOW 18
p D0 4
p D1 5
p D2 7
p D3 8
p D4 9
p D5 12
p D6 13
p A 3
p B 19
p VCC1 2
p VCC2 20
p VEE 10
p D7 14
p D8 15
*package MC10171 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \E0\ 14
p A 9
p B 7
p \E\ 15
p \E1\ 2
p Q03 10
p Q02 11
p Q01 12
p Q00 13
p Q13 3
p Q12 4
p Q11 5
p Q10 6
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p \E0\ 18
p A 12
p B 9
p \E\ 19
p \E1\ 3
p Q03 13
p Q02 14
p Q01 15
p Q00 17
p Q13 4
p Q12 5
p Q11 7
p Q10 8
p VCC1 2
p VCC2 20
p VEE 10
*package MC10172 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p \E0\ 18
p A 12
p B 9
p \E\ 19
p \E1\ 3
p Q03 13
p Q02 14
p Q01 15
p Q00 17
p Q13 4
p Q12 5
p Q11 7
p Q10 8
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p \E0\ 14
p A 9
p B 7
p \E\ 15
p \E1\ 2
p Q03 10
p Q02 11
p Q01 12
p Q00 13
p Q13 3
p Q12 4
p Q11 5
p Q10 6
p VCC1 1
p VCC2 16
p VEE 8
*package MC10173 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p \SEL\ 12
p D00 8
p D01 7
p D10 5
p D11 4
p D20 17
p D21 15
p D30 14
p D31 13
p \CLK\ 9
p Q0 2
p Q1 3
p Q2 19
p Q3 18
p VCC 20
p VEE 10
t DIP16,CDIP16
g 1
p \SEL\ 9
p D00 6
p D01 5
p D10 4
p D11 3
p D20 13
p D21 12
p D30 11
p D31 10
p \CLK\ 7
p Q0 1
p Q1 2
p Q2 15
p Q3 14
p VCC 16
p VEE 8
*package MC10174 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p D00 4
p D01 7
p D02 5
p D03 8
p A 9
p B 12
p \EN\ 18
p D10 17
p D11 14
p D12 15
p D13 13
p Q0 3
p Q1 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p D00 3
p D01 5
p D02 4
p D03 6
p A 7
p B 9
p \EN\ 14
p D10 13
p D11 11
p D12 12
p D13 10
p Q0 2
p Q1 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10175 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p D0 13
p D1 15
p D2 17
p D3 12
p D4 7
p \C0\ 8
p \C1\ 9
p RESET 14
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p Q4 5
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p D0 10
p D1 12
p D2 13
p D3 9
p D4 5
p \C0\ 6
p \C1\ 7
p RESET 11
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p Q4 4
p VCC1 1
p VCC2 16
p VEE 8
*package MC10176 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p D0 7
p D1 8
p D2 9
p D3 13
p D4 14
p CLK 12
p Q0 3
p Q1 4
p Q2 5
p Q3 17
p Q4 18
p VCC1 2
p VCC2 20
p VEE 10
p D5 15
p Q5 19
t DIP16,CDIP16
g 1
p D0 5
p D1 6
p D2 7
p D3 10
p D4 11
p CLK 9
p Q0 2
p Q1 3
p Q2 4
p Q3 13
p Q4 14
p VCC1 1
p VCC2 16
p VEE 8
p D5 12
p Q5 15
*package MC10178 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p CLK1 15
p RES 12
p CLK2 13
p S0 14
p S1 9
p S2 8
p S3 7
p Q0 19
p \Q0\ 18
p Q1 17
p Q2 5
p Q3 3
p \Q3\ 4
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p CLK1 12
p RES 9
p CLK2 10
p S0 11
p S1 7
p S2 6
p S3 5
p Q0 15
p \Q0\ 14
p Q1 13
p Q2 4
p Q3 2
p \Q3\ 3
p VCC1 1
p VCC2 16
p VEE 8
*package MC10181 b
@types 1
g 1 
@pinout
t DIP24X,CDIP24X
g 1
p A0 21
p A1 18
p A2 16
p A3 10
p B0 20
p B1 19
p B2 11
p B3 9
p CN 22
p M 23
p S0 14
p S1 17
p S2 15
p S3 13
p F0 2
p F1 3
p F2 7
p F3 6
p GG 4
p PG 8
p CN+4 5
p VCC1 1
p VCC2 24
p VEE 12
*package MC10186 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p D0 7
p D1 8
p D2 9
p D3 13
p D4 14
p CLK 12
p Q0 3
p Q1 4
p Q2 5
p Q3 17
p Q4 18
p VCC 20
p VEE 10
p RESET 2
p D5 15
p Q5 19
t DIP16,CDIP16
g 1
p D0 5
p D1 6
p D2 7
p D3 10
p D4 11
p CLK 9
p Q0 2
p Q1 3
p Q2 4
p Q3 13
p Q4 14
p VCC 16
p VEE 8
p RESET 1
p D5 12
p Q5 15
*package MC10188 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN 7
p B_IN 8
p C_IN 9
p D_IN 13
p E_IN 14
p F_IN 15
p A_OUT 3
p B_OUT 4
p C_OUT 5
p D_OUT 17
p E_OUT 18
p F_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
p COM 12
t DIP16,CDIP16
g 1
p A_OUT 2
p B_OUT 3
p C_OUT 4
p D_OUT 13
p E_OUT 14
p F_OUT 15
p A_IN 5
p B_IN 6
p C_IN 7
p D_IN 10
p E_IN 11
p F_IN 12
p VCC1 1
p VCC2 16
p VEE 8
p COM 9
*package MC10189 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN 7
p B_IN 8
p C_IN 9
p D_IN 13
p E_IN 14
p F_IN 15
p A_OUT 3
p B_OUT 4
p C_OUT 5
p D_OUT 17
p E_OUT 18
p F_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
p COM 12
t DIP16,CDIP16
g 1
p A_OUT 2
p B_OUT 3
p C_OUT 4
p D_OUT 13
p E_OUT 14
p F_OUT 15
p A_IN 5
p B_IN 6
p C_IN 7
p D_IN 10
p E_IN 11
p F_IN 12
p VCC1 1
p VCC2 16
p VEE 8
p COM 9
*package MC10190 b
@types 4
g 1 A,B,C,D
@pinout
t PLCC20
g 1
p \IN\ 5,9,13,17
p IN 7,8,14,15
p OUT 3,4,18,19
s VCC1 2
s VCC2 20
s VEE 10
s VSS/VCC 12
t DIP16,CDIP16
g 1
p \IN\ 4,7,10,13
p IN 5,6,11,12
p OUT 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s VSS/VCC 9
*package MC10195 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A 12
p B1 7
p B2 8
p B3 9
p B4 13
p B5 14
p B6 15
p Q1 3
p Q2 4
p Q3 5
p Q4 17
p Q5 18
p Q6 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p A 9
p B1 5
p B2 6
p B3 7
p B4 10
p B5 11
p B6 12
p Q1 2
p Q2 3
p Q3 4
p Q4 13
p Q5 14
p Q6 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10197 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p COM 12
p A_IN 7
p B_IN 8
p C_IN 9
p D_IN 13
p E_IN 14
p F_IN 15
p A_OUT 3
p B_OUT 4
p C_OUT 5
p D_OUT 17
p E_OUT 18
p F_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p COM 9
p A_IN 5
p B_IN 6
p C_IN 7
p D_IN 10
p E_IN 11
p F_IN 12
p A_OUT 2
p B_OUT 3
p C_OUT 4
p D_OUT 13
p E_OUT 14
p F_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10210 b
@types 2
g 1 A,B
@pinout
t PLCC20
g 1
p OUT0 3,15
p OUT1 4,17
p OUT2 5,18
p IN0 7,12
p IN1 8,13
p IN2 9,14
s VCC10 2
s VCC11 19
s VCC2 20
s VEE 10
t DIP16,CDIP16
g 1
p OUT0 2,12
p OUT1 3,13
p OUT2 4,14
p IN0 5,9
p IN1 6,10
p IN2 7,11
s VCC10 1
s VCC11 15
s VCC2 16
s VEE 8
*package MC10211 b
@types 2
g 1 A,B
@pinout
t PLCC20
g 1
p OUT0 3,15
p OUT1 4,17
p OUT2 5,18
p IN0 7,12
p IN1 8,13
p IN2 9,14
s VCC10 2
s VCC11 19
s VCC2 20
s VEE 10
t DIP16,CDIP16
g 1
p OUT0 2,12
p OUT1 3,13
p OUT2 4,14
p IN0 5,9
p IN1 6,10
p IN2 7,11
s VCC10 1
s VCC11 15
s VCC2 16
s VEE 8
*package MC10212 b
@types 2
g 1 A,B
@pinout
t PLCC20
g 1
p OUT0 5,15
p OUT1 4,17
p OUT2 3,18
p IN0 7,12
p IN1 8,13
p IN2 9,14
s VCC10 2
s VCC11 19
s VEE 10
s VCC2 20
t DIP16,CDIP16
g 1
p OUT0 4,12
p OUT1 3,13
p OUT2 2,14
p IN0 5,9
p IN1 6,10
p IN2 7,11
s VCC10 1
s VCC11 15
s VEE 8
s VCC2 16
*package MC10216 b
@types 3
g 1 A,B,C
@pinout
t PLCC20
g 1
p \IN\ 5,12,15
p \OUT\ 3,8,18
p OUT 4,9,19
p IN 7,13,17
s VCC1 2
s VCC2 20
s VEE 10
s VBB 14
t DIP16,CDIP16
g 1
p \IN\ 4,9,12
p \OUT\ 2,6,14
p OUT 3,7,15
p IN 5,10,13
s VCC1 1
s VCC2 16
s VEE 8
s VBB 11
*package MC10231 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p S1 7
p D1 9
p \CE1\ 8
p R1 5
p CC 12
p R2 17
p \CE2\ 14
p D2 13
p S2 15
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p S1 5
p D1 7
p \CE1\ 6
p R1 4
p CC 9
p R2 13
p \CE2\ 11
p D2 10
p S2 12
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10566 b
@types 1
g 1 
@pinout
t LCC20
g 1
p A0 7
p A1 8
p A2 17
p A3 15
p A4 12
p B0 5
p B1 9
p B2 18
p B3 14
p B4 13
p \E\ 19
p A>B 3
p A<B 4
p VCC1 2
p VCC2 20
p VEE 10
t CDIP16
g 1
p A0 5
p A1 6
p A2 13
p A3 12
p A4 9
p B0 4
p B1 7
p B2 14
p B3 11
p B4 10
p \E\ 15
p A>B 2
p A<B 3
p VCC1 1
p VCC2 16
p VEE 8
*package MC10616 b
@types 3
g 1 A,B,C
@pinout
t LCC20
g 1
p \IN\ 5,12,15
p \OUT\ 3,8,18
p OUT 4,9,19
p IN 7,13,17
s VCC1 2
s VCC2 20
s VEE 10
s VBB 14
t CDIP16
g 1
p \IN\ 4,9,12
p \OUT\ 2,6,14
p OUT 3,7,15
p IN 5,10,13
s VCC1 1
s VCC2 16
s VEE 8
s VBB 11
*package MC10H016 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p P0 9
p P1 12
p P2 13
p P3 14
p \PE\ 7
p \CE\ 8
p CP 17
p MR 15
p Q0 4
p Q1 3
p Q2 19
p Q3 18
p \TC\ 5
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p P0 7
p P1 9
p P2 10
p P3 11
p \PE\ 5
p \CE\ 6
p CP 13
p MR 12
p Q0 3
p Q1 2
p Q2 15
p Q3 14
p \TC\ 4
p VCC1 1
p VCC2 16
p VEE 8
*package MC10H100 b
@types 4
g 1 A,B,C,D
@pinout
t PLCC20
g 1
p A 5,8,13,15
p B 7,9,14,17
p Y 3,4,18,19
s VEE 10
s COM 11
s VCC1 2
s VCC2 20
t DIP16,CDIP16
g 1
p A 4,6,10,12
p B 5,7,11,13
p Y 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s COM 9
*package MC10H101 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p A 4,7,10,13
p X 5,6,11,9
p Y 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s COM 12
t PLCC20
g 1
p A 5,9,13,17
p X 7,8,14,12
p Y 3,4,18,19
s VCC1 2
s VCC2 20
s VEE 10
s COM 15
*package MC10H102 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p \A_OUT\ 2
p VCC1 1
p VEE 8
p B1 6
p B 7
p \B_OUT\ 3
p C1 10
p C2 11
p \C_OUT\ 14
p D1 12
p D2 13
p \D_OUT\ 15
p D_OUT 9
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p \A_OUT\ 3
p VCC1 2
p VEE 10
p B1 8
p B 9
p \B_OUT\ 4
p C1 13
p C2 14
p \C_OUT\ 18
p D1 15
p D2 17
p \D_OUT\ 19
p D_OUT 12
p VCC2 20
*package MC10H103 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A_OUT 2
p VCC1 1
p VEE 8
p B1 6
p B 7
p B_OUT 3
p C1 10
p C2 11
p C_OUT 14
p D1 12
p D2 13
p \C_OUT\ 9
p D_OUT 15
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p A_OUT 3
p VCC1 2
p VEE 10
p B1 8
p B 9
p B_OUT 4
p C1 13
p C2 14
p C_OUT 18
p D1 15
p D2 17
p \C_OUT\ 12
p D_OUT 19
p VCC2 20
*package MC10H104 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A_OUT 2
p VCC1 1
p VEE 8
p B1 6
p B 7
p B_OUT 3
p C1 10
p C2 11
p C_OUT 14
p D1 12
p D2 13
p \D_OUT\ 9
p D_OUT 15
p VCC2 16
t PLCC20
g 1
p A1 5
p A2 7
p A_OUT 3
p VCC1 2
p VEE 10
p B1 8
p B 9
p B_OUT 4
p C1 13
p C2 14
p C_OUT 18
p D1 15
p D2 17
p \D_OUT\ 12
p D_OUT 19
p VCC2 20
*package MC10H105 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p VCC1 1
p VEE 8
p C1 13
p C2 12
p \C_OUT\ 14
p C_OUT 15
p VCC2 16
p \B_OUT\ 6
p B_OUT 7
p \A_OUT\ 3
p A_OUT 2
p B1 9
p B3 11
p A1 4
p A2 5
p B2 10
t PLCC20
g 1
p VCC1 2
p VEE 10
p C1 17
p C2 15
p \C_OUT\ 18
p C_OUT 19
p VCC2 20
p \B_OUT\ 8
p B_OUT 9
p \A_OUT\ 4
p A_OUT 3
p B1 12
p B3 14
p A1 5
p A2 7
p B2 13
*package MC10H106 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A2 5
p A1 4
p A3 6
p \A_OUT\ 3
p B1 9
p B2 10
p B3 11
p \B_OUT\ 2
p C1 12
p C2 13
p C3 14
p \C_OUT\ 15
p A4 7
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A2 7
p A1 5
p A3 8
p \A_OUT\ 4
p B1 12
p B2 13
p B3 14
p \B_OUT\ 3
p C1 15
p C2 17
p C3 18
p \C_OUT\ 19
p A4 9
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H107 b
@types 3
g 1 A,B,C
@pinout
t PLCC20
g 1
p A1 5,12,18
p A2 7,9,19
p \A_OUT\ 3,14,15
p A_OUT 4,13,17
s VCC1 2
s VCC2 20
s VEE 10
t DIP16,CDIP16
g 1
p A1 4,9,14
p A2 5,7,15
p \A_OUT\ 2,11,12
p A_OUT 3,10,13
s VCC1 1
s VCC2 16
s VEE 8
*package MC10H109 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1 4
p A2 5
p A3 6
p A4 7
p B1 9
p B2 10
p B3 11
p B4 12
p B5 13
p \A_OUT\ 3
p A_OUT 2
p \B_OUT\ 14
p B_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A1 5
p A2 7
p A3 8
p A4 9
p B1 12
p B2 13
p B3 14
p B4 15
p B5 17
p \A_OUT\ 4
p A_OUT 3
p \B_OUT\ 18
p B_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H113 b
@types 4
g 1 A,B,C,D
@pinout
t PLCC20
g 1
p A1 5,8,13,15
p A2 7,9,14,17
p A_OUT 3,4,18,19
s VCC1 2
s VCC2 20
s VEE 10
s \E\ 12
t DIP16,CDIP16
g 1
p A1 4,6,10,12
p A2 5,7,11,13
p A_OUT 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
s \E\ 9
*package MC10H115 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p A1 4,7,10,13
p A2 5,6,11,12
p A_OUT 2,3,14,15
s VBB 9
s VCC1 1
s VCC2 16
s VEE 8
t PLCC20
g 1
p A1 5,9,13,17
p A2 7,8,14,15
p A_OUT 3,4,18,19
s VBB 12
s VCC1 2
s VCC2 20
s VEE 10
*package MC10H116 b
@types 3
g 1 A,B,C
@pinout
t DIP16,CDIP16
g 1
p \A_IN\ 4,9,12
p \A_OUT\ 2,6,14
p A_OUT 3,7,15
p A_IN 5,10,13
s VCC1 1
s VCC2 16
s VBB 11
s VEE 8
t PLCC20
g 1
p \A_IN\ 5,12,15
p A_IN 7,13,17
p \A_OUT\ 3,8,18
p A_OUT 4,9,19
s VCC1 2
s VCC2 20
s VBB 14
s VEE 10
*package MC10H117 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 6
p A2_IN1 7
p A2,B2_IN 9
p B1_IN0 10
p B1_IN1 11
p B2_IN0 12
p B2_IN1 13
p \A_OUT\ 3
p A_OUT 2
p \B_OUT\ 14
p B_OUT 15
p VCC2 16
p VCC1 1
p VEE 8
t PLCC20
g 1
p A1_IN0 5
p A1_IN1 7
p A2_IN0 8
p A2_IN1 9
p A2,B2_IN 12
p B1_IN0 13
p B1_IN1 14
p B2_IN0 15
p B2_IN1 17
p \A_OUT\ 4
p A_OUT 3
p \B_OUT\ 18
p B_OUT 19
p VCC2 20
p VCC1 2
p VEE 10
*package MC10H118 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 3
p A1_IN1 4
p A2_IN0 6
p A2_IN1 7
p A2,B2_IN 9
p B1_IN0 10
p B1_IN1 11
p B2_IN0 12
p B2_IN1 13
p A_OUT 2
p B_OUT 15
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 5
p B2_IN2 14
t PLCC20
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 8
p A2_IN1 9
p A2,B2_IN 12
p B1_IN0 13
p B1_IN1 14
p B2_IN0 15
p B2_IN1 17
p A_OUT 3
p B_OUT 19
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 7
p B2_IN2 18
*package MC10H119 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 3
p A1_IN1 4
p A2_IN0 7
p A2_IN1 9
p A2,A3_IN 10
p A3_IN0 11
p A3_IN1 12
p A4_IN0 13
p A4_IN1 14
p A_OUT 2
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 5
p A4_IN2 15
p A1_IN3 6
t PLCC20
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 9
p A2_IN1 12
p A2,A3_IN 13
p A3_IN0 14
p A3_IN1 15
p A4_IN0 17
p A4_IN1 18
p A_OUT 3
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 7
p A4_IN2 19
p A1_IN3 8
*package MC10H121 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A1_IN0 4
p A1_IN1 5
p A2_IN0 7
p A2_IN1 9
p A2,A3_IN 10
p A3_IN0 11
p A3_IN1 12
p A4_IN0 13
p A4_IN1 14
p A_OUT 2
p \A_OUT\ 3
p VCC2 16
p VCC1 1
p VEE 8
p A1_IN2 6
p A4_IN2 15
t PLCC20
g 1
p A1_IN0 5
p A1_IN1 7
p A2_IN0 9
p A2_IN1 12
p A2,A3_IN 13
p A3_IN0 14
p A3_IN1 15
p A4_IN0 17
p A4_IN1 18
p A_OUT 3
p \A_OUT\ 4
p VCC2 20
p VCC1 2
p VEE 10
p A1_IN2 8
p A4_IN2 19
*package MC10H123 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 6
p A_IN3 7
p B_IN0 9
p B_IN1 10
p B_IN2 11
p C_IN0 12
p C_IN1 13
p C_IN2 14
p \A_OUT\ 3
p \B_OUT\ 2
p \C_OUT\ 15
p VCC2 16
p VCC1 1
p VEE 8
t PLCC20
g 1
p A_IN0 5
p A_IN1 7
p A_IN2 8
p A_IN3 9
p B_IN0 12
p B_IN1 13
p B_IN2 14
p C_IN0 15
p C_IN1 17
p C_IN2 18
p \A_OUT\ 4
p \B_OUT\ 3
p \C_OUT\ 19
p VCC2 20
p VCC1 2
p VEE 10
*package MC10H124 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN 5
p STROBE 6
p B_IN 7
p C_IN 10
p D_IN 11
p \A_OUT\ 4
p A_OUT 2
p \B_OUT\ 3
p B_OUT 1
p \C_OUT\ 12
p C_OUT 15
p \D_OUT\ 13
p D_OUT 14
p VCC 9
p GND 16
p VEE 8
t PLCC20
g 1
p A_IN 7
p STROBE 8
p B_IN 9
p C_IN 13
p D_IN 14
p \A_OUT\ 5
p A_OUT 3
p \B_OUT\ 4
p B_OUT 2
p \C_OUT\ 15
p C_OUT 19
p \D_OUT\ 17
p D_OUT 18
p VCC 12
p GND 20
p VEE 10
*package MC10H125 b
@types 4
g 1 A,B,C,D
@pinout
t DIP16,CDIP16
g 1
p A0 2,6,10,14
p A1 3,7,11,15
p A_OUT 4,5,12,13
s VCC 9
s VBB 1
s GND 16
s VEE 8
t PLCC20
g 1
p A0 3,8,13,18
p A1 4,9,14,19
p A_OUT 5,7,15,17
s VCC 12
s VBB 2
s GND 20
s VEE 10
*package MC10H130 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p D1 7
p \CE1\ 6
p R1 4
p \C\ 9
p R2 13
p \CE2\ 11
p D2 10
p S2 12
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p D1 9
p \CE1\ 8
p R1 5
p \C\ 12
p R2 17
p \CE2\ 14
p D2 13
p S2 15
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H131 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p D1 7
p \CE1\ 6
p R1 4
p CC 9
p R2 13
p \CE2\ 11
p D2 10
p S2 12
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p D1 9
p \CE1\ 8
p R1 5
p CC 12
p R2 17
p \CE2\ 14
p D2 13
p S2 15
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H135 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 5
p \J1\ 7
p \K1\ 6
p R1 4
p C 9
p S2 12
p \J2\ 10
p \K2\ 11
p R2 13
p Q1 2
p \Q1\ 3
p \Q2\ 14
p Q2 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 7
p \J1\ 9
p \K1\ 8
p R1 5
p C 12
p S2 15
p \J2\ 13
p \K2\ 14
p R2 17
p Q1 3
p \Q1\ 4
p \Q2\ 18
p Q2 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H136 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 9
p S2 7
p \CARRY_IN\ 10
p CLK 13
p DO 12
p D1 11
p D2 6
p D3 5
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p \CARRY-OUT\ 4
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p S1 12
p S2 9
p \CARRY_IN\ 13
p CLK 17
p DO 15
p D1 14
p D2 8
p D3 7
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p \CARRY-OUT\ 5
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H141 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p S1 10
p S2 7
p DR 5
p CLK 4
p DO 12
p D1 11
p D2 9
p D3 6
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p VCC1 1
p VCC2 16
p VEE 8
p DL 13
t PLCC20
g 1
p S1 13
p S2 9
p DR 7
p CLK 5
p DO 15
p D1 14
p D2 12
p D3 8
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p VCC1 2
p VCC2 20
p VEE 10
p DL 17
*package MC10H145 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A0 10
p A1 9
p A2 7
p \WE\ 13
p DO 5
p D1 4
p D2 11
p D3 12
p Q0 2
p Q1 1
p Q2 15
p Q3 14
p VCC 16
p VEE 8
p A3 6
p \CS\ 3
t PLCC20
g 1
p A0 13
p A1 12
p A2 9
p \WE\ 17
p DO 7
p D1 5
p D2 14
p D3 15
p Q0 3
p Q1 2
p Q2 19
p Q3 18
p VCC 20
p VEE 10
p A3 8
p \CS\ 4
*package MC10H158 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p SEL 9
p D0_1 5
p D0_0 6
p D1_1 3
p D1_0 4
p D2_1 12
p D2_0 13
p D3_1 10
p D3_0 11
p Q0 1
p Q1 2
p Q2 15
p Q3 14
p VCC 16
p VEE 8
t PLCC20
g 1
p SEL 12
p D0_1 7
p D0_0 8
p D1_0 5
p D1_1 4
p D2_1 15
p D2_0 17
p D3_1 13
p D3_0 14
p Q0 2
p Q1 3
p Q2 19
p Q3 18
p VCC 20
p VEE 10
*package MC10H159 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \EN\ 7
p SEL 9
p D0_1 5
p D0_0 6
p D1_1 3
p D1_0 4
p D2_1 12
p D2_0 13
p D3_1 10
p D3_0 11
p \Q0\ 1
p \Q1\ 2
p \Q2\ 15
p \Q3\ 14
p VCC 16
p VEE 8
t PLCC20
g 1
p SEL 12
p D0_1 7
p D0_0 8
p D1_0 5
p \EN\ 9
p D1_1 4
p D2_1 15
p D2_0 17
p D3_1 13
p D3_0 14
p \Q0\ 2
p \Q1\ 3
p \Q2\ 19
p \Q3\ 18
p VCC 20
p VEE 10
*package MC10H166 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A4 9
p B4 10
p A3 12
p B3 11
p A2 13
p B2 14
p A1 6
p B1 7
p A0 5
p B0 4
p \E\ 15
p A>B 2
p A<B 3
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A4 12
p B4 13
p A3 15
p B3 14
p A2 17
p B2 18
p A1 8
p B1 9
p A0 7
p B0 5
p \E\ 19
p A>B 3
p A<B 4
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H171 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \E0\ 14
p A 9
p B 7
p \E\ 15
p \E1\ 2
p Q0_3 10
p Q0_2 11
p Q0_1 12
p Q0_0 13
p Q1_3 3
p Q1_2 4
p Q1_1 5
p Q1_0 6
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p \E0\ 18
p A 12
p B 9
p \E1\ 3
p Q0_3 13
p Q0_2 14
p Q0_1 15
p Q0_0 17
p Q1_3 4
p Q1_2 5
p Q1_1 7
p Q1_0 8
p VCC1 2
p VCC2 20
p VEE 10
p \E\ 19
*package MC10H172 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p \E0\ 14
p A 9
p B 7
p \E\ 15
p \E1\ 2
p Q0_3 10
p Q0_2 11
p Q0_1 12
p Q0_0 13
p Q1_3 3
p Q1_2 4
p Q1_1 5
p Q1_0 6
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p \E0\ 18
p A 12
p B 9
p \E\ 19
p \E1\ 3
p Q0_3 13
p Q0_2 14
p Q0_1 15
p Q0_0 17
p Q1_3 4
p Q1_2 5
p Q1_1 7
p Q1_0 8
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H173 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p SEL 9
p D0_1 5
p D0_0 6
p D1_1 3
p D1_0 4
p D2_1 12
p D2_0 13
p D3_1 10
p D3_0 11
p Q0 1
p Q1 2
p Q2 15
p Q3 14
p VCC 16
p VEE 8
p CLK 7
t PLCC20
g 1
p SEL 12
p D0_1 7
p D0_0 8
p D1_1 4
p D1_0 5
p D2_1 15
p D2_0 17
p D3_1 13
p D3_0 14
p Q0 2
p Q1 3
p Q2 19
p Q3 18
p VCC 20
p VEE 10
p CLK 9
*package MC10H174 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p X0 3
p X1 5
p X2 4
p X3 6
p A 7
p B 9
p \EN\ 14
p Y0 13
p Y1 11
p Y2 12
p Y3 10
p Z 2
p W 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p X0 4
p X1 6
p X2 5
p X3 8
p A 9
p B 12
p \EN\ 18
p Y0 17
p Y1 14
p Y2 15
p Y3 13
p Z 3
p W 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H175 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p RESET 11
p D0 10
p D1 12
p D2 13
p D3 9
p D4 5
p \C0\ 6
p \C1\ 7
p Q0 14
p Q1 15
p Q2 2
p Q3 3
p VCC1 1
p VEE 8
p Q4 4
p VCC2 16
t PLCC20
g 1
p RESET 14
p D0 13
p D1 15
p D2 17
p D3 12
p D4 7
p \C0\ 8
p \C1\ 9
p Q0 18
p Q1 19
p Q2 3
p Q3 4
p VCC1 2
p VEE 10
p Q4 5
p VCC2 20
*package MC10H176 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p D0 7
p D1 8
p D2 9
p D3 13
p D4 14
p CLK 12
p Q0 3
p Q1 4
p Q2 5
p Q3 17
p Q4 18
p VCC1 2
p VCC2 20
p VEE 10
p D5 15
p Q5 19
t DIP16,CDIP16
g 1
p D0 5
p D1 6
p D2 7
p D3 10
p D4 11
p CLK 9
p Q0 2
p Q1 3
p Q2 4
p Q3 13
p Q4 14
p VCC1 1
p VCC2 16
p VEE 8
p D5 12
p Q5 15
*package MC10H179 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p G3 5
p G2 9
p G1 7
p G0 4
p CN 11
p GG 2
p PG 15
p CN+2 6
p CN+4 3
p VCC1 1
p VCC2 16
p VEE 8
p P3 13
p P2 12
p P1 10
p P0 14
t PLCC20
g 1
p G3 7
p G2 12
p G1 9
p G0 5
p CN 14
p GG 3
p PG 19
p CN+2 8
p CN+4 4
p VCC1 2
p VCC2 20
p VEE 10
p P3 17
p P2 15
p P1 13
p P0 18
*package MC10H180 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p SEL_A0 7
p SEL_B0 9
p A0 5
p B0 6
p S0 15
p \S0\ 2
p C_OUT0 3
p S1 14
p \S1\ 1
p VCC 16
p VEE 8
p A1 11
p B1 10
p C_IN0 4
p C_IN1 12
p C_OUT1 13
t PLCC20
g 1
p SEL_A0 9
p SEL_B0 12
p A0 7
p B0 8
p S0 19
p \S0\ 3
p C_OUT0 4
p S1 18
p \S1\ 2
p VCC 20
p VEE 10
p A1 14
p B1 13
p C_IN0 5
p C_IN1 15
p C_OUT1 17
*package MC10H181 b
@types 1
g 1 
@pinout
t PLCC28
g 1
p A0 25
p A1 21
p A2 19
p A3 12
p B0 24
p B1 23
p B2 13
p B3 11
p CN 26
p M 27
p S0 17
p S1 20
p S2 18
p S3 16
p F0 3
p F1 4
p F2 9
p F3 7
p GG 5
p PG 10
p CN+4 6
p VCC1 2
p VCC2 28
p VEE 14
t DIP24,DIP24X,CDIP24,CDIP24X
g 1
p A0 21
p A1 18
p A2 16
p A3 10
p B0 20
p B1 19
p B2 11
p B3 9
p CN 22
p M 23
p S0 14
p S1 17
p S2 15
p S3 13
p F0 2
p F1 3
p F2 7
p F3 6
p GG 4
p PG 8
p CN+4 5
p VCC1 1
p VCC2 24
p VEE 12
*package MC10H186 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p D0 5
p D1 6
p D2 7
p D3 10
p D4 11
p CLK 9
p Q0 2
p Q1 3
p Q2 4
p Q3 13
p Q4 14
p VCC 16
p VEE 8
p RESET 1
p D5 12
p Q5 15
t PLCC20
g 1
p D0 7
p D1 8
p D2 9
p D3 13
p D4 14
p CLK 12
p Q0 3
p Q1 4
p Q2 5
p Q3 17
p Q4 18
p VCC 20
p VEE 10
p RESET 2
p D5 15
p Q5 19
*package MC10H188 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p COM 9
p A_IN 5
p B_IN 6
p C_IN 7
p D_IN 10
p E_IN 11
p F_IN 12
p A_OUT 2
p B_OUT 3
p C_OUT 4
p D_OUT 13
p E_OUT 14
p F_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p COM 12
p A_IN 7
p B_IN 8
p C_IN 9
p D_IN 13
p E_IN 14
p F_IN 15
p A_OUT 3
p B_OUT 4
p C_OUT 5
p D_OUT 17
p E_OUT 18
p F_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H189 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p COM 9
p A_IN 5
p B_IN 6
p C_IN 7
p D_IN 10
p E_IN 11
p F_IN 12
p A_OUT 2
p B_OUT 3
p C_OUT 4
p D_OUT 13
p E_OUT 14
p F_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p COM 12
p A_IN 7
p B_IN 8
p C_IN 9
p D_IN 13
p E_IN 14
p F_IN 15
p A_OUT 3
p B_OUT 4
p C_OUT 5
p D_OUT 17
p E_OUT 18
p F_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H209 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 6
p A_IN3 7
p B_IN0 9
p B_IN1 10
p B_IN2 11
p B_IN3 12
p B_IN4 13
p \A_OUT\ 3
p A_OUT 2
p \B_OUT\ 14
p B_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
t PLCC20
g 1
p A_IN0 5
p A_IN1 7
p A_IN2 8
p A_IN3 9
p B_IN0 12
p B_IN1 13
p B_IN2 14
p B_IN3 15
p B_IN4 17
p \A_OUT\ 4
p A_OUT 3
p \B_OUT\ 18
p B_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
*package MC10H210 b
@types 2
g 1 A,B
@pinout
t DIP16,CDIP16
g 1
p A_OUT0 2,12
p A_OUT1 3,13
p A_OUT2 4,14
p A_IN0 5,9
p A_IN1 6,10
p A_IN2 7,11
s VCC1_0 1
s VCC1_1 15
s VCC2 16
s VEE 8
t PLCC20
g 1
p A_OUT0 3,15
p A_OUT1 4,17
p A_OUT2 5,18
p A_IN0 7,12
p A_IN1 8,13
p A_IN2 9,14
s VCC1_0 2
s VCC1_1 19
s VCC2 20
s VEE 10
*package MC10H211 b
@types 2
g 1 A,B
@pinout
t DIP16,CDIP16
g 1
p A_OUT0 2,12
p A_OUT1 3,13
p A_OUT2 4,14
p A_IN0 5,9
p A_IN1 6,10
p A_IN2 7,11
s VCC1_0 1
s VCC1_1 15
s VCC2 16
s VEE 8
t PLCC20
g 1
p A_OUT0 3,15
p A_OUT1 4,17
p A_OUT2 5,18
p A_IN0 7,12
p A_IN1 8,13
p A_IN2 9,14
s VCC1_0 2
s VCC1_1 19
s VCC2 20
s VEE 10
*package MC10H301 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 7
p A_IN3 8
p B_IN0 9
p B_IN1 12
p C_IN0 13
p C_IN1 14
p C_IN2 15
p C_IN3 17
p A_OUT 3
p B_OUT 18
p C_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p A_IN0 3
p A_IN1 4
p A_IN2 5
p A_IN3 6
p B_IN0 7
p B_IN1 9
p C_IN0 10
p C_IN1 11
p C_IN2 12
p C_IN3 13
p A_OUT 2
p B_OUT 14
p C_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10H302 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 7
p A_IN3 8
p B_IN0 9
p B_IN1 12
p C_IN0 13
p C_IN1 14
p C_IN2 15
p C_IN3 17
p A_OUT 3
p B_OUT 18
p C_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p A_IN0 3
p A_IN1 4
p A_IN2 5
p A_IN3 6
p B_IN0 7
p B_IN1 9
p C_IN0 10
p C_IN1 11
p C_IN2 12
p C_IN3 13
p A_OUT 2
p B_OUT 14
p C_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10H303 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 7
p A_IN3 8
p A_IN4 9
p B_IN4 17
p B_IN0 12
p B_IN1 13
p B_IN2 14
p B_IN3 15
p A_OUT 3
p B_OUT 19
p VCC1 2
p VCC2 20
p VEE 10
t DIP16,CDIP16
g 1
p A_IN0 3
p A_IN1 4
p A_IN2 5
p A_IN3 6
p A_IN4 7
p B_IN4 13
p B_IN0 9
p B_IN1 10
p B_IN2 11
p B_IN3 12
p A_OUT 2
p B_OUT 15
p VCC1 1
p VCC2 16
p VEE 8
*package MC10H304 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p A_IN0 4
p A_IN1 5
p A_IN2 7
p A_IN3 8
p B_IN0 13
p B_IN1 14
p B_IN2 15
p B_IN3 17
p A_OUT 3
p C_OUT 18
p VCC1 2
p VCC2 20
p VEE 10
p B_OUT 19
t DIP16,CDIP16
g 1
p A_IN0 3
p A_IN1 4
p A_IN2 5
p A_IN3 6
p B_IN0 10
p B_IN1 11
p B_IN2 12
p B_IN3 13
p A_OUT 2
p C_OUT 14
p VCC1 1
p VCC2 16
p VEE 8
p B_OUT 15
*package MC10H330 b
@types 1
g 1 
@pinout
t DIP24,CDIP24
g 1
p \OE\ 21
p S 9
p W0 8
p W1 7
p W_IN 10
p X0 6
p X1 5
p X_IN 11
p Y0 20
p Y1 19
p Y_IN 14
p Z0 18
p Z1 17
p Z_IN 15
p \RE\ 16
p W_BUS 3
p X_BUS 2
p Y_BUS 23
p Z_BUS 22
p VEE 12
p VCC0_0 4
p VCC0_1 13
p VCC0_2 24
p VCC 1
t PLCC28
g 1
p \OE\ 25
p S 11
p W0 10
p W1 9
p W_IN 12
p X0 7
p X1 6
p X_IN 13
p Y0 24
p Y1 23
p Y_IN 17
p Z0 21
p Z1 20
p Z_IN 18
p \RE\ 19
p W_BUS 4
p X_BUS 3
p Y_BUS 27
p Z_BUS 26
p VEE 14
p VCC0_0 5
p VCC0_1 16
p VCC0_2 28
p VCC 2
*package MC10H332 b
@types 1
g 1 
@pinout
t DIP20,PLCC20,CDIP20
g 1
p \OE\ 18
p X0 3
p X1 4
p X2 5
p X3 6
p S0 7
p S1 8
p Y0 17
p Y1 16
p Y2 15
p Y3 14
p X_IN 9
p \RE\ 13
p Y_IN 12
p X_BUS 2
p Y_BUS 19
p VEE 10
p VCC01 11
p VCC02 20
p VCC 1
*package MC10H334 b
@types 1
g 1 
@pinout
t DIP20,PLCC20,CDIP20
g 1
p \OE\ 17
p \DLE\ 7
p D0 6
p D1 5
p D2 16
p D3 15
p \RLE\ 14
p R0 8
p R1 9
p R2 12
p R3 13
p BUS0 3
p BUS1 2
p BUS2 19
p BUS3 18
p VCC0 1
p VCC01 4
p VCC02 11
p VCC03 20
p VEE 10
*package MC10H350 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN 3
p \A_IN\ 4
p B_IN 6
p \B_IN\ 5
p C_IN 14
p \C_IN\ 13
p D_IN 11
p \D_IN\ 12
p A_OUT 2
p B_OUT 7
p C_OUT 15
p D_OUT 10
p GND 8
p VCC_TTL 16
p VCC_ECL 1
p \OE\ 9
t PLCC20
g 1
p A_IN 4
p \A_IN\ 5
p B_IN 8
p \B_IN\ 7
p C_IN 14
p \C_IN\ 15
p D_IN 18
p \D_IN\ 17
p A_OUT 3
p B_OUT 9
p C_OUT 13
p D_OUT 19
p GND 10
p VCC_TTL 20
p VCC_ECL 2
p \OE\ 12
*package MC10H351 b
@types 1
g 1 
@pinout
t DIP20,PLCC20,CDIP20
g 1
p A_IN 8
p B_IN 7
p C_IN 14
p D_IN 12
p COM 9
p A_OUT 4
p B_OUT 2
p C_OUT 18
p D_OUT 17
p GND 10
p VCC_TTL 11
p VCC_ECL 20
p \A_OUT\ 5
p \B_OUT\ 1
p \C_OUT\ 19
p \D_OUT\ 16
p VCC 6
p VCC2 15
*package MC10H352 b
@types 1
g 1 
@pinout
t DIP20,PLCC20,CDIP20
g 1
p A_IN 8
p B_IN 7
p C_IN 14
p D_IN 12
p COM 9
p A_OUT 4
p B_OUT 2
p C_OUT 18
p D_OUT 17
p GND 10
p VCC_CMOS 11
p VCC_ECL 20
p \A_OUT\ 5
p \B_OUT\ 1
p \C_OUT\ 19
p \D_OUT\ 16
p VCC 6
p VCC2 15
*package MC10H423 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN0 4
p A_IN1 5
p B_IN0 9
p B_IN1 10
p B_IN2 11
p C_IN0 12
p C_IN1 13
p C_IN2 14
p EN 7
p \A_OUT\ 3
p \B_OUT\ 2
p VCC2 16
p VCC1 1
p VEE 8
p A_IN2 6
p \C_OUT\ 15
t PLCC20
g 1
p A_IN0 5
p A_IN1 7
p B_IN0 12
p B_IN1 13
p B_IN2 14
p C_IN0 15
p C_IN1 17
p C_IN2 18
p EN 9
p \A_OUT\ 4
p \B_OUT\ 3
p VCC2 20
p VCC1 2
p VEE 10
p A_IN2 8
p \C_OUT\ 19
*package MC10H424 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p A_IN 5
p STROBE 6
p B_IN 7
p C_IN 10
p D_IN 11
p \A_OUT\ 4
p A_OUT 2
p \B_OUT\ 3
p B_OUT 1
p \C_OUT\ 12
p C_OUT 15
p \D_OUT\ 13
p D_OUT 14
p VCC 9
p GND 16
p VEE 8
t PLCC20
g 1
p A_IN 7
p STROBE 8
p B_IN 9
p C_IN 13
p D_IN 14
p \A_OUT\ 5
p A_OUT 3
p \B_OUT\ 4
p B_OUT 2
p \C_OUT\ 15
p C_OUT 19
p \D_OUT\ 17
p D_OUT 18
p VCC 12
p GND 20
p VEE 10
*package MC12002 b
@types 1
g 1 
@pinout
t DIP14,CDIP14
g 1
p REG_BPS0 1
p REG_BPS1 10
p OSC_IN0 2
p OSC_IN1 3
p NULL_ADJ0 5
p NULL_ADJ1 6
p MIX_SIG_IN0 8
p MIX_SIG_IN1 9
p ALT_ADJ_IN 4
p RES_LOAD 13
p DATA_OUT0 11
p DATA_OUT1 12
p VCC 14
p VEE 7
*package MC12009 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p E1_MECL 13
p E2_MECL 12
p E3_MECL 11
p E4_MTTL 10
p E5_MTTL 9
p CLK 15
p VBB 14
p + 5
p Q 2
p \Q\ 3
p MTTL_OUT 7
p - 4
p VCC 16
p VCCO 1
p MTTL_VCC 6
p VEE 8
*package MC12011 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p E1_MECL 13
p E2_MECL 12
p E3_MECL 11
p E4_MTTL 10
p E5_MTTL 9
p CLK 15
p VBB 14
p + 5
p Q 2
p \Q\ 3
p MTTL_OUT 7
p - 4
p VCC 16
p VCCO 1
p MTTL_VCC 6
p VEE 8
*package MC12013 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p E1_MECL 13
p E2_MECL 12
p E3_MECL 11
p E4_MTTL 10
p E5_MTTL 9
p CLK 15
p VBB 14
p + 5
p Q 2
p \Q\ 3
p MTTL_OUT 7
p - 4
p VCC 16
p VCCO 1
p MTTL_VCC 6
p VEE 8
*package MC12014 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p B1 10
p \P0\ 11
p P1 14
p \P2\ 12
p \P3\ 13
p F_IN 1
p \Z0\ 2
p \Z1\ 3
p \Z2\ 4
p \Z3\ 5
p B2 6
p F_OUT 9
p EN_OUT 7
p VCC 16
p GND 8
*package MC12015 b
@types 1
g 1 
@pinout
t DIP8,SO8,CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12015D b
@types 1
g 1 
@pinout
t SO8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12015L b
@types 1
g 1 
@pinout
t CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12015P b
@types 1
g 1 
@pinout
t DIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12016 b
@types 1
g 1 
@pinout
t DIP8,SO8,CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12016D b
@types 1
g 1 
@pinout
t SO8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12016L b
@types 1
g 1 
@pinout
t CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12016P b
@types 1
g 1 
@pinout
t DIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12017 b
@types 1
g 1 
@pinout
t DIP8,SO8,CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12017D b
@types 1
g 1 
@pinout
t SO8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12017L b
@types 1
g 1 
@pinout
t CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12017P b
@types 1
g 1 
@pinout
t DIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p ACT_PULLUP 2
p OUT 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12018 b
@types 1
g 1 
@pinout
t DIP8,SO8,CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p V_REG 7
p NEG_EDGE 2
p POS_EDGE 3
p VCC 8
p GND 4
p SIG_GND 6
*package MC12019 b
@types 1
g 1 
@pinout
t DIP8,SO8,CDIP8
g 1
p CTRL_IN 1
p SIG_IN 5
p OUTPUT 3
p VCC 7
p GND 4
p SIG_GND 6
*package MC12022A b
@types 1
g 1 
@pinout
t DIP8,SO8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12022AD b
@types 1
g 1 
@pinout
t SO8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12022AP
@types 1
g 1
@pinout
t DIP8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12022B b
@types 1
g 1 
@pinout
t DIP8,SO8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12022BD b
@types 1
g 1 
@pinout
t SO8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12022BP b
@types 1
g 1 
@pinout
t DIP8
g 1
p IN 1
p \IN\ 8
p MC 6
p OUT 4
p SW 3
p VCC 2
p GND 5
*package MC12023 b
@types 1
g 1 
@pinout
t DIP8,SO8
g 1
p SIG_IN 5
p ACT_PULLUP 2
p OUT 3
p VCC 7
p GND 4
p SIG_GND 6
*package MC12025
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p INPUT 6
p \INPUT\ 5
p MOD 1
p OUTPUT 3
p VCC 8
p GND 4
*package MC12040 b
@types 1
g 1 
@pinout
t DIP14,CDIP14
g 1
p R 6
p V 9
p U 4
p \U\ 3
p \D\ 12
p D 11
p VCC1 1
p VCC2 14
p VEE 7
t PLCC20
g 1
p R 9
p V 13
p U 6
p \U\ 4
p \D\ 18
p D 16
p VCC1 2
p VCC2 20
p VEE 10
*package MC12061 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p MECL(+) 15
p MECL(-) 14
p BIAS 7
p CRYS0 5
p CRYS1 6
p SIN(+) 2
p SIN(-) 3
p TTL_OUT 10
p MECL0 12
p MECL1 13
p FILTER 4
p VCC0 1
p VCC1 11
p VCC2 16
p VEE0 8
p VEE1 9
*package MC12073
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p IN0 2
p IN1 3
p OUT0 6
p OUT1 7
p VCC 8
p GND 4
*package MC12074
@types 1
g 1
@pinout
t DIP8,SO8
g 1
p IN0 2
p IN1 3
p OUT0 6
p OUT1 7
p VCC 8
p GND 4
*package MC12090 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p C1 7
p C2 9
p D1 11
p D2 12
p Q 2
p \Q\ 3
p VCC1 1
p VCC2 16
p VEE 8
*package MC1648 b
@types 1
g 1 
@pinout
t DIP14,CDIP14
g 1
p BIAS 10
p TANK 12
p AGC 5
p OUTPUT 3
p VCC1 1
p VCC2 14
p VEE0 7
p VEE1 8
t SO8
g 1
p BIAS 8
p TANK 1
p AGC 5
p OUTPUT 4
p VCC1 3
p VCC2 2
p VEE0 6
p VEE1 7
t PLCC20
g 1
p BIAS 14
p TANK 18
p AGC 8
p OUTPUT 4
p VCC1 2
p VCC2 20
p VEE0 10
p VEE1 12
*package MC1650 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p V1A 6
p Q0 2
p V2A 5
p \CA\ 4
p V1B 12
p V2B 11
p \CB\ 13
p \Q0\ 3
p Q1 14
p \Q1\ 15
p VEE 8
p GND0 1
p GND1 16
p VCC0 7
p VCC1 10
*package MC1651 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p V1A 6
p Q0 2
p V2A 5
p \CA\ 4
p V1B 12
p V2B 11
p \CB\ 13
p \Q0\ 3
p Q1 14
p \Q1\ 15
p VEE 8
p GND0 1
p GND1 16
p VCC0 7
p VCC1 10
*package MC1658 b
@types 1
g 1 
@pinout
t PLCC20
g 1
p VCX 3
p BIAS 15
p FILTER 17
p CX1 14
p CX2 18
p Q 8
p \Q\ 5
p VCC1 2
p VCC2 7
p VEE 10
t DIP16,SO16,CDIP16
g 1
p VCX 2
p BIAS 12
p FILTER 13
p CX1 11
p CX2 14
p Q 6
p \Q\ 4
p VCC1 1
p VCC2 5
p VEE 8
*package MC1662 b
@types 4
g 1 A,B,C,D
@pinout
t CDIP16
g 1
p IN1 4,6,10,12
p IN2 5,7,11,13
p \OUT\ 2,3,14,15
s VCC1 1
s VCC2 16
s VEE 8
*package MC1692 b
@types 4
g 1 A,B,C,D
@pinout
t CDIP16
g 1
p IN1 4,6,10,13
p IN2 5,7,11,12
p OUT 2,3,14,15
s VBB 9
s VCC1 1
s VCC2 16
s VEE 8
*package MC4016 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p Q1 9
p R 13
p CLK 6
p D3 2
p D0 5
p GATE 4
p BUS 12
p D1 11
p \PE\ 3
p D2 14
p Q2 15
p GND 8
p Q3 1
p VCC 16
p Q0 7
p \MR\ 10
*package MC4018 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p Q1 9
p R 13
p CLK 6
p D3 2
p D0 5
p GATE 4
p BUS 12
p D1 11
p \PE\ 3
p D2 14
p Q2 15
p GND 8
p Q3 1
p VCC 16
p Q0 7
p \MR\ 10
*package MC4044 b
@types 1
g 1 
@pinout
t DIP14,CDIP14
g 1
p D2 6
p D1 2
p UF 5
p PU 4
p U2 12
p PD 11
p U1 13
p V 3
p VCC 14
p OUT 8
p R 1
p GND 7
p DF 10
p AMPIN 9
*package MC4316 b
@types 1
g 1 
@pinout
t DIP16,CDIP16
g 1
p Q1 9
p R 13
p CLK 6
p D3 2
p D0 5
p GATE 4
p BUS 12
p D1 11
p \PE\ 3
p D2 14
p Q2 15
p GND 8
p Q3 1
p VCC 16
p Q0 7
p \MR\ 10
*package MC4344 b
@types 1
g 1 
@pinout
t DIP14,CDIP14
g 1
p D2 6
p D1 2
p UF 5
p PU 4
p U2 12
p PD 11
p U1 13
p V 3
p VCC 14
p OUT 8
p R 1
p GND 7
p DF 10
p AMPIN 9
*package MCM10139 b
@types 1
g 1 
@pinout
t CDIP16,CFP16-MO-004
g 1
p A0 10
p A1 11
p A2 12
p A3 13
p A4 14
p \CS\ 15
p D0 1
p D1 2
p D2 3
p D3 4
p D4 5
p D5 6
p D6 7
p D7 9
p VCC 16
p VEE 8
*package MCM10143 b
@types 1
g 1 
@pinout
t CDIP24X
g 1
p \RE\_B 4
p \RE\_C 20
p B0 6
p B1 7
p B2 5
p \WE\_0 9
p \WE\_1 8
p D0 10
p D1 11
p CLK 19
p A0 14
p A1 15
p A2 13
p C0 17
p C1 16
p C2 18
p QB0 3
p QB1 2
p QC0 21
p QC1 22
p VCC0 1
p VCC1 23
p VCC 24
p VEE 12
*package MCM10144 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p A0 1
p A1 2
p A2 3
p A3 4
p A4 9
p A5 10
p A6 11
p A7 12
p \CS1\ 5
p \CS2\ 6
p \CS3\ 7
p \WE\ 14
p D_IN 13
p D_OUT 15
p VCC 16
p VEE 8
*package MCM10145 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p A0 10
p A1 9
p A2 7
p A3 6
p \WE\ 13
p \CS\ 3
p D0 5
p D1 4
p D2 11
p D3 12
p Q0 2
p Q1 1
p Q2 15
p Q3 14
p VCC 16
p VEE 8
*package MCM10146 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 9
p A7 10
p A8 11
p A9 12
p \CS\ 14
p \WE\ 13
p D_IN 15
p D_OUT 1
p VCC 16
p VEE 8
*package MCM10147 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p A0 2
p A1 3
p A2 4
p A3 5
p A4 6
p A5 7
p A6 10
p \CS1\ 14
p \CS2\ 13
p \WE\ 12
p D_IN 11
p D_OUT 15
p VCC1 1
p VEE 8
p VCC2 16
*package MCM10148 b
@types 1
g 1 
@pinout
t CDIP16
g 1
p A0 2
p A1 3
p A2 6
p A3 7
p A4 9
p A5 10
p \CS1\ 4
p \CS2\ 5
p \WE\ 12
p D_IN 13
p D_OUT 15
p VCC1 1
p VEE 8
p VCC2 16
