*version 8.0 222687118
@index
symloc 2N2608 0 67
symloc 2N2609 67 67
symloc 2N3329 134 67
symloc 2N3330 201 67
symloc 2N3331 268 67
symloc 2N3332 335 67
symloc 2N3369 402 67
symloc 2N3370 469 67
symloc 2N3458 536 67
symloc 2N3459 603 67
symloc 2N3460 670 67
symloc 2N3684 737 67
symloc 2N3685 804 67
symloc 2N3686 871 67
symloc 2N3687 938 67
symloc 2N3819 1005 67
symloc 2N3820 1072 67
symloc 2N3821 1139 67
symloc 2N3822 1206 67
symloc 2N3823 1273 67
symloc 2N3824 1340 67
symloc 2N3921 1407 77
symloc 2N3922 1484 77
symloc 2N3954 1561 77
symloc 2N3954A 1638 78
symloc 2N3955 1716 77
symloc 2N3955A:TO71-12 1793 29
symloc 2N3956 1822 77
symloc 2N3957 1899 77
symloc 2N3958 1976 77
symloc 2N3966 2053 67
symloc 2N3967 2120 67
symloc 2N3967A 2187 68
symloc 2N3968 2255 67
symloc 2N3968A 2322 68
symloc 2N3969 2390 67
symloc 2N3969A 2457 68
symloc 2N3970 2525 67
symloc 2N3971 2592 67
symloc 2N3972 2659 67
symloc 2N4084 2726 77
symloc 2N4085 2803 77
symloc 2N4091 2880 67
symloc 2N4092 2947 67
symloc 2N4093 3014 67
symloc 2N4117 3081 67
symloc 2N4117A 3148 68
symloc 2N4118 3216 67
symloc 2N4118A 3283 68
symloc 2N4119 3351 67
symloc 2N4119A 3418 68
symloc 2N4220 3486 67
symloc 2N4220A 3553 68
symloc 2N4221 3621 67
symloc 2N4221A 3688 68
symloc 2N4222 3756 67
symloc 2N4222A 3823 68
symloc 2N4223 3891 67
symloc 2N4224 3958 67
symloc 2N4338 4025 67
symloc 2N4339 4092 67
symloc 2N4340 4159 67
symloc 2N4341 4226 67
symloc 2N4381 4293 67
symloc 2N4391 4360 67
symloc 2N4392 4427 67
symloc 2N4393 4494 67
symloc 2N4416 4561 67
symloc 2N4416A 4628 68
symloc 2N4856 4696 67
symloc 2N4856A 4763 68
symloc 2N4857 4831 67
symloc 2N4857A 4898 68
symloc 2N4858 4966 67
symloc 2N4858A 5033 68
symloc 2N4859 5101 67
symloc 2N4859A 5168 68
symloc 2N4860 5236 67
symloc 2N4860A 5303 68
symloc 2N4861 5371 67
symloc 2N4861A 5438 68
symloc 2N4867 5506 67
symloc 2N4867A 5573 68
symloc 2N4868 5641 67
symloc 2N4868A 5708 68
symloc 2N4869 5776 67
symloc 2N4869A 5843 68
symloc 2N5018 5911 67
symloc 2N5019 5978 67
symloc 2N5020 6045 67
symloc 2N5021 6112 67
symloc 2N5045 6179 77
symloc 2N5046 6256 77
symloc 2N5047 6333 77
symloc 2N5078 6410 67
symloc 2N5103 6477 67
symloc 2N5104 6544 67
symloc 2N5105 6611 67
symloc 2N5114 6678 67
symloc 2N5115 6745 67
symloc 2N5116 6812 67
symloc 2N5196 6879 77
symloc 2N5197 6956 77
symloc 2N5198:TO71-12 7033 28
symloc 2N5199 7061 77
symloc 2N5245 7138 67
symloc 2N5246 7205 67
symloc 2N5247 7272 67
symloc 2N5248 7339 67
symloc 2N5358 7406 67
symloc 2N5359:TO72-25 7473 28
symloc 2N5360 7501 67
symloc 2N5361 7568 67
symloc 2N5362 7635 67
symloc 2N5363 7702 67
symloc 2N5364 7769 67
symloc 2N5397 7836 67
symloc 2N5398 7903 67
symloc 2N5432 7970 67
symloc 2N5433 8037 67
symloc 2N5434 8104 67
symloc 2N5452 8171 77
symloc 2N5453 8248 77
symloc 2N5454 8325 77
symloc 2N5457 8402 67
symloc 2N5458 8469 67
symloc 2N5459 8536 67
symloc 2N5460 8603 67
symloc 2N5461 8670 67
symloc 2N5462 8737 67
symloc 2N5484 8804 67
symloc 2N5485 8871 67
symloc 2N5486 8938 67
symloc 2N5515 9005 77
symloc 2N5516 9082 77
symloc 2N5517 9159 77
symloc 2N5518 9236 77
symloc 2N5519 9313 77
symloc 2N5520 9390 77
symloc 2N5521 9467 77
symloc 2N5522 9544 77
symloc 2N5523 9621 77
symloc 2N5524 9698 77
symloc 2N5545 9775 77
symloc 2N5546 9852 77
symloc 2N5547 9929 77
symloc 2N5555 10006 67
symloc 2N5556 10073 67
symloc 2N5557 10140 67
symloc 2N5558 10207 67
symloc 2N5561 10274 77
symloc 2N5562 10351 77
symloc 2N5563 10428 77
symloc 2N5564 10505 77
symloc 2N5565 10582 77
symloc 2N5566 10659 77
symloc 2N5638 10736 67
symloc 2N5639 10803 67
symloc 2N5640 10870 67
symloc 2N5653 10937 67
symloc 2N5654 11004 67
symloc 2N5668 11071 67
symloc 2N5669 11138 67
symloc 2N5670 11205 67
symloc 2N5902 11272 77
symloc 2N5903 11349 77
symloc 2N5904 11426 77
symloc 2N5905 11503 77
symloc 2N5906 11580 77
symloc 2N5907 11657 77
symloc 2N5908 11734 77
symloc 2N5909 11811 77
symloc 2N5911 11888 77
symloc 2N5912 11965 77
symloc 2N5949 12042 67
symloc 2N5950 12109 67
symloc 2N5951 12176 67
symloc 2N5952 12243 67
symloc 2N5953 12310 67
symloc 2N6483 12377 77
symloc 2N6484 12454 77
symloc 2N6485 12531 77
symloc 2N6905 12608 77
symloc 2N6906 12685 77
symloc 2N6907 12762 77
symloc BC264A 12839 71
symloc BC264B 12910 71
symloc BC264C 12981 71
symloc BC264D 13052 71
symloc BF244A 13123 67
symloc BF244B 13190 67
symloc BF244C 13257 67
symloc BF245A 13324 67
symloc BF245B 13391 67
symloc BF245C 13458 67
symloc BF256A 13525 67
symloc BF256B 13592 67
symloc BF256C 13659 67
symloc DN5564 13726 77
symloc DN5565 13803 77
symloc DN5566 13880 77
symloc DN5567 13957 77
symloc FN4117 14034 67
symloc FN4117A 14101 68
symloc FN4118 14169 67
symloc FN4118A 14236 68
symloc FN4119 14304 67
symloc FN4119A 14371 68
symloc FN4392 14439 67
symloc FN4393 14506 67
symloc J105 14573 65
symloc J106 14638 65
symloc J107 14703 65
symloc J108 14768 65
symloc J109 14833 65
symloc J110 14898 65
symloc J111 14963 65
symloc J112 15028 65
symloc J113 15093 65
symloc J114 15158 65
symloc J174 15223 65
symloc J175 15288 65
symloc J176 15353 65
symloc J177 15418 65
symloc J201 15483 65
symloc J202 15548 65
symloc J203 15613 65
symloc J204 15678 65
symloc J210 15743 65
symloc J211 15808 65
symloc J212 15873 65
symloc J230 15938 65
symloc J231 16003 65
symloc J232 16068 65
symloc J270 16133 65
symloc J271 16198 65
symloc J300 16263 65
symloc J304 16328 65
symloc J305 16393 65
symloc J308 16458 65
symloc J309 16523 65
symloc J310 16588 65
symloc J401 16653 74
symloc J402 16727 74
symloc J403 16801 74
symloc J404 16875 74
symloc J405 16949 74
symloc J406 17023 74
symloc J410 17097 74
symloc J411 17171 74
symloc J412 17245 74
symloc MPF102 17319 67
symloc MPF103 17386 67
symloc MPF104 17453 67
symloc MPF105 17520 67
symloc MPF106 17587 67
symloc MPF107 17654 67
symloc MPF108 17721 67
symloc MPF109 17788 67
symloc MPF110 17855 67
symloc MPF111 17922 67
symloc MPF112 17989 67
symloc MPF256 18056 67
symloc MPF820 18123 67
symloc MPF2608 18190 68
symloc MPF3330 18258 68
symloc MPF3970 18326 68
symloc MPF3971 18394 68
symloc MPF3972 18462 68
symloc MPF4091:TO92-97 18530 29
symloc MPF4092:TO92-97 18559 29
symloc MPF4093 18588 68
symloc MPF4117 18656 68
symloc MPF4117A 18724 69
symloc MPF4118 18793 68
symloc MPF4118A 18861 69
symloc MPF4119 18930 68
symloc MPF4119A 18998 69
symloc MPF4391 19067 68
symloc MPF4392 19135 68
symloc MPF4393 19203 68
symloc MPF4856 19271 68
symloc MPF4856A 19339 69
symloc MPF4857 19408 68
symloc MPF4857A 19476 69
symloc MPF4858 19545 68
symloc MPF4858A 19613 69
symloc MPF4859 19682 68
symloc MPF4859A 19750 69
symloc MPF4860 19819 68
symloc MPF4860A 19887 69
symloc MPF4861 19956 68
symloc MPF4861A 20024 69
symloc NDF9406 20093 78
symloc NDF9407 20171 78
symloc NDF9408 20249 78
symloc NDF9409 20327 78
symloc NDF9410 20405 78
symloc NF5101 20483 67
symloc NF5102 20550 67
symloc NF5103 20617 67
symloc NF5301-2 20684 69
symloc NF5301 20753 67
symloc NF5301-1 20820 69
symloc NF5301-3 20889 69
symloc NPD5564 20958 77
symloc NPD5565 21035 77
symloc NPD5566 21112 77
symloc NPD8301 21189 77
symloc NPD8302 21266 77
symloc NPD8303 21343 77
symloc P1086 21420 66
symloc P1087 21486 66
symloc PF5101 21552 67
symloc PF5102 21619 67
symloc PF5103 21686 67
symloc PF5301 21753 67
symloc PF5301-1 21820 69
symloc PF5301-2 21889 69
symloc PF5301-3 21958 69
symloc PN3684 22027 67
symloc PN3685 22094 67
symloc PN3686 22161 67
symloc PN3687 22228 67
symloc PN4091 22295 67
symloc PN4092 22362 67
symloc PN4093 22429 67
symloc PN4117 22496 67
symloc PN4117A 22563 68
symloc PN4118 22631 67
symloc PN4118A 22698 68
symloc PN4119 22766 67
symloc PN4119A 22833 68
symloc PN4120 22901 67
symloc PN4220 22968 67
symloc PN4221 23035 67
symloc PN4222 23102 67
symloc PN4223 23169 67
symloc PN4224 23236 67
symloc PN4302 23303 67
symloc PN4303 23370 67
symloc PN4304 23437 67
symloc PN4342 23504 67
symloc PN4360 23571 67
symloc PN4391 23638 67
symloc PN4392 23705 67
symloc PN4393 23772 67
symloc PN4416 23839 67
symloc PN4856 23906 67
symloc PN4857 23973 67
symloc PN4858 24040 67
symloc PN4859 24107 67
symloc PN4860 24174 67
symloc PN4861 24241 67
symloc PN5033 24308 67
symloc PN5163 24375 67
symloc PN5432 24442 67
symloc PN5433 24509 67
symloc PN5434 24576 67
symloc TIS58 24643 66
symloc TIS59 24709 66
symloc TIS73 24775 66
symloc TIS74 24841 66
symloc TIS75 24907 66
symloc U200 24973 65
symloc U201 25038 65
symloc U202 25103 65
symloc U257 25168 75
symloc U290 25243 65
symloc U291 25308 65
symloc U304 25373 65
symloc U305 25438 65
symloc U306 25503 65
symloc U308 25568 65
symloc U310 25633 65
symloc U311 25698 65
symloc U401 25763 75
symloc U402 25838 75
symloc U403 25913 75
symloc U404 25988 75
symloc U405 26063 75
symloc U406:TO71-12 26138 26
symloc U410 26164 75
symloc U411 26239 75
symloc U412 26314 75
symloc U427 26389 75
symloc U428 26464 75
symloc U430 26539 75
symloc U431 26614 75
symloc U440 26689 75
symloc U441 26764 75
symloc U443 26839 75
symloc U444 26914 75
symloc U1897 26989 66
symloc U1898 27055 66
symloc U1899 27121 66
symloc TO18-2 27187 81 b
symloc TO18-11 27268 82 b
symloc TO52-7 27350 81 b
symloc TO71-12 27431 92 b
symloc TO72-23 27523 70 b
symloc TO72-25 27593 82 b
symloc TO72-29 27675 82 b
symloc TO78-24 27757 92 b
symloc TO92-92 27849 82 b
symloc TO92-94 27931 82 b
symloc TO92-96 28013 82 b
symloc TO92-97 28095 82 b
symloc TO99 28177 89 b
symloc DIP8 28266 88 b
symloc U309 28354 65
symloc U312 28419 65
*package 2N2608
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N2609
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N3329
@types 1
g 1
@pinout
t TO-72
g 1
p D 3
p G 2
p S 1
*package 2N3330
@types 1
g 1
@pinout
t TO-72
g 1
p D 3
p G 2
p S 1
*package 2N3331
@types 1
g 1
@pinout
t TO-72
g 1
p D 3
p G 2
p S 1
*package 2N3332
@types 1
g 1
@pinout
t TO-72
g 1
p D 3
p G 2
p S 1
*package 2N3369
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3370
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3458
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3459
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3460
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3684
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3685
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3686
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3687
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3819
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package 2N3820
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package 2N3821
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3822
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3823
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3824
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3921
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3922
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3954
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3954A
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3955
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3955A ako TO71-12
*package 2N3956
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3957
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3958
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N3966
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3967
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3967A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3968
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3968A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3969
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3969A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N3970
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3971
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N3972
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4084
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N4085
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N4091
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4092
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4093
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4117
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4117A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4118
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4118A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4119
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4119A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4220
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4220A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4221
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4221A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4222
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4222A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4223
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4224
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4338
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4339
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4340
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4341
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4381
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N4391
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4392
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4393
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4416
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4416A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4856
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4856A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4857
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4857A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4858
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4858A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4859
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4859A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4860
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4860A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4861
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4861A
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package 2N4867
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4867A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4868
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4868A
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package 2N4869
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N4869A
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5018
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5019
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5020
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5021
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5045
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5046
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5047
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5078
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5103
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5104
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5105
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5114
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5115
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5116
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package 2N5196
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5197
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5198 ako TO71-12
*package 2N5199
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5245
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5246
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5247
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5248
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package 2N5358
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5359 ako TO72-25
*package 2N5360
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5361
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5362
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5363
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5364
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5397
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5398
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5432
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package 2N5433
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package 2N5434
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package 2N5452
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5453
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5454
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5457
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5458
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5459
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5460
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5461
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5462
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5484
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5485
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5486
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5515
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5516
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5517
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5518
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5519
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5520
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5521
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5522
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5523
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5524
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5545
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5546
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5547
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5555
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5556
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5557
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5558
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package 2N5561
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5562
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5563
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5564
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5565
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5566
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5638
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5639
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5640
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5653
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5654
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5668
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5669
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5670
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package 2N5902
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5903
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5904
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5905
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5906
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5907
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5908
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5909
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5911
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5912
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N5949
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5950
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5951
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5952
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N5953
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package 2N6483
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N6484
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N6485
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N6905
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N6906
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package 2N6907
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package BC264A
@types 1
g 1
@pinout
t TO-92-18B
g 1
p G 1
p S 2
p D 3
*package BC264B
@types 1
g 1
@pinout
t TO-92-18B
g 1
p G 1
p S 2
p D 3
*package BC264C
@types 1
g 1
@pinout
t TO-92-18B
g 1
p G 1
p S 2
p D 3
*package BC264D
@types 1
g 1
@pinout
t TO-92-18B
g 1
p G 1
p S 2
p D 3
*package BF244A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package BF244B
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package BF244C
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package BF245A
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package BF245B
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package BF245C
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package BF256A
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package BF256B
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package BF256C
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package DN5564
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package DN5565
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package DN5566
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package DN5567
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package FN4117
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4117A
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4118
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4118A
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4119
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4119A
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package FN4392
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package FN4393
@types 1
g 1
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package J105
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J106
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J107
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J108
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J109
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J110
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J111
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J112
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J113
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J114
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J174
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J175
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J176
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J177
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J201
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J202
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J203
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J204
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J210
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J211
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J212
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J230
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J231
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J232
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J270
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J271
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package J300
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J304
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J305
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J308
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J309
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J310
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package J401
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J402
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J403
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J404
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J405
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J406
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J410
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J411
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package J412
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package MPF102
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF103
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF104
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF105
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF106
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF107
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF108
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF109
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF110
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF111
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF112
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF256
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF820
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF2608
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF3330
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF3970
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF3971
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF3972
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4091 ako TO92-97
*package MPF4092 ako TO92-97
*package MPF4093
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4117
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4117A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4118
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4118A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4119
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4119A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4391
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4392
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4393
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4856
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4856A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4857
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4857A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4858
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4858A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4859
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4859A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4860
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4860A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4861
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package MPF4861A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package NDF9406
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package NDF9407
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package NDF9408
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package NDF9409
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package NDF9410
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package NF5101
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5102
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5103
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5301-2
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5301
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5301-1
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NF5301-3
@types 1
g 1
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package NPD5564
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p S 1,5
p D 2,6
p G 4,8
*package NPD5565
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p S 1,5
p D 2,6
p G 4,8
*package NPD5566
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p S 1,5
p D 2,6
p G 4,8
*package NPD8301
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 2,6
p G 4,8
p S 1,5
*package NPD8302
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 2,6
p G 4,8
p S 1,5
*package NPD8303
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p D 2,6
p G 4,8
p S 1,5
*package P1086
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package P1087
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5101
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5102
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5103
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5301
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5301-1
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5301-2
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PF5301-3
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN3684
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN3685
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN3686
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN3687
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4091
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4092
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4093
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4117
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4117A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4118
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4118A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4119
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4119A
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4120
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4220
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4221
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4222
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4223
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4224
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4302
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4303
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4304
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4342
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4360
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4391
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4392
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4393
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4416
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4856
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4857
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4858
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4859
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4860
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN4861
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN5033
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN5163
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN5432
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN5433
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package PN5434
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package TIS58
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package TIS59
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 2
p S 3
*package TIS73
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package TIS74
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package TIS75
@types 1
g 1
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package U200
@types 1
g 1
@pinout
t TO-18
g 1
p S 1
p D 2
p G 3
*package U201
@types 1
g 1
@pinout
t TO-18
g 1
p S 1
p D 2
p G 3
*package U202
@types 1
g 1
@pinout
t TO-18
g 1
p S 1
p D 2
p G 3
*package U257
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package U290
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package U291
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package U304
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package U305
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package U306
@types 1
g 1
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package U308
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package U310
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package U311
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package U401
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U402
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U403
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U404
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U405
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U406 ako TO71-12
*package U410
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U411
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U412
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U427
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package U428
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package U430
@types 2
g 1 A,B
@pinout
t TO-99
g 1
p D 3,5
p G 2,6
p S 1,7
*package U431
@types 2
g 1 A,B
@pinout
t TO-99
g 1
p D 3,5
p G 2,6
p S 1,7
*package U440
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U441
@types 2
g 1 A,B
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package U443
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package U444
@types 2
g 1 A,B
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package U1897
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package U1898
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package U1899
@types 1
g 1
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package TO18-2 b
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p D 2
p G 3
p S 1
*package TO18-11 b
@types 1
g 1
@attributes
@pinout
t TO-18
g 1
p D 3
p G 2
p S 1
*package TO52-7 b
@types 1
g 1
@attributes
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package TO71-12 b
@types 2
g 1 A,B
@attributes
@pinout
t TO-71
g 1
p D 2,6
p G 3,7
p S 1,5
*package TO72-23 b
@types 1
g 1
@pinout
t TO-72
g 1
p S 1
p D 2
p G 3
*package TO72-25 b
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package TO72-29 b
@types 1
g 1
@attributes
@pinout
t TO-72
g 1
p D 2
p G 3
p S 1
*package TO78-24 b
@types 2
g 1 A,B
@attributes
@pinout
t TO-78
g 1
p D 2,6
p G 3,7
p S 1,5
*package TO92-92 b
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p D 3
p G 1
p S 2
*package TO92-94 b
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p D 3
p G 2
p S 1
*package TO92-96 b
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p D 2
p G 1
p S 3
*package TO92-97 b
@types 1
g 1
@attributes
@pinout
t TO-92
g 1
p D 1
p G 3
p S 2
*package TO99 b
@types 2
g 1 A,B
@attributes
@pinout
t TO-99
g 1
p D 3,5
p G 2,6
p S 1,7
*package DIP8 b
@types 2
g 1 A,B
@attributes
@pinout
t DIP8
g 1
p D 3,6
p G 4,7
p S 2,5
*package U309
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
*package U312
@types 1
g 1
@pinout
t TO-52
g 1
p D 2
p G 3
p S 1
