*version 7.1 999012552
@index
symloc AD648A:2D8C8 0 26
symloc AD648B:2D8C8 26 26
symloc AD648C:2D8C8 52 26
symloc AD741:741 78 23
symloc CA723:D14D 101 24
symloc CA3085 125 111
symloc HA-2600 236 249
symloc HA-5154 485 187
symloc L161 672 122
symloc LAS1505:15XX 794 26
symloc LAS1512:15XX 820 26
symloc LAS1515:15XX 846 26
symloc LAS1805:TO3 872 25
symloc LAS1812:TO3 897 25
symloc LAS1815:TO3 922 25
symloc LF411:411 947 23
symloc LF412:2D8C8 970 25
symloc LM101A:101 995 24
symloc LM108:D8C8B 1019 25
symloc LM111:111 1044 23
symloc LM117:VREG-ADJ 1067 28
symloc LM117HVH 1095 144
symloc LM118:118 1239 23
symloc LM119:2D14C10A 1262 28
symloc LM120K-5:TO3 1290 26
symloc LM124:4D14 1316 24
symloc LM129 1340 60
symloc LM137HVH 1400 108
symloc LM138:VREG-ADJ 1508 28
symloc LM139 1536 185
symloc LM140-5:78XX 1721 26
symloc LM140A-5:78XX 1747 27
symloc LM140-12:78XX 1774 27
symloc LM140-15:78XX 1801 27
symloc LM150 1828 106
symloc LM158:2D8C8 1934 25
symloc LM185 1959 130
symloc LM193:2D8C8 2089 25
symloc LM196:196 2114 23
symloc LM201A:101 2137 24
symloc LM208:D8C8B 2161 25
symloc LM211:111 2186 23
symloc LM218:118 2209 23
symloc LM219:2D14C10A 2232 28
symloc LM224:4D14 2260 24
symloc LM239 2284 185
symloc LM258:2D8C8 2469 25
symloc LM293:2D8C8 2494 25
symloc LM301A:101 2519 24
symloc LM308:D8C8B 2543 25
symloc LM311:111 2568 23
symloc LM318:118 2591 23
symloc LM319:2D14C10A 2614 28
symloc LM320K-5:TO3 2642 26
symloc LM320T-5:TO220 2668 28
symloc LM324:4D14 2696 24
symloc LM339:4D14F20C 2720 28
symloc LM340-5:78XX 2748 26
symloc LM340A-5:78XX 2774 27
symloc LM340-12:78XX 2801 27
symloc LM340-15:78XX 2828 27
symloc LM358:2D8C8 2855 25
symloc LM393:2D8C8 2880 25
symloc LM675:675 2905 23
symloc LM709:709 2928 23
symloc LM709A:709 2951 24
symloc LM709C:709 2975 24
symloc LM723:D14D 2999 24
symloc LM723C:D14D 3023 25
symloc LM741:741 3048 23
symloc LM3302 3071 114
symloc LM7805C:78XX 3185 26
symloc LM7812C:78XX 3211 26
symloc LM7815C:78XX 3237 26
symloc LM7905C:79XX 3263 26
symloc LM7912C:79XX 3289 26
symloc LM7915C:79XX 3315 26
symloc LT1084C 3341 108
symloc LM120K-12:TO3 3449 27
symloc LM120K-15:TO3 3476 27
symloc LM140A-12:78XX 3503 28
symloc LM140A-15:78XX 3531 28
symloc LM320K-12:TO3 3559 27
symloc LM320K-15:TO3 3586 27
symloc LM320T-12:TO220 3613 29
symloc LM320T-15:TO220 3642 29
symloc LM340A-12:78XX 3671 28
symloc LM340A-15:78XX 3699 28
symloc MC1458:2D8C8 3727 26
symloc MC1458C:2D8C8 3753 27
symloc MC1458S:2D8C8 3780 27
symloc MC1558:2D8C8 3807 26
symloc MC1558S:2D8C8 3833 27
symloc MC1709:1709 3860 25
symloc MC1709A:1709 3885 26
symloc MC1709C:1709 3911 26
symloc MC1723C:D14D 3937 26
symloc MC1741:1741 3963 25
symloc MC7805C:78XX 3988 26
symloc MC7812C:78XX 4014 26
symloc MC7815C:78XX 4040 26
symloc MC7905C:79XX 4066 26
symloc MC7912C:79XX 4092 26
symloc MC7915C:79XX 4118 26
symloc MC33076:33076 4144 27
symloc MPR155 4171 110
symloc OP-07:OP07 4281 24
symloc OP-27:OP07 4305 24
symloc OP-471A 4329 261
symloc OP-471E 4590 115
symloc OP-471F 4705 115
symloc OP-471G 4820 185
symloc OPA3581J:3581 5005 27
symloc OPA3582J:3581 5032 27
symloc OPA3583:3581 5059 26
symloc OPA3584J:3584 5085 27
symloc PM-741:PM741 5112 26
symloc RC723:D14D 5138 24
symloc REF-02 5162 126
symloc SG137 5288 177
symloc SG340-5 5465 108
symloc SG340-12 5573 109
symloc SG723C:D14D 5682 25
symloc SG7805C 5707 108
symloc SG7805 5815 71
symloc SG7812 5886 71
symloc SG7812C 5957 72
symloc SG7815C 6029 108
symloc SG7905C 6137 108
symloc SG7912C 6245 108
symloc SG7915C 6353 108
symloc SG7915 6461 71
symloc SMX10114 6532 112
symloc TL082 6644 91
symloc TL084:4D14 6735 24
symloc TL780-05C:780 6759 27
symloc TL780-12C:780 6786 27
symloc TL780-15C:780 6813 27
symloc TL783C:783 6840 24
symloc UA723 6864 136
symloc uA709:709 7000 23
symloc UA709A:709 7023 24
symloc UA709C:709 7047 24
symloc uA723C:D14D 7071 25
symloc uA723M:D14D 7096 25
symloc uA741:741 7121 23
symloc UA771 7144 97
symloc UA771A 7241 98
symloc UA772 7339 91
symloc UA772A 7430 92
symloc UA772L 7522 96
symloc UA798 7618 91
symloc uA7805C:78XX 7709 26
symloc uA7812C:78XX 7735 26
symloc uA7815C 7761 108
symloc uA7905C:79XX 7869 26
symloc uA7912C:79XX 7895 26
symloc uA7915C:79XX 7921 26
symloc UC7805C 7947 108
symloc UA7805 8055 115
symloc UC7812C 8170 108
symloc UC7815C 8278 108
symloc UA78M05 8386 116
symloc F78M12 8502 115
symloc UA78M12 8617 116
symloc UA78M15 8733 116
symloc UA79M05 8849 76
symloc UA79M15 8925 76
symloc UC7905C 9001 108
symloc UC7912C 9109 108
symloc UC7915C 9217 108
symloc UPC7805:78XX 9325 26
symloc UPC7812:78XX 9351 26
symloc VREG-ADJ 9377 158 b
symloc D8C8B 9535 115 b
symloc D14D 9650 149 b
symloc OP07 9799 116 b
symloc PM741 9915 100 b
symloc TO3 10015 82 b
symloc TO220 10097 86 b
symloc 2D8C8 10183 111 b
symloc 2D14C10A 10294 182 b
symloc 4D14 10476 126 b
symloc 4D14F20C 10602 190 b
symloc 78XX 10792 119 b
symloc 79XX 10911 119 b
symloc 15XX 11030 83 b
symloc 101 11113 188 b
symloc 111 11301 186 b
symloc 118 11487 120 b
symloc 196 11607 82 b
symloc 411 11689 113 b
symloc 471 11802 341 b
symloc 675 12143 95 b
symloc 709 12238 190 b
symloc 741 12428 115 b
symloc 771 12543 113 b
symloc 772 12656 107 b
symloc 780 12763 84 b
symloc 783 12847 84 b
symloc 798 12931 107 b
symloc 1709 13038 120 b
symloc 1741 13158 119 b
symloc 3581 13277 110 b
symloc 3584 13387 117 b
symloc 33076 13504 159 b
symloc LM124A 13663 114
symloc LM12CLK 13777 83
symloc LM317K 13860 71
symloc LM317H 13931 72
symloc LM317T 14003 73
symloc LM385Z-1.2 14076 65
symloc LM385M-1.2 14141 63
symloc MAX402CPA 14204 99
symloc MAX402CSA 14303 98
symloc MAX402EPA 14401 99
symloc MAX402ESA 14500 98
symloc LM759CP 14598 83
symloc LM759CH 14681 97
symloc MAX403CPA 14778 99
symloc MAX403CSA 14877 98
symloc MAX403EPA 14975 99
symloc MAX403ESA 15074 98
*package AD648A ako 2D8C8
*package AD648B ako 2D8C8
*package AD648C ako 2D8C8
*package AD741 ako 741
*package CA723 ako D14D
*package CA3085
@types 1
g 1
@pinout
t TO-5
g 1
p OUT 1
p V- 4
p COMP 7
p IN- 6
p VIN 3
p CB 2
p CL 8
p Vref 5
*package HA-2600
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p COMP 8
p B2 5
p B1 1
t LCC20
g 1
p + 7
p - 5
p V+ 17
p V- 10
p OUT 15
p COMP 20
p B2 2
p B1 12
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p COMP 8
p B2 5
p B1 1
*package HA-5154
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V- 11
s V+ 4
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
*package L161
@types 4
g 1 A,B,C,D
@pinout
t DIP16
g 1
p + 1,3,6,8
p - 2,4,5,7
p OUT 13,12,11,10
s V- 9
s V+ 16
s ISET 15
*package LAS1505 ako 15XX
*package LAS1512 ako 15XX
*package LAS1515 ako 15XX
*package LAS1805 ako TO3
*package LAS1812 ako TO3
*package LAS1815 ako TO3
*package LF411 ako 411
*package LF412 ako 2D8C8
*package LM101A ako 101
*package LM108 ako D8C8B
*package LM111 ako 111
*package LM117 ako VREG-ADJ
*package LM117HVH
@types 1
g 1
@pinout
t TO-220
g 1
p IN 3
p OUT 2
p ADJ 1
t TO-3
g 1
p IN 2
p OUT 3
p ADJ 1
t TO-39
g 1
p IN 1
p OUT 3
p ADJ 2
*package LM118 ako 118
*package LM119 ako 2D14C10A
*package LM120K-5 ako TO3
*package LM124 ako 4D14
*package LM129
@types 1
g 1
@pinout
t TO-46
g 1
p A 2
p C 1
*package LM137HVH
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p ADJ 1
t TO-39
g 1
p IN 3
p OUT 2
p ADJ 1
*package LM138 ako VREG-ADJ
*package LM139
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 7,5,9,11
p - 6,4,8,10
p OUT 1,2,14,13
s V+ 3
s V- 12
t LCC20
g 1
p + 10,8,13,16
p - 9,6,12,14
p OUT 2,3,20,19
s V+ 4
s V- 18
*package LM140-5 ako 78XX
*package LM140A-5 ako 78XX
*package LM140-12 ako 78XX
*package LM140-15 ako 78XX
*package LM150
@types 1
g 1
@pinout
t TO-3
g 1
p IN 2
p ADJ 1
p OUT 3
t TO-220
g 1
p IN 3
p ADJ 1
p OUT 2
*package LM158 ako 2D8C8
*package LM185
@types 1
g 1
@pinout
t SO8
g 1
p + 8
p - 4
p ADJ 5
t TO-92
g 1
p + 2
p - 3
p ADJ 1
t TO-46
g 1
p + 2
p - 3
p ADJ 1
*package LM193 ako 2D8C8
*package LM196 ako 196
*package LM201A ako 101
*package LM208 ako D8C8B
*package LM211 ako 111
*package LM218 ako 118
*package LM219 ako 2D14C10A
*package LM224 ako 4D14
*package LM239
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 7,5,9,11
p - 6,4,8,10
p OUT 1,2,14,13
s V+ 3
s V- 12
t LCC20
g 1
p + 10,8,13,16
p - 9,6,12,14
p OUT 2,3,20,19
s V+ 4
s V- 18
*package LM258 ako 2D8C8
*package LM293 ako 2D8C8
*package LM301A ako 101
*package LM308 ako D8C8B
*package LM311 ako 111
*package LM318 ako 118
*package LM319 ako 2D14C10A
*package LM320K-5 ako TO3
*package LM320T-5 ako TO220
*package LM324 ako 4D14
*package LM339 ako 4D14F20C
*package LM340-5 ako 78XX
*package LM340A-5 ako 78XX
*package LM340-12 ako 78XX
*package LM340-15 ako 78XX
*package LM358 ako 2D8C8
*package LM393 ako 2D8C8
*package LM675 ako 675
*package LM709 ako 709
*package LM709A ako 709
*package LM709C ako 709
*package LM723 ako D14D
*package LM723C ako D14D
*package LM741 ako 741
*package LM3302
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 5,7,9,11
p - 4,6,8,10
p OUT 2,1,14,13
s V+ 3
s V- 12
*package LM7805C ako 78XX
*package LM7812C ako 78XX
*package LM7815C ako 78XX
*package LM7905C ako 79XX
*package LM7912C ako 79XX
*package LM7915C ako 79XX
*package LT1084C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 2
p ADJ 1
p OUT 3
t TO-220
g 1
p IN 3
p ADJ 1
p OUT 2
*package LM120K-12 ako TO3
*package LM120K-15 ako TO3
*package LM140A-12 ako 78XX
*package LM140A-15 ako 78XX
*package LM320K-12 ako TO3
*package LM320K-15 ako TO3
*package LM320T-12 ako TO220
*package LM320T-15 ako TO220
*package LM340A-12 ako 78XX
*package LM340A-15 ako 78XX
*package MC1458 ako 2D8C8
*package MC1458C ako 2D8C8
*package MC1458S ako 2D8C8
*package MC1558 ako 2D8C8
*package MC1558S ako 2D8C8
*package MC1709 ako 1709
*package MC1709A ako 1709
*package MC1709C ako 1709
*package MC1723C ako D14D
*package MC1741 ako 1741
*package MC7805C ako 78XX
*package MC7812C ako 78XX
*package MC7815C ako 78XX
*package MC7905C ako 79XX
*package MC7912C ako 79XX
*package MC7915C ako 79XX
*package MC33076 ako 33076
*package MPR155
@types 1
g 1
@pinout
t DIP14
g 1
p + 5
p - 4
p V- 6
p V+ 11
p VC 3
p BW1 12
p OUT 10
p BW2 14
*package OP-07 ako OP07
*package OP-27 ako OP07
*package OP-471A
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package OP-471E
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-471F
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package OP-471G
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t DIP16
g 1
p + 3,5,12,14
p - 2,6,9,11
p OUT 1,7,10,16
s V+ 4
s V- 13
*package OPA3581J ako 3581
*package OPA3582J ako 3581
*package OPA3583 ako 3581
*package OPA3584J ako 3584
*package PM-741 ako PM741
*package RC723 ako D14D
*package REF-02
@types 1
g 1
@pinout
t DIP8
g 1
p IN 2
p OUT 6
p TEMP 3
p TRIM 5
t TO-99
g 1
p IN 2
p OUT 6
p TEMP 3
p TRIM 5
*package SG137
@types 1
g 1
@pinout
t TO-66
g 1
p IN 3
p OUT 2
p ADJ 1
t TO-3
g 1
p IN 3
p OUT 2
p ADJ 1
t TO-39
g 1
p IN 3
p OUT 2
p ADJ 1
t LCC20
g 1
p IN 11
p OUT 1
p ADJ 16
*package SG340-5
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package SG340-12
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package SG723C ako D14D
*package SG7805C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package SG7805
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
*package SG7812
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
*package SG7812C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
*package SG7815C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package SG7905C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package SG7912C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package SG7915C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package SG7915
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
*package SMX10114
@types 1
g 1
@pinout
t DIP18
g 1
p + 5
p - 4
p V- 6
p V+ 14
p VC 1
p BW1 15
p OUT 13
p BW2 18
*package TL082
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package TL084 ako 4D14
*package TL780-05C ako 780
*package TL780-12C ako 780
*package TL780-15C ako 780
*package TL783C ako 783
*package UA723
@types 1
g 1
@pinout
t DIP14
g 1
p Vcc+ 12
p Vc 11
p OUT 10
p Vcc- 7
p COMP 13
p - 4
p + 5
p CL 2
p CS 3
p Vref 6
p Vz 9
*package uA709 ako 709
*package UA709A ako 709
*package UA709C ako 709
*package uA723C ako D14D
*package uA723M ako D14D
*package uA741 ako 741
*package UA771
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 5
*package UA771A
@types 1
g 1
@pinout
t DIP8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 5
*package UA772
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package UA772A
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package UA772L
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package UA798
@types 2
g 1 A,B
@pinout
t DIP8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package uA7805C ako 78XX
*package uA7812C ako 78XX
*package uA7815C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 3
p GND 2
*package uA7905C ako 79XX
*package uA7912C ako 79XX
*package uA7915C ako 79XX
*package UC7805C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package UA7805
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 2
p COMMON 3
t LCC20
g 1
p IN 10
p OUT 15
p COMMON 2
*package UC7812C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package UC7815C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 2
p GND 3
*package UA78M05
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 2
p COMMON 3
t LCC20
g 1
p IN 10
p OUT 15
p COMMON 2
*package F78M12
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 2
p COMMON 3
t LCC20
g 1
p IN 10
p OUT 15
p COMMON 2
*package UA78M12
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 2
p COMMON 3
t LCC20
g 1
p IN 10
p OUT 15
p COMMON 2
*package UA78M15
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 2
p COMMON 3
t LCC20
g 1
p IN 10
p OUT 15
p COMMON 2
*package UA79M05
@types 1
g 1
@pinout
t TO-39
g 1
p IN 3
p OUT 2
p COMMON 1
*package UA79M15
@types 1
g 1
@pinout
t TO-39
g 1
p IN 3
p OUT 2
p COMMON 1
*package UC7905C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package UC7912C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package UC7915C
@types 1
g 1
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 3
p OUT 2
p GND 1
*package UPC7805 ako 78XX
*package UPC7812 ako 78XX
*package VREG-ADJ b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 2
p ADJ 1
p OUT 3
t TO-39
g 1
p IN 1
p ADJ 2
p OUT 3
t TO-220
g 1
p IN 3
p ADJ 1
p OUT 2
*package D8C8B b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C2 8
p C1 1
*package D14D b
@types 1
g 1
@attributes
@pinout
t DIP14
g 1
p CL 2
p CS 3
p - 4
p + 5
p VREF 6
p VCC- 7
p VZ 9
p OUT 10
p VC 11
p VCC+ 12
p COMP 13
*package OP07 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 8
*package PM741 b
@types 1
g 1
@pinout
t TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 5
*package TO3 b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
*package TO220 b
@types 1
g 1
@attributes
@pinout
t TO-220
g 1
p IN 2
p OUT 3
p GND 1
*package 2D8C8 b
@types 2
g 1 A,B
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package 2D14C10A b
@types 2
g 1 A,B
@attributes
@pinout
t DIP14
g 1
p + 4,9
p - 5,10
p OUT 12,7
p G 3,8
s V+ 11
s V- 6
t TO-100
g 1
p + 3,8
p - 4,9
p OUT 1,6
p G 2,7
s V+ 10
s V- 5
*package 4D14 b
@types 4
g 1 A,B,C,D
@attributes
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package 4D14F20C b
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 5,7,9,11
p - 4,6,8,10
p OUT 2,1,14,13
s V+ 3
s V- 12
t LCC20
g 1
p + 10,8,13,16
p - 9,6,12,14
p OUT 2,3,20,19
s V+ 4
s V- 18
*package 78XX b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
t TO-220
g 1
p IN 1
p OUT 3
p GND 2
*package 79XX b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 3
p OUT 2
p GND 1
t TO-220
g 1
p IN 2
p OUT 3
p GND 1
*package 15XX b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 1
p OUT 2
p GND 3
*package 101 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
p B 5
t DIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p C1 3
p C2 12
p B 9
*package 111 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 2
p - 3
p V+ 8
p V- 4
p OUT 7
p G 1
p B 5
p B/S 6
t DIP14
g 1
p + 3
p - 4
p V+ 11
p V- 6
p OUT 9
p G 2
p B 7
p B/S 8
*package 118 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p C1 1
p C2 8
p C3 5
*package 196 b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p IN 3
p ADJ 2
p OUT 1
*package 411 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p B1 1
p B2 5
*package 471 b
@types 4
g 1 A,B,C,D
@attributes
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
t DIP16
g 1
p + 3,5,12,14
p - 2,6,9,11
p OUT 1,7,10,16
s V+ 4
s V- 13
t LCC20
g 1
p + 4,8,14,18
p - 3,9,13,19
p OUT 2,10,12,20
s V+ 6
s V- 16
t LCC28
g 1
p + 6,10,20,24
p - 3,13,17,27
p OUT 2,14,16,28
s V+ 8
s V- 22
*package 675 b
@types 1
g 1
@attributes
@pinout
t TO-220
g 1
p + 1
p - 2
p OUT 4
p V+ 5
p V- 3
*package 709 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p CA 1
p CB 8
p CO 5
t DIP14
g 1
p + 5
p - 4
p V+ 11
p V- 6
p OUT 10
p CA 3
p CB 12
p CO 9
*package 741 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-99
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 5
*package 771 b
@types 1
g 1
@attributes
@pinout
t DIP8,SO8
g 1
p + 3
p - 2
p V+ 7
p V- 4
p OUT 6
p OS1 1
p OS2 5
*package 772 b
@types 2
g 1 A,B
@attributes
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package 780 b
@types 1
g 1
@attributes
@pinout
t TO-220
g 1
p IN 1
p OUT 3
p GND 2
*package 783 b
@types 1
g 1
@attributes
@pinout
t TO-220
g 1
p IN 3
p ADJ 1
p OUT 2
*package 798 b
@types 2
g 1 A,B
@attributes
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
*package 1709 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-5
g 1
p + 3
p - 2
p OUT 6
p V+ 7
p V- 4
p CA 1
p CB 8
p CO 5
*package 1741 b
@types 1
g 1
@attributes
@pinout
t DIP8,TO-5,SO8
g 1
p + 3
p - 2
p OUT 6
p V+ 7
p V- 4
p OS1 1
p OS2 5
*package 3581 b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p + 6
p - 5
p OUT 1
p V+ 2
p V- 7
p OS1 3
p OS2 4
*package 3584 b
@types 1
g 1
@attributes
@pinout
t TO-3
g 1
p + 6
p - 5
p OUT 1
p V+ 2
p V- 7
p OS1 3
p OS2 4
p Cc 8
*package 33076 b
@types 2
g 1 A,B
@pinout
t DIP8,SO8
g 1
p + 3,5
p - 2,6
p OUT 1,7
s V+ 8
s V- 4
t DIP16
g 1
p + 2,7
p - 1,8
p OUT 16,9
s V+ 14
s V- 4,5,12,13
*package LM124A
@types 4
g 1 A,B,C,D
@pinout
t DIP14
g 1
p + 3,5,10,12
p - 2,6,9,13
p OUT 1,7,8,14
s V+ 4
s V- 11
*package LM12CLK
@types 1
g 1
@pinout
t K04A
g 1
p + 2
p - 1
p V+ 3
p V- 5
p OUT 4
*package LM317K
@types 1
g 1
@pinout
t TO-3
g 1
p IN 2
p OUT 3
p ADJ 1
*package LM317H
@types 1
g 1
@pinout
t TO-39
g 1
p IN 1
p OUT 3
p ADJ 2
*package LM317T
@types 1
g 1
@pinout
t TO-220
g 1
p IN 3
p OUT 2
p ADJ 1
*package LM385Z-1.2
@types 1
g 1
@pinout
t TO-92
g 1
p A 3
p K 2
*package LM385M-1.2
@types 1
g 1
@pinout
t SO8
g 1
p A 4
p K 8
*package MAX402CPA
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX402CSA
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX402EPA
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX402ESA
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package LM759CP
@types 1
g 1
@pinout
t P04A
g 1
p + 2
p - 1
p V+ 4
p V- 5
p OUT 3
*package LM759CH
@types 1
g 1
@pinout
t H08C
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX403CPA
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX403CSA
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX403EPA
@types 1
g 1
@pinout
t DIP8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
*package MAX403ESA
@types 1
g 1
@pinout
t SO8
g 1
p - 2
p + 3
p OUT 6
p V+ 7
p N1 1
p N2 5
p V- 4
