M48
; DRILL file {KiCad 9.0.5} date 2025-12-05T20:02:41-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-05T20:02:41-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X134.05Y-73.825
T2
X53.0Y-68.0
X53.0Y-87.0
X141.0Y-68.0
X141.0Y-87.0
T3
X134.6Y-78.475
X138.4Y-78.475
M30
